### ISSUE TITLE
[TW#15470] Memory leak in commit de10032

### ISSUE THREAD

**Issue by jaracil** [espressif/esp-idf#1001]
I isolated a commit with memory leak.

commit: de10032717d18b323b6d49a7903167c6621e09a5

This commit is too large and I could not locate the place of the leak. There are many changes to the new memory allocation system

**Comment by lucazader** [comment]
The espressif team might need some more information about what your program does and what parts of the idf you are using to try and track down the bug.

Does the leak increase after a certain function or area of your code is called?

**Comment by jaracil** [comment]
My use case is a BLE device. I print the free heap after each cycle of connection / disconnection from BLE central. The heap after cycles remains stable but since the indicated commit there is a ~1k leak each cycle.

Hope that helps but checking the leak within the conn/disconn cycle is very complex, since I make intensive use of the heap.

Thanks.

**Comment by lucazader** [comment]
Do you do any communication (eg and read write or notifys of any
characteristic) between the connection and disconnection?

I reported a memory leak in the set characteristic function a while back,
however I am unsure if it has been fixed yet.

**Comment by jaracil** [comment]
Yes. In communications are  Write command and Notifications of one characteristic.

If you take a look at the commit, you will see that there are a lot of substitutions like: 
GKI_getbuf(...) -> osi_malloc(...)
GKI_freebuf(...) ->  osi_free(...)

My intuition tells me that there is a malloc without its free. But there are some parts of the code where it is not trivial to follow it.

**Comment by garacil** [comment]
Hello everyone!

My name is German Aracil Boned. I'm from spain. It could be, but I'm not James Bond's family :-)

Is posible show a debug if you add file "allocator.h" in your project and call function osi_mem_dbg_show()" after connect event. You need modify file allocator.h first because function osi_mem_dbg_show() have a mistake like "BT: osi_mem_dbg_record invalid !! size 0". You need comment these lines like:
 
/*    if (!p || size == 0) {
        LOG_ERROR("%s invalid !! size %i\n", __func__, size);
        return;
    }
*/

Remember set "CONFIG_BLUEDROID_MEM_DEBUG" first and compile. Please if is posible, dump result here to compare with me.

I have the same problem but, only 908 bytes of memory leak every one. Remember, "you have 2 responsibilities regarding any block of memory allocated: (1) always preserve a pointer to the starting address for the block of memory so, (2) it can be freed when it is no longer needed. Freeing the memory is up to you."

First connection: Free heap: 113492
Second connection: Free heap: 112584

My dump:

First connection:

E (2787) BT: --> p 0x3ffdbeb8, s 8, f btc_to_bta_adv_data, l 262
E (2797) BT: --> p 0x3ffd2a88, s 24, f fixed_queue_new, l 42
E (2797) BT: --> p 0x3ffd2aa4, s 20, f osi_calloc_func, l 150
E (2807) BT: --> p 0x3ffd5790, s 24, f fixed_queue_new, l 42
E (2817) BT: --> p 0x3ffd5800, s 20, f osi_calloc_func, l 150
E (2817) BT: --> p 0x3ffd58c0, s 20, f osi_calloc_func, l 150
E (2827) BT: --> p 0x3ffd5abc, s 32, f osi_calloc_func, l 150
E (2837) BT: --> p 0x3ffd5ae0, s 168, f osi_calloc_func, l 150
E (2837) BT: --> p 0x3ffd5b8c, s 24, f fixed_queue_new, l 42
E (2847) BT: --> p 0x3ffd87a8, s 20, f osi_calloc_func, l 150
E (2857) BT: --> p 0x3ffd97e4, s 32, f osi_calloc_func, l 150
E (2857) BT: --> p 0x3ffd9808, s 136, f osi_calloc_func, l 150
E (2867) BT: --> p 0x3ffd98e8, s 32, f osi_calloc_func, l 150
E (2877) BT: --> p 0x3ffd990c, s 136, f osi_calloc_func, l 150
E (2877) BT: --> p 0x3ffd99ec, s 32, f osi_calloc_func, l 150
E (2887) BT: --> p 0x3ffd9a10, s 136, f osi_calloc_func, l 150
E (2887) BT: --> p 0x3ffdb1cc, s 24, f fixed_queue_new, l 42
E (2897) BT: --> p 0x3ffdb23c, s 20, f osi_calloc_func, l 150
E (2907) BT: --> p 0x3ffdb2fc, s 24, f fixed_queue_new, l 42
E (2907) BT: --> p 0x3ffdb36c, s 20, f osi_calloc_func, l 150
E (2917) BT: --> p 0x3ffdb42c, s 20, f osi_calloc_func, l 150
E (2927) BT: --> p 0x3ffdb444, s 24, f fixed_queue_new, l 42
E (2927) BT: --> p 0x3ffdb4b4, s 20, f osi_calloc_func, l 150
E (2937) BT: --> p 0x3ffdb574, s 24, f fixed_queue_new, l 42
E (2947) BT: --> p 0x3ffdb5e4, s 20, f osi_calloc_func, l 150
E (2947) BT: --> p 0x3ffdb6a4, s 24, f fixed_queue_new, l 42
E (2957) BT: --> p 0x3ffdb714, s 20, f osi_calloc_func, l 150
E (2957) BT: --> p 0x3ffdb7d4, s 24, f fixed_queue_new, l 42
E (2967) BT: --> p 0x3ffdb844, s 20, f osi_calloc_func, l 150
E (2977) BT: --> p 0x3ffdb904, s 128, f allocate_svc_db_buf, l 1340
E (2977) BT: --> p 0x3ffd0cf4, s 8, f osi_calloc_func, l 150
E (2987) BT: --> p 0x3ffdb988, s 24, f fixed_queue_new, l 42
E (2997) BT: --> p 0x3ffdb9f8, s 20, f osi_calloc_func, l 150
E (2997) BT: --> p 0x3ffdbab8, s 135, f btm_ble_adv_filter_init, l 1251
E (3007) BT: --> p 0x3ffdbb44, s 24, f fixed_queue_new, l 42
E (3017) BT: --> p 0x3ffdbbb4, s 20, f osi_calloc_func, l 150
E (3017) BT: --> p 0x3ffdbc74, s 128, f allocate_svc_db_buf, l 1340
E (3027) BT: --> p 0x3ffd2abc, s 8, f osi_calloc_func, l 150
E (3037) BT: --> p 0x3ffdbcf8, s 128, f allocate_svc_db_buf, l 1340
E (3037) BT: --> p 0x3ffd5bfc, s 8, f osi_calloc_func, l 150
E (3047) BT: --> p 0x3ffdbdd0, s 32, f osi_calloc_func, l 150
E (3057) BT: --> p 0x3ffdbdf4, s 68, f osi_calloc_func, l 150
E (3057) BT: --> p 0x3ffd5c08, s 4, f config_new_empty, l 62
E (3067) BT: --> p 0x3ffdbe90, s 20, f osi_calloc_func, l 150
E (3077) BT: --> p 0x3ffdcb1c, s 280, f btc_transfer_context, l 123
E (3077) BT: --> p 0x3ffdbef0, s 18, f btm_ble_resolving_list_init, l 951
E (3087) BT: --> p 0x3ffdbf08, s 3, f btm_ble_resolving_list_init, l 952
E (3097) BT: --> p 0x3ffdcecc, s 8, f section_new, l 503
E (3097) BT: --> p 0x3ffdced8, s 8, f osi_strdup, l 121
E (3107) BT: --> p 0x3ffdcee4, s 20, f osi_calloc_func, l 150
E (3117) BT: --> p 0x3ffdcefc, s 8, f osi_calloc_func, l 150
E (3117) BT: --> p 0x3ffdcf08, s 8, f entry_new, l 539
E (3127) BT: --> p 0x3ffdcf14, s 17, f osi_strdup, l 121
E (3127) BT: --> p 0x3ffdcf2c, s 33, f osi_strdup, l 121
E (3137) BT: --> p 0x3ffdcf54, s 8, f osi_calloc_func, l 150
E (3147) BT: --> p 0x3ffdcf60, s 8, f entry_new, l 539
E (3147) BT: --> p 0x3ffdcf6c, s 16, f osi_strdup, l 121
E (3157) BT: --> p 0x3ffdcf80, s 33, f osi_strdup, l 121
E (3157) BT: --> p 0x3ffdcfa8, s 8, f osi_calloc_func, l 150
E (3167) BT: --> p 0x3ffdcfb4, s 8, f entry_new, l 539
E (3177) BT: --> p 0x3ffdcfc0, s 17, f osi_strdup, l 121
E (3177) BT: --> p 0x3ffdcfd8, s 33, f osi_strdup, l 121
E (3187) BT: --> p 0x3ffdd000, s 8, f osi_calloc_func, l 150
E (3187) BT: --> p 0x3ffdd00c, s 8, f entry_new, l 539
E (3197) BT: --> p 0x3ffdd018, s 16, f osi_strdup, l 121
E (3207) BT: --> p 0x3ffdd02c, s 33, f osi_strdup, l 121
E (3207) BT: --> p 0x3ffdd054, s 8, f osi_calloc_func, l 150
E (3217) BT: --> p 0x3ffdce28, s 24, f fixed_queue_new, l 42
E (3227) BT: --> p 0x3ffdbec4, s 4, f btc_to_bta_adv_data, l 265
E (3227) BT: --> p 0x3ffdbf10, s 1, f btm_ble_resolving_list_init, l 956
E (3237) BT: --> p 0x3ffdbf18, s 20, f osi_calloc_func, l 150
E (3247) BT: --> p 0x3ffdbecc, s 8, f btc_to_bta_adv_data, l 281
E (3247) BT: --> p 0x3ffdbed8, s 8, f btc_to_bta_adv_data, l 285
E (3257) BT: --> p 0x3ffdce98, s 20, f osi_calloc_func, l 150
E (3267) BT: --> p 0x3ffdbf30, s 24, f fixed_queue_new, l 42
E (3267) BT: --> p 0x3ffdbf4c, s 20, f osi_calloc_func, l 150
E (3277) BT: --> p 0x3ffdc6ac, s 64, f gatts_add_characteristic, l 514
E (3287) BT: --> p 0x3ffdc02c, s 128, f allocate_svc_db_buf, l 1340
E (3287) BT: --> p 0x3ffdceb0, s 8, f osi_calloc_func, l 150
E (3297) BT: --> p 0x3ffdce10, s 20, f osi_calloc_func, l 150
E (3307) BT: --> p 0x3ffdbea8, s 12, f osi_calloc_func, l 150
E (3307) BT: --> p 0x3ffdbee4, s 8, f osi_calloc_func, l 150
E (3317) BT: --> p 0x3ffdc1ac, s 24, f fixed_queue_new, l 42
E (3317) BT: --> p 0x3ffdce44, s 24, f fixed_queue_new, l 42
E (3327) BT: --> p 0x3ffdc21c, s 20, f osi_calloc_func, l 150
E (3337) BT: --> p 0x3ffdc2dc, s 24, f fixed_queue_new, l 42
E (3337) BT: --> p 0x3ffdbf6c, s 20, f osi_calloc_func, l 150
E (3347) BT: --> p 0x3ffdc34c, s 20, f osi_calloc_func, l 150
E (3357) BT: --> p 0x3ffdc40c, s 24, f fixed_queue_new, l 42
E (3357) BT: --> p 0x3ffdc47c, s 20, f osi_calloc_func, l 150
E (3367) BT: --> p 0x3ffdc798, s 128, f allocate_svc_db_buf, l 1340
E (3377) BT: --> p 0x3ffdc694, s 8, f osi_calloc_func, l 150
E (3377) BT: --> p 0x3ffdc574, s 24, f fixed_queue_new, l 42
E (3387) BT: --> p 0x3ffdc5e4, s 20, f osi_calloc_func, l 150
E (3387) BT: --> p 0x3ffdc5fc, s 24, f fixed_queue_new, l 42
E (3397) BT: --> p 0x3ffdca00, s 280, f btc_transfer_context, l 123
E (3407) BT: --> p 0x3ffdc618, s 20, f osi_calloc_func, l 150
E (3407) BT: --> p 0x3ffdc9c0, s 28, f btc_transfer_context, l 123
E (3417) BT: --> p 0x3ffdc9e0, s 28, f btc_transfer_context, l 123
E (3427) BT: --> count 100

Second connection:

E (13957) BT: --> p 0x3ffdbeb8, s 8, f btc_to_bta_adv_data, l 262
E (13957) BT: --> p 0x3ffd2a88, s 24, f fixed_queue_new, l 42
E (13967) BT: --> p 0x3ffd2aa4, s 20, f osi_calloc_func, l 150
E (13977) BT: --> p 0x3ffd5790, s 24, f fixed_queue_new, l 42
E (13977) BT: --> p 0x3ffd5800, s 20, f osi_calloc_func, l 150
E (13987) BT: --> p 0x3ffd58c0, s 20, f osi_calloc_func, l 150
E (13997) BT: --> p 0x3ffd5abc, s 32, f osi_calloc_func, l 150
E (13997) BT: --> p 0x3ffd5ae0, s 168, f osi_calloc_func, l 150
E (14007) BT: --> p 0x3ffd5b8c, s 24, f fixed_queue_new, l 42
E (14007) BT: --> p 0x3ffd87a8, s 20, f osi_calloc_func, l 150
E (14017) BT: --> p 0x3ffd97e4, s 32, f osi_calloc_func, l 150
E (14027) BT: --> p 0x3ffd9808, s 136, f osi_calloc_func, l 150
E (14027) BT: --> p 0x3ffd98e8, s 32, f osi_calloc_func, l 150
E (14037) BT: --> p 0x3ffd990c, s 136, f osi_calloc_func, l 150
E (14047) BT: --> p 0x3ffd99ec, s 32, f osi_calloc_func, l 150
E (14047) BT: --> p 0x3ffd9a10, s 136, f osi_calloc_func, l 150
E (14057) BT: --> p 0x3ffdb1cc, s 24, f fixed_queue_new, l 42
E (14067) BT: --> p 0x3ffdb23c, s 20, f osi_calloc_func, l 150
E (14067) BT: --> p 0x3ffdb2fc, s 24, f fixed_queue_new, l 42
E (14077) BT: --> p 0x3ffdb36c, s 20, f osi_calloc_func, l 150
E (14087) BT: --> p 0x3ffdb42c, s 20, f osi_calloc_func, l 150
E (14087) BT: --> p 0x3ffdb444, s 24, f fixed_queue_new, l 42
E (14097) BT: --> p 0x3ffdb4b4, s 20, f osi_calloc_func, l 150
E (14107) BT: --> p 0x3ffdb574, s 24, f fixed_queue_new, l 42
E (14107) BT: --> p 0x3ffdb5e4, s 20, f osi_calloc_func, l 150
E (14117) BT: --> p 0x3ffdb6a4, s 24, f fixed_queue_new, l 42
E (14127) BT: --> p 0x3ffdb714, s 20, f osi_calloc_func, l 150
E (14127) BT: --> p 0x3ffdb7d4, s 24, f fixed_queue_new, l 42
E (14137) BT: --> p 0x3ffdb844, s 20, f osi_calloc_func, l 150
E (14137) BT: --> p 0x3ffdb904, s 128, f allocate_svc_db_buf, l 1340
E (14147) BT: --> p 0x3ffd0cf4, s 8, f osi_calloc_func, l 150
E (14157) BT: --> p 0x3ffdb988, s 24, f fixed_queue_new, l 42
E (14157) BT: --> p 0x3ffdb9f8, s 20, f osi_calloc_func, l 150
E (14167) BT: --> p 0x3ffdbab8, s 135, f btm_ble_adv_filter_init, l 1251
E (14177) BT: --> p 0x3ffdbb44, s 24, f fixed_queue_new, l 42
E (14177) BT: --> p 0x3ffdbbb4, s 20, f osi_calloc_func, l 150
E (14187) BT: --> p 0x3ffdbc74, s 128, f allocate_svc_db_buf, l 1340
E (14197) BT: --> p 0x3ffd2abc, s 8, f osi_calloc_func, l 150
E (14197) BT: --> p 0x3ffdbcf8, s 128, f allocate_svc_db_buf, l 1340
E (14207) BT: --> p 0x3ffd5bfc, s 8, f osi_calloc_func, l 150
E (14217) BT: --> p 0x3ffdbdd0, s 32, f osi_calloc_func, l 150
E (14217) BT: --> p 0x3ffdbdf4, s 68, f osi_calloc_func, l 150
E (14227) BT: --> p 0x3ffd5c08, s 4, f config_new_empty, l 62
E (14237) BT: --> p 0x3ffdbe90, s 20, f osi_calloc_func, l 150
E (14237) BT: --> p 0x3ffd2c38, s 280, f btc_transfer_context, l 123
E (14247) BT: --> p 0x3ffdbef0, s 18, f btm_ble_resolving_list_init, l 951
E (14257) BT: --> p 0x3ffdbf08, s 3, f btm_ble_resolving_list_init, l 952
E (14267) BT: --> p 0x3ffdcecc, s 8, f section_new, l 503
E (14267) BT: --> p 0x3ffdced8, s 8, f osi_strdup, l 121
E (14277) BT: --> p 0x3ffdcee4, s 20, f osi_calloc_func, l 150
E (14277) BT: --> p 0x3ffdcefc, s 8, f osi_calloc_func, l 150
E (14287) BT: --> p 0x3ffdcf08, s 8, f entry_new, l 539
E (14297) BT: --> p 0x3ffdcf14, s 17, f osi_strdup, l 121
E (14297) BT: --> p 0x3ffdcf2c, s 33, f osi_strdup, l 121
E (14307) BT: --> p 0x3ffdcf54, s 8, f osi_calloc_func, l 150
E (14317) BT: --> p 0x3ffdcf60, s 8, f entry_new, l 539
E (14317) BT: --> p 0x3ffdcf6c, s 16, f osi_strdup, l 121
E (14327) BT: --> p 0x3ffdcf80, s 33, f osi_strdup, l 121
E (14327) BT: --> p 0x3ffdcfa8, s 8, f osi_calloc_func, l 150
E (14337) BT: --> p 0x3ffdcfb4, s 8, f entry_new, l 539
E (14347) BT: --> p 0x3ffdcfc0, s 17, f osi_strdup, l 121
E (14347) BT: --> p 0x3ffdcfd8, s 33, f osi_strdup, l 121
E (14357) BT: --> p 0x3ffdd000, s 8, f osi_calloc_func, l 150
E (14357) BT: --> p 0x3ffdd00c, s 8, f entry_new, l 539
E (14367) BT: --> p 0x3ffdd018, s 16, f osi_strdup, l 121
E (14377) BT: --> p 0x3ffdd02c, s 33, f osi_strdup, l 121
E (14377) BT: --> p 0x3ffdd054, s 8, f osi_calloc_func, l 150
E (14387) BT: --> p 0x3ffdce28, s 24, f fixed_queue_new, l 42
E (14397) BT: --> p 0x3ffdbec4, s 4, f btc_to_bta_adv_data, l 265
E (14397) BT: --> p 0x3ffdbf10, s 1, f btm_ble_resolving_list_init, l 956
E (14407) BT: --> p 0x3ffdbf18, s 20, f osi_calloc_func, l 150
E (14417) BT: --> p 0x3ffdbecc, s 8, f btc_to_bta_adv_data, l 281
E (14417) BT: --> p 0x3ffdbed8, s 8, f btc_to_bta_adv_data, l 285
E (14427) BT: --> p 0x3ffdce98, s 20, f osi_calloc_func, l 150
E (14437) BT: --> p 0x3ffdbf30, s 24, f fixed_queue_new, l 42
E (14447) BT: --> p 0x3ffdbf4c, s 20, f osi_calloc_func, l 150
E (14447) BT: --> p 0x3ffdc6ac, s 64, f gatts_add_characteristic, l 514
E (14457) BT: --> p 0x3ffdc02c, s 128, f allocate_svc_db_buf, l 1340
E (14457) BT: --> p 0x3ffdceb0, s 8, f osi_calloc_func, l 150
E (14467) BT: --> p 0x3ffdce10, s 20, f osi_calloc_func, l 150
E (14477) BT: --> p 0x3ffdbea8, s 12, f osi_calloc_func, l 150
E (14477) BT: --> p 0x3ffdbee4, s 8, f osi_calloc_func, l 150
E (14487) BT: --> p 0x3ffdc1ac, s 24, f fixed_queue_new, l 42
E (14497) BT: --> p 0x3ffdce44, s 24, f fixed_queue_new, l 42
E (14497) BT: --> p 0x3ffdc21c, s 20, f osi_calloc_func, l 150
E (14507) BT: --> p 0x3ffdc2dc, s 24, f fixed_queue_new, l 42
E (14517) BT: --> p 0x3ffdbf6c, s 20, f osi_calloc_func, l 150
E (14517) BT: --> p 0x3ffdc34c, s 20, f osi_calloc_func, l 150
E (14527) BT: --> p 0x3ffdc40c, s 24, f fixed_queue_new, l 42
E (14527) BT: --> p 0x3ffdc47c, s 20, f osi_calloc_func, l 150
E (14537) BT: --> p 0x3ffdc5e4, s 24, f fixed_queue_new, l 42
E (14547) BT: --> p 0x3ffdc798, s 128, f allocate_svc_db_buf, l 1340
E (14547) BT: --> p 0x3ffdc694, s 8, f osi_calloc_func, l 150
E (14557) BT: --> p 0x3ffdc600, s 20, f osi_calloc_func, l 150
E (14567) BT: --> p 0x3ffdc618, s 24, f fixed_queue_new, l 42
E (14567) BT: --> p 0x3ffdc8c4, s 20, f osi_calloc_func, l 150
E (14577) BT: --> p 0x3ffdc984, s 24, f fixed_queue_new, l 42
E (14587) BT: --> p 0x3ffdc9f4, s 20, f osi_calloc_func, l 150
E (14587) BT: --> p 0x3ffdcaec, s 24, f fixed_queue_new, l 42
E (14597) BT: --> p 0x3ffdcb5c, s 20, f osi_calloc_func, l 150
E (14607) BT: --> p 0x3ffdcc1c, s 24, f fixed_queue_new, l 42
E (14607) BT: --> p 0x3ffd2b1c, s 280, f btc_transfer_context, l 123
E (14617) BT: --> p 0x3ffdcc8c, s 20, f osi_calloc_func, l 150
E (14627) BT: --> p 0x3ffdcd4c, s 28, f btc_transfer_context, l 123
E (14627) BT: --> p 0x3ffdcd6c, s 28, f btc_transfer_context, l 123
E (14637) BT: --> count 106

I'm still looking for the problem...

King regards,
   German Aracil Boned

**Comment by projectgus** [comment]
There is also a new leak tracing feature in IDF which should help narrow down the place where this leak is occuring:
https://esp-idf.readthedocs.io/en/latest/api-reference/system/heap_debug.html#how-to-diagnose-memory-leaks

**Comment by TianHao-Espressif** [comment]
@garacil , what's the procedure of your test? Do BLE connect to GATT-SERVER or BLE connected from  GATT_CLIENT?

**Comment by jaracil** [comment]
Esp32 is GATT_SERVER.

**Comment by blueMoods** [comment]
@jaracil @garacil The memory leak has been fixed, please use the latest esp_idf. Thanks.
