### ISSUE TITLE
Cannot find "xtensa-esp32-elf-gcc" VS on Windows  (IDFGH-8596)

### ISSUE THREAD

**Issue by ANQUN12** [espressif/esp-idf#10043]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF 4.4

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

**I have a problem with any code that uses xtensa-esp32-gcc**
![VS](https://user-images.githubusercontent.com/46296045/197594281-502b3e5a-bfa4-4909-941c-5a9c88c75563.PNG)

### What is the actual behavior?

**I added IDF_PATH, xtensa-esp32-elf
However it gives the same error**

![VER](https://user-images.githubusercontent.com/46296045/197595426-c489bd3b-2d16-4837-a585-4441903f85bc.PNG)
![IDF](https://user-images.githubusercontent.com/46296045/197595757-4b794475-fcad-4657-82a3-01bc189c1a5f.PNG)

### Steps to reproduce.

1. idf.py set-target esp32       // **ok**
2. idf.py menuconfig       // **ok**
3. idf.py build     // **error**
...

**Comment by Hairy-Lee** [comment]
What was the resolution to this issue? I have 4.4.3 installed and I'm experiencing the same issue

**Comment by brianignacio5** [comment]
You need to specify the full compiler path (C:\esp\Espressif\tools\xtensa-esp32-elf\...\bin\xtensa-esp32-elf-gcc) instead of just the binary name. If you are using the ESP-IDF extension for Visual Studio Code, use the `ESP-IDF: Set Espressif device target` so the extension will update this compiler path automatically. 

Based on what you shared, seems you are running `idf.py` which doesn't update this c_cpp_properties.json file and you need to update it manually. I also don't t see the `xtensa-esp32-elf`

**Comment by pixelprizm** [comment]
I had a similar issue (I'm using Rust but sharing in case it's helpful), and it was fixed when I installed MinGW using the instructions here: https://github.com/esp-rs/rust-build#prerequisites-x86_64-gnu.  Note that the `7z e` command should be `7z x` to maintain directory structure.  (Just the MinGW step -- for everything else I just used `cargo install espup`, and `espup install`.)
