### ISSUE TITLE
ESP_IDF Set hostname not working (IDFGH-8770)

### ISSUE THREAD

**Issue by robocircuits** [espressif/esp-idf#10202]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using esp-IDF and esp-wroom-32 chip. I created a captive portal for esp to set various parameters of esp. currently I access it through the IP address of esp
![Screenshot from 2022-11-18 19-59-33](https://user-images.githubusercontent.com/42605572/202731357-913564f5-93da-4d0c-9742-b813fd89a914.png)

I want to access it using the hostname as same as the home assistant uses like this
![Screenshot from 2022-11-18 20-06-17](https://user-images.githubusercontent.com/42605572/202731522-a1f18680-d221-41d6-ac02-a034f7840d76.png)

I used this code to add a hostname to esp 

![Screenshot from 2022-11-18 20-01-45](https://user-images.githubusercontent.com/42605572/202731629-62acd909-d6e2-4405-bb11-6c7179b9aeed.png)

And logs show hostname is set

![Screenshot from 2022-11-18 20-03-11](https://user-images.githubusercontent.com/42605572/202731677-b7a4c70a-6a5b-449e-aeb6-4519a2983bb5.png)

but when I enter prashant.local in browser I see nothing. 

Kindly help me if I am doing anything wrong.

**Comment by chipweinberger** [comment]
The adapter hostname is a different lower level protocol for naming devices on your network. Look at your router device page.

For http, you need to use MDNS.

**Comment by gabsuren** [comment]
@robocircuits thank you for the question. As mentioned @chipweinberger `tcpip_adapter_set_hostname` sets the hostname of an interface. 
In order to set local network hostname you need to use `mDNS` component with the following API `mdns_hostname_set`
You can find the example below (if you use `ESP-IDF version < 5.0`)
[mDNS example](https://github.com/espressif/esp-idf/blob/release/v4.1/examples/protocols/mdns/main/mdns_example_main.c)

If you use `ESP-IDF version >= 5.0` (mDNS component migrated to [esp-protocols](https://github.com/espressif/esp-protocols/))

[mDNS example](https://github.com/espressif/esp-protocols/blob/master/components/mdns/examples/main/mdns_example_main.c)

Please let us know if it helped you or don't hesitate to ask a questions.

Regards,
Suren

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
