### ISSUE TITLE
regarding bluetooth data sending  (IDFGH-8789)

### ISSUE THREAD

**Issue by beginner140BB** [espressif/esp-idf#10221]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Here i am having an issue of  bluetooth data sending, where i am sending the data only based on  the bluetooth exists using flag. where the flag is set to high on the event where there connection establishes.

i am settting the flag to high on the events
ESP_SPP_OPEN_EVT
ESP_SPP_SRV_OPEN_EVT
the initiator(or master or client) should check whether there exists a connection and if exists then send data based on the flag.
but its is entering into sniff mode

the below shown is the log
where master tries to send data based on flag

![image](https://user-images.githubusercontent.com/83206454/203289351-504f47ef-30ec-40b9-964a-1c1cb287ba86.png)

`while(bBTisConnected)
	{
	vTaskDelay(500);
	if(iSend_data_to_bluetooth("HEYSLAVE"))
	{
		printf("okay");
	}
	else
	{
		printf("not okay");
	}
	}`
	
	where bBTisConnected is high during ESP_SPP_OPEN_EVT on master side.
	
	
	
	anyone knows what may be the possible issue

**Comment by beginner140BB** [comment]
> @beginner140BB Do you not understand why it enters sniff mode? Or, do you not want it to go into sniff mode at all?

dont want to go to sniff mode as
esp_spp_write() function will not work.

**Comment by BetterJincheng** [comment]
@beginner140BB `vTaskDelay(500);` can be 5 seconds with 10ms-tick. When there is no data to be sent for a period time, it enters sniff mode to save power. If you take no care of power, you can disable sniff mode.
Currently, there is no such an API, we will add this API immediately.

**Comment by beginner140BB** [comment]
> @beginner140BB `vTaskDelay(500);` can be 5 seconds with 10ms-tick. When there is no data to be sent for a period time, it enters sniff mode to save power. If you take no care of power, you can disable sniff mode. Currently, there is no such an API, we will add this API immediately.

actually i am sending a default string using esp_spp_write()

`int iSend_data_to_bluetooth(char *send_bt_data)
{
	esp_spp_write( handle,strlen(send_bt_data), (uint8_t *)send_bt_data);
	return 1;
}`

**Comment by BetterJincheng** [comment]
@espressif-bot For a test, you can change `#define BTA_DM_LINK_POLICY_SETTINGS    (HCI_ENABLE_MASTER_SLAVE_SWITCH | HCI_ENABLE_HOLD_MODE | HCI_ENABLE_SNIFF_MODE | HCI_ENABLE_PARK_MODE)` to `#define BTA_DM_LINK_POLICY_SETTINGS    (HCI_ENABLE_MASTER_SLAVE_SWITCH | HCI_ENABLE_HOLD_MODE | HCI_ENABLE_PARK_MODE)`. And see if it works.

**Comment by beginner140BB** [comment]
> 

reply from espressif


For the problem you are facing, please follow these steps to test:

1. Please download the “libbtdm_app.a”file in the attached and replace the “esp-idf/components/bt/controller/lib_esp32/esp32/libbtdm_app.a” file under the esp-idf SDK that you used.

2. Delete the “build” file generated by your project and recompile it.

3. Please redownload the new compiled firmware for testing.


when we face issue in the case of slave device which accepts the connection
here issue is regarding master device when initiates the connection.

here we are able to initiate the connection but when we are sending data based on flag which enabled true during 
ESP_SPP_OPEN_EVT which comes when client connection opens i.e there is bluetooth connection based on the flag we are sending the data the flag is turning high but bluetooth is turning to sniff mode thereby not able to send data.

**Comment by beginner140BB** [comment]
> @beginner140BB For a test, you can change `#define BTA_DM_LINK_POLICY_SETTINGS (HCI_ENABLE_MASTER_SLAVE_SWITCH | HCI_ENABLE_HOLD_MODE | HCI_ENABLE_SNIFF_MODE | HCI_ENABLE_PARK_MODE)` to `#define BTA_DM_LINK_POLICY_SETTINGS (HCI_ENABLE_MASTER_SLAVE_SWITCH | HCI_ENABLE_HOLD_MODE | HCI_ENABLE_PARK_MODE)`.
> 
> And see if it works.

it works its not entering to sniff mode
![image](https://user-images.githubusercontent.com/83206454/203475861-9e2dd79b-41ad-4f03-b6c0-c95ea9d730a7.png)

**Comment by BetterJincheng** [comment]
@beginner140BB We will add an API to disable sniff mode.

**Comment by beginner140BB** [comment]
> @beginner140BB We will add an API to disable sniff mode.

just curious will disabling sniff mode consumes more power.
and another question is that whether there is any other way to get to know the bluetooth connection exists other than using 
event information.



when i put while(1) its okay
but using flag read from event parameters its not okay

using simple while (1 )
4157) SPP_INITIATOR_DEMO: ESP_SPP_OPEN_EVT handle:129 rem_bda:[da:7a:fb:3f:00:00][0m
okay[0;32mI (4167) SPP_INITIATOR_DEMO: ESP_SPP_WRITE_EVT[0m

but when sending based on flag that set to high on open event the code is not executing the while loop

while(bBTisConnected)
`

     break;
    case ESP_SPP_OPEN_EVT:
        if (param->open.status == ESP_SPP_SUCCESS) {
        	bBTisConnected=1;
        	ESP_LOGI(SPP_TAG, "BT_connected:%d",bBTisConnected);

            ESP_LOGI(SPP_TAG, "ESP_SPP_OPEN_EVT handle:%d rem_bda:[%s]", param->srv_open.handle,
                     bda2str(param->srv_open.rem_bda, bda_str, sizeof(bda_str)));
            handle=param->srv_open.handle;
            /* Start to write the first data packet */
           // esp_spp_write(param->open.handle, SPP_DATA_LEN, spp_data);
           // send_bt_data("test",4);
           // s_p_data = spp_data;
            gettimeofday(&time_old, NULL);
        } else {
            ESP_LOGE(SPP_TAG, "ESP_SPP_OPEN_EVT status:%d", param->open.status);
        }
        break;
	

`

**Comment by BetterJincheng** [comment]
@beginner140BB As I said before, if there is no data to be sent for a while, the link will go in sniff mode to save power. When `bBTisConnected` is set to high, it indicates the spp is open. Even though spp is open, it will still enter sniff mode when there is no data to send.
But in theory, even in sniff mode, calling `esp_spp_write()` can still exit sniff mode and send data successfully.
You can attach your complete code and I can check it for you.

**Comment by beginner140BB** [comment]
[main.zip](https://github.com/espressif/esp-idf/files/10073292/main.zip)
this is the main code of initiator
could you please check this

**Comment by BetterJincheng** [comment]
@beginner140BB In your `main.c`, `while (flag)` can be missed if flag is false and never come back...

**Comment by beginner140BB** [comment]
> @beginner140BB In your `main.c`, `while (flag)` can be missed if flag is false and never come back...

oh no sorry
thanks for point out the simple issue.

**Comment by BetterJincheng** [comment]
@beginner140BB Do you still use the SPP example?
You can use
`esp_bt_gap_set_scan_mode(ESP_BT_NON_CONNECTABLE, ESP_BT_NON_DISCOVERABLE);`
to set the slave to non-connectable whenever you want.

**Comment by beginner140BB** [comment]
> @beginner140BB Do you still use the SPP example? You can use `esp_bt_gap_set_scan_mode(ESP_BT_NON_CONNECTABLE, ESP_BT_NON_DISCOVERABLE);` to set the slave to non-connectable whenever you want.

okay thanks for the support😊

**Comment by ramesh12322** [comment]
Hello Sir,

I am facing a critical issue on ESP32-WROOM-32E with Classic Bluetooth (SPP).

My application requires continuous data transmission over Bluetooth without interruption. However, when I send data continuously, the ESP32 stalls for about 400–500 ms every 5–6 seconds.

After debugging Bluetooth logs, I identified that this pause occurs because Bluetooth enters Sniff (power-saving) mode, and during the transition back to Active (Unsniff) mode, data transmission is temporarily blocked.

I clearly understand the root cause:

Bluetooth automatically switches to Sniff Mode

On exiting Sniff mode (Unsniff), there is a ~500 ms delay

This delay is unacceptable for my application

I have already tried:

Disabling power-saving options in menuconfig

Forcing continuous data transmission

Using available Bluetooth APIs related to power management

Adjusting connection intervals and application-level delays

Unfortunately, none of these methods permanently disable Sniff mode, and the issue still persists.

Could you please guide me on:

How to completely disable Sniff mode for Classic Bluetooth (SPP)?

Is there any supported or internal API to force Active mode permanently?

If this behavior is unavoidable, what is the recommended workaround for real-time continuous data streaming?

Any guidance or confirmation would be greatly appreciated, as this issue is blocking my application.

**Comment by BetterJincheng** [comment]
@ramesh12322  I’ve added a GAP API on **master** to disable sniff mode on a specific link. I can provide you with the current patch so you can test it in advance.

[0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch](https://github.com/user-attachments/files/24303130/0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch)

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) I’ve added a GAP API on **master** to disable sniff mode on a specific link. I can provide you with the current patch so you can test it in advance.
> 
> [0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch](https://github.com/user-attachments/files/24303130/0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch)

Sure sir, I will test it and give you feedback.

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) I’ve added a GAP API on **master** to disable sniff mode on a specific link. I can provide you with the current patch so you can test it in advance.
> 
> [0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch](https://github.com/user-attachments/files/24303130/0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch)

I am using ESP-IDF v5.3.1 and trying to use the patch
0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch which adds an API to control Bluetooth sniff mode.

I tried applying the patch using git apply, but it fails with multiple hunk rejects because the patch does not match the current ESP-IDF v5.3.1 source tree.

I would like to use this API without doing manual source code modifications, as manual changes are difficult to maintain across ESP-IDF updates.Can you suggest how to use it...

**Comment by BetterJincheng** [comment]
@ramesh12322 This API will be released as a new feature on the latest **master** branch, and we are unlikely to backport it to existing older release branches. However, to facilitate your testing, I can generate a usable patch for **v5.3.1** and provide it to you shortly.

**Comment by BetterJincheng** [comment]
[0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch](https://github.com/user-attachments/files/24306447/0001-feat-bt-added-an-API-to-control-sniff-mode-for-a-spe.patch)

@ramesh12322  You can now apply this patch directly to **v5.3.1**. After the connection is established, you can call the following API:
```c
esp_bt_link_policy_t policy = {
    .no_sniff = true,
 };
 esp_bt_gap_set_link_policy(Remote_bda, &policy);
```

**Comment by BetterJincheng** [comment]
@ramesh12322 Does it work ?

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) Does it work ?

@BetterJincheng After adding the API to the ESP-IDF source, I’m encountering build errors related to stdio.h. I suspect this may be due to a toolchain or environment configuration issue rather than the patch itself.I will reinstall ESP-IDF to ensure a clean environment and then test the new patch API. I’ll update my results after testing.

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) Does it work ?

Finally the sniff mode disable successfully .I am using ESP32 as a Bluetooth Classic SPP to UART bridge. After successfully disabling Bluetooth sniff mode, the connection is now stable. However, I am facing another issue related to UART data handling.

When I send the # command from an Android Serial Bluetooth Terminal app, the ESP32 correctly forwards this command to another controller (Nuvoton MCU) via UART. After receiving this # command, the Nuvoton controller starts sending continuous data frames back to the ESP32 over UART. The problem is that at the beginning of this transmission, the ESP32 receives some garbage or corrupted frames and appears to be briefly stuck for a few milliseconds. After a short delay, the UART data becomes stable and correct.

This issue occurs consistently only at the start of the continuous UART transmission, immediately after sending the # command. I am already using UART DMA buffers and FreeRTOS tasks with delays to yield CPU time. I would like to understand how to properly flush, synchronize, or stabilize the UART data stream so that the initial garbage frames can be avoided.

Additionally, I would like to mention that the same code works perfectly on the ESP32-WROOM-32 module, but the issue occurs on the ESP32-WROOM-32E module. This makes me suspect possible differences in hardware, UART timing, clocking, or Bluetooth coexistence behavior between the two modules.

Any guidance on handling UART startup synchronization, buffer flushing, or ESP32-WROOM-32E–specific considerations would be very helpful.

**Comment by BetterJincheng** [comment]
@ramesh12322 For UART-related issues, we recommend that you open a new issue so it can be handled by the appropriate persons.

**Comment by ramesh12322** [comment]
[main.zip](https://github.com/user-attachments/files/24390572/main.zip)

Sir, I kindly request you to please go through my code. If you find any issues or mistakes, please let me know.

**Comment by BetterJincheng** [comment]
@ramesh12322 I’ll try to review your code later today.

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) I’ll try to review your code later today.

@BetterJincheng okay

**Comment by BetterJincheng** [comment]
@ramesh12322 In addition, the sniff-disable code I previously shared with you is only the first internal development version and may change later. Once it is officially released, I’ll notify you here so you can optionally update your code.

**Comment by ramesh12322** [comment]
> [@ramesh12322](https://github.com/ramesh12322) In addition, the sniff-disable code I previously shared with you is only the first internal development version and may change later. Once it is officially released, I’ll notify you here so you can optionally update your code.

@BetterJincheng okay sir

**Comment by BetterJincheng** [comment]
@ramesh12322 I’ve reviewed your code, but since I’m not an expert in UART peripherals, I’m unable to provide any useful suggestions. Please reopen a UART-related issue to get professional guidance as quickly as possible.
