### ISSUE TITLE
Problem with MODBUS RTU (IDFGH-8804)

### ISSUE THREAD

**Issue by Kunal2019** [espressif/esp-idf#10235]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

IDF version used: **v4.4.3**

Operating System used: **Windows**

IDE used: **VS Code IDE**

Development Kit: **ESP-32 WROOM 32D Devkit**

When I tried using the inbuilt example of the MODBUS (i.e. mb_master) by making some changes as per my needs, I observed that I am unable to print the data in the desired format, but I am getting the correct data in the hexadecimal format. 

I tried mulitple ways of solving it, but failed. 

I am also attaching the screenshot for the reference. 

![MODBUS_issue](https://user-images.githubusercontent.com/47253641/203605575-98ce1d3d-b50d-494e-b083-f6537887efbc.png)

**Comment by alisitsyn** [comment]
Hello @Kunal2019 ,

The value is displayed incorrectly because the official example uses the float format for Humidity and Temperature  values.
https://github.com/espressif/esp-idf/tree/master/examples/protocols/modbus/serial/mb_master#example-parameters-definition
If you configure the ModbusPoll as below you will be able to see the correct float values.
![image](https://user-images.githubusercontent.com/37483886/203736970-44bc970c-837b-4143-b286-cd2d152d0e29.png)
Refer the documentation to understand how to configure the data dictionary (PARAM_TYPE_U16 parameter in your case):
https://docs.espressif.com/projects/esp-modbus/en/latest/esp32/master_api_overview.html#configuring-master-data-access

**Comment by Alvin1Zhang** [comment]
@Kunal2019 Thanks for reporting, would you please help share if any further updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
