### ISSUE TITLE
"hello_world" `printf` formats do not match input (IDFGH-8882)

### ISSUE THREAD

**Issue by gregjesl** [espressif/esp-idf#10303]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-2066-g7869f4e151

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

"hello_world" example compiles without warnings or errors, even when the `-Werror` compile flag is set

### What is the actual behavior?

Compile fails with two errors (see build logs)

### Steps to reproduce.

Compile "hello_world" with `-Werror` compile flag set

### Build or installation Logs.

```plain
error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'long unsigned int' [-Werror=format=]
   44 |     printf("%uMB %s flash\n", flash_size / (1024 * 1024),
      |             ~^                ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              |                           |
      |              unsigned int                long unsigned int
      |             %lu

error: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
   47 |     printf("Minimum free heap size: %d bytes\n", esp_get_minimum_free_heap_size());
      |                                     ~^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |                                         |
      |                                      int                                       uint32_t {aka long unsigned int}
      |                                     %ld
```

### More Information.

 I plan on submitting a pull request to resolve the behavior

**Comment by chipweinberger** [comment]
"Format string warnings (-Wformat) are now enabled for Xtensa and RISC-V targets. This will result in warnings whenever uint32_t values are formatted using %u or %d format specifiers. The reason is that int32_t type is defined as long which was int in a past. The same is for uint32_t. To fix the warnings, do either one of the following: 1) Use PRIx32 specifier from inttypes.h instead of d or u. 2) Cast the values being formatted to unsigned int. 3) (Not recommended) add -Wno-format compiler flag to the files where this warning occurs using set_source_files_properties CMake function."

From the v5.0 release notes.
