### ISSUE TITLE
SPI DMA & Async memcpy (IDFGH-9182)

### ISSUE THREAD

**Issue by enhany** [espressif/esp-idf#10575]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Slave SPI DMA and async memcpy doesn't work together.

Device: ESP32-C3 (any devboard or chip)

How to reproduce:
1. compile "spi_slave/receiver" example
2. check it works fine
3. add "esp_async_memcpy_install" code anywhere (before or after spi initialize) (see below) 
4. compile and see SPI doesn't work (send garbage to master)

Initialize async memcpy code:

```
async_memcpy_config_t config = ASYNC_MEMCPY_DEFAULT_CONFIG();
async_memcpy_t driver = NULL;
ESP_ERROR_CHECK(esp_async_memcpy_install(&config, &driver));
```

**Comment by suda-morris** [comment]
@enhany  Thanks for reporting the issue. This seems like a hardware limitation that we can't workaround very well at the moment. The issue is that, the memory copy engine will occupy one of the DMA trigger ID that used by the peripheral. And by default, we set the trigger ID to [zero]() for memory copy, however this ID is also used by [SPI2](https://github.com/espressif/esp-idf/blob/master/https://github.com/espressif/esp-idf/blob/master/components/hal/esp32c3/include/hal/gdma_ll.h#L46components/soc/esp32c3/include/soc/gdma_channel.h#L11).

For now, you can just change [them](https://github.com/espressif/esp-idf/blob/master/components/hal/esp32c3/include/hal/gdma_ll.h#L46-L47) to `2`, your SPI2 should work again.

In the future, we should make that user ID selectable from the menuconfig. But we can't change the situation that the memcpy takes another perpheral's DMA.
