### ISSUE TITLE
IDF 5.0 Docker image doesn't contain `led_strip` common component or blink example (IDFGH-9258)

### ISSUE THREAD

**Issue by parksj10** [espressif/esp-idf#10642]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I generated the blink example program from the ESP-IDF VSCode plugin and it doesn't seem to be supported by `common_components` libraries provided in this docker image: [link](https://hub.docker.com/layers/espressif/idf/release-v5.0/images/sha256-3a595f15ab1a634ffe67876c690dbd70cfdc9179d4803cd8ca8ad413f13a3170?context=explore)

**Comment by suda-morris** [comment]
The `led_strip` component was uploaded to the [Espressif Component Registry](https://components.espressif.com/components/espressif/led_strip) since 5.0. Check [this](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html) out for how to use the component manager in your project.

FYI, the official blink example is also using this way: https://github.com/espressif/esp-idf/blob/master/examples/get-started/blink/main/idf_component.yml#L2
