### ISSUE TITLE
CAN bus peripheral drivers not present in esp-idf (IDFGH-9335)

### ISSUE THREAD

**Issue by skanky-dev** [espressif/esp-idf#10713]
The espressif api-reference shows how to use the can bus peripheral here:
https://docs.espressif.com/projects/esp ... s/can.html](https://docs.espressif.com/projects/esp-idf/en/v3.3.5/api-reference/peripherals/can.html

However the "driver/can.c" and "driver/can.h"are not present in the esp-idf master branch.
How do I use the can bus with the current esp-idf (I'm using the ESP32C3 and ESP32S3 ?)

**Comment by igrr** [comment]
These peripheral and the driver have been [renamed](https://github.com/espressif/esp-idf/issues/5580) to TWAI in the chip documentation and the code, so the API reference (for the `master` branch) is now at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html. The examples are in https://github.com/espressif/esp-idf/tree/master/examples/peripherals/twai.

**Comment by skanky-dev** [comment]
Thank you.
When you search ESP32 can bus this page is the top espressif result - I think it needs a note adding to the top starting this?: https://docs.espressif.com/projects/esp-idf/en/release-v3.3/api-reference/peripherals/can.html

**Comment by igrr** [comment]
We have a redirect set up from can.html to twai.html, so for any recent version a URL like https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/api-reference/peripherals/can.html will get automatically redirected to https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/api-reference/peripherals/twai.html.
Since release/v3.3 branch is EoL since last year, the corresponding docs will probably not get updated anymore.

Let me see if we can do anything to bring the docs for the latest releases higher in the search rankings for this query.
