### ISSUE TITLE
md5 function not found (IDFGH-9895)

### ISSUE THREAD

**Issue by LHYYSY** [espressif/esp-idf#11211]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![image](https://user-images.githubusercontent.com/112528246/232402812-9cb0edc7-2b3c-433b-a0ce-420917d8dbca.png)
![image](https://user-images.githubusercontent.com/112528246/232402944-2219b76a-4ab9-42f9-971a-27b65a174ff3.png)
![image](https://user-images.githubusercontent.com/112528246/232403021-a6d24be7-ecc9-4f21-8ef6-db4acad91a4e.png)

**Comment by ESP-Marius** [comment]
In IDF 5.0 we've updated mbtedtls to v3.1.0 which does not have these `_ret` crypto functions, see [description](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/protocols.html#deprecated-functions-were-removed-from-cryptography-modules).

You should use `mbedtls_md5` instead of `mbedtls_md5_ret`

**Comment by LHYYSY** [comment]
Many thanks

**Comment by ESP-Marius** [comment]
Marking this one as resolved then.
