### ISSUE TITLE
ESP32C3 SAVE 1kbyte data in internal Flash (IDFGH-10151)

### ISSUE THREAD

**Issue by Cuongha1995** [espressif/esp-idf#11422]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Currently, I want to store 1kbyte data (user data) in internal Flash, but after reading the documentation and examples, it seems impossible to store one bank (1kbyte) together. Please let me know if there is a way to do this.

**Comment by igrr** [comment]
Hi @Cuongha1995, this example shows how to  read and write data using esp_partititon API: https://github.com/espressif/esp-idf/blob/master/examples/storage/partition_api/partition_ops/main/main.c. It doesn't store exactly 1kB of data, but the code would like pretty much the same. You just need to allocate the data arrays on the heap rather than the stack, and make them 1kB in size. Then call esp_partition_erase_range and esp_partition_write to write the data. For more information about these APIs, please refer to [this page](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/partition.html).

**Comment by adokitkat** [comment]
Hi @Cuongha1995, have you been able to solve your issue?

**Comment by Cuongha1995** [comment]
Hi @igrr , Thank you for your response.
Sorry for the late reply.
We looked for ways to do this. I seem to agree with you.
Thank you so much.

**Comment by Cuongha1995** [comment]
Hi @adokitkat , 
I was able to solve this problem.
Thanks you!
