### ISSUE TITLE
led strip implementation led_strip_rmt_ws2812.c uses deprecated rmt.h API (IDFGH-10319)

### ISSUE THREAD

**Issue by QuentinFarizon** [espressif/esp-idf#11579]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Use new rmt_tx.h adn rmt_rx.h APIs

### What is the actual behavior?

I get build warning : "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by igrr** [comment]
> Steps to reproduce.
> Step
> Step
> Step

Hi @QuentinFarizon, please provide the steps to reproduce the issue (which application you are trying to build, and how)

**Comment by suda-morris** [comment]
hi @QuentinFarizon As you see, since idf 5.x, we're having another RMT driver. (check this [migration guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/peripherals.html#rmt-driver).

The original example (I mean the example you copied from v4.x) has been upgraded to using the new driver APIs. See https://github.com/espressif/esp-idf/tree/master/examples/peripherals/rmt/led_strip

Also we have made a general interface for led_strip component. It was uploaded to the Espressif Component Registry: https://components.espressif.com/components/espressif/led_strip

We recommend the user use that new component. It should contain all the functionality that exists in the previous example. You can get started with that component by running `idf.py create-project-from-example "espressif/led_strip^2.3.2:led_strip_rmt_ws2812"`
