### ISSUE TITLE
requirements.txt (IDFGH-10512)

### ISSUE THREAD

**Issue by JackCameo** [espressif/esp-idf#11756]
### Is your feature request related to a problem?

esp-idf-v5.1-rc2 missing requirements.txt

### Describe the solution you'd like.

can anyone please share or upload one.

**Comment by dobairoland** [comment]
Requirements.txt file is not used since v5.0.

We have several similar files at https://github.com/espressif/esp-idf/tree/release/v5.1/tools/requirements for each "feature" we support.

Additionally, the versions are specified by the constraint file: https://dl.espressif.com/dl/esp-idf/espidf.constraints.v5.1.txt

You can read about this at: https://docs.espressif.com/projects/esp-idf/en/release-v5.1/esp32/api-guides/tools/idf-tools.html#idf-tools-py-script

But we strongly recommend to use the install and export scripts which handle all these under the hood.
