### ISSUE TITLE
Does the ESP32-C6 support PDM RX or not? (IDFGH-10931)

### ISSUE THREAD

**Issue by thedevleon** [espressif/esp-idf#12125]
I'm trying to hookup a microphone to an ESP32-C6. However, I'm getting mixed information whether or not a PDM microphone is supported or not.

Here it is said to exist (PDM RX):
- Section 29.10.1 of the [Techincal Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-c6_technical_reference_manual_en.pdf#subsection.29.10) says [quote]ESP32-C6 I2S supports both TDM RX mode and PDM RX mode.[/quote]
- The [issue](https://github.com/espressif/esp-idf/issues/10423) for the ESP32-C6 support status also lists PDM RX.

This makes me think it is NOT supported:
- The [table for the modes of the I2S peripheral](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/api-reference/peripherals/i2s.html#overview-of-all-modes) says none for PDM RX for the ESP32C6
- The [soc_caps config file for the esp32c6](https://github.com/espressif/esp-idf/blob/master/components/soc/esp32c6/include/soc/Kconfig.soc_caps.in#L554) on master doesn't contain SOC_I2S_SUPPORTS_PDM_RX

So, does this mean that software support is not ready for PDM RX, or does the actual hardware of the C6 not contain support for PDM RX?

Thanks

**Comment by L-KAYA** [comment]
@thedevleon Thanks for your reporting! These `PDM RX` actually not in same meaning.

You can refer to the terminology in section 29.2 of [Techincal Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-c6_technical_reference_manual_en.pdf#subsection.29.2), in which mentions the **Normal** PDM RX mode. The normal mode means the data you read is actually the raw data on line that sampled by the PDM clock. But as you know, PDM encode the data by pulse density, that means you can hardly decode the raw data in software. So the **Normal** PDM TX/RX modes are not supported in the I2S driver.

In the I2S driver, if PDM RX is supported, that means the target supports PDM-to-PCM RX mode, which can decode the PDM raw data into PCM format in hardware. So that the data format that read from I2S driver is always consistent and useful. As ESP32-C6 doesn't have PDM-to-PCM RX mode, so PDM RX is not supported in I2S driver.

**Comment by L-KAYA** [comment]
Update:

Raw PDM data format has been supported in the commit [9b779d8b](https://github.com/espressif/esp-idf/commit/9b779d8b3c1c7d7aff73ebe5ef36d03ae3d60141)

**Comment by yuzhench** [comment]
Does this mean c6 supports getting raw PDM data but there is no PDM-PCM library to convert this PDM data to PCM automatically? In this case, how can I get PCM data? Is there any recommendation for a conversion library?

**Comment by Steliyan1** [comment]
Hello,
 Does this mean that the only way in **ESP32-C6**, to read **PDM** signal is in **RAW** formal using the legacy **I2S** from commit :
https://github.com/espressif/esp-idf/commit/9b779d8b3c1c7d7aff73ebe5ef36d03ae3d60141 ???

Are there other alternatives reading ****PDM RX** Microphone**  with **ESP32-C6**??

Thanks in advance!

**Comment by L-KAYA** [comment]
@yuzhench @Steliyan1 
Yes, the  raw PDM data is coded by pulse density. Since there is no PDM2PCM converter in the hardware, we need to realize a PDM2PCM converter in the software to get the data in PCM format. 

Normally, this converter is a FIR filter. But currently this FIR filter has not been implemented yet.

As for how to initialize a raw PDM rx channel, you can refer to the [PDM example](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2s/i2s_basic/i2s_pdm/main/i2s_pdm_rx.c#L61)
