### ISSUE TITLE
esp_http_client_read downloading speed (IDFGH-10953)

### ISSUE THREAD

**Issue by gl-chenxiaosheng** [espressif/esp-idf#12145]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I used `esp_http_client_read ` to pull firmware from the server and then upgraded it. I found that if the server is in a local environment, the download speed is fast, but if it is a remote server, the download speed is only 7-8kb. What is the reason for this ?

**Comment by hmalpani** [comment]
Hello @gl-chenxiaosheng 

I am hosting my firmware on GitHub. When I tried updating to that firmware, I got overall OTA speed ~25kbps. I am not sure but it might be because of poor network connectivity or some server issues. You can try improving the network performance using https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/speed.html#improving-network-speed

**Comment by kriegste** [comment]
Even with the network speed tweaks, OTA via download from the internet is slow for me, too. My laptop achieves much higher speeds downloading the exact same file.

However, OTA via local upload (HTTP server running on the ESP32) is fast. So I can rule out the flash writing as the bottleneck here.

I don't know why there is such a big difference. It could be caused by the SSL decryption.

**Comment by kriegste** [comment]
SSL decryption speed should be depending on CPU frequency, right? I compared OTA times at 160 and 240 MHz. There is no difference. I get about 40 kB/s.

**Comment by gl-chenxiaosheng** [comment]
> 

So what is the maximum transmission rate of OTA after your optimization？

**Comment by gl-chenxiaosheng** [comment]
The current speed is about 30kb, this speed is still too low for us.

**Comment by hmalpani** [comment]
> So what is the maximum transmission rate of OTA after your optimization？

I updated the esp_http_client example to calculate the throughput. I started a server and set the client to download a 1 GB file. After setting up the config options for optimization, I got download speed of ~950KBps. Note that this speed is the download speed by es_http_client and not the OTA speed.

**Comment by gl-chenxiaosheng** [comment]
Thank you for your reply. The optimization has indeed improved, but the disadvantage is that it will increase internal RAM consumption. At present, after debugging, the internal ram consumption is acceptable, and the download speed is about 200kb.
