### ISSUE TITLE
[TW#16361] gettimeofday in ISR broken after SNTP

### ISSUE THREAD

**Issue by ctag-fh-kiel** [espressif/esp-idf#1227]
gettimeofday in ISR seems to not return reasonable values any more after time is set with SNTP
outside of ISR it still works

example GPIO ISR:
static void IRAM_ATTR gpio_isr_handler_encoder1_btn1(void* arg)
{
    gpio_ev_ts_t ev;
    uint32_t ev.event = gpio_get_level(GPIO_INPUT_IO_ENCODER1_BTN);
    gettimeofday(&ev.timestamp, NULL); // issue here, no valid result after SNTP
    xQueueSendFromISR(gpio_event_queue_ui, &ev, NULL);
}

**Comment by igrr** [comment]
Hi @ctag-fh-kiel, unfortunately `gettimeofday` is not safe to be used in ISR, as it takes a mutex internally. We'll look into ways of fixing this. For now, you can use `esp_timer_get_time` function (`#include "esp_timer.h"`) to get monotonic time since reset. This function can be used in task code and in ISR.
