### ISSUE TITLE
Unable to flash my code into esp32s3? (IDFGH-11349)

### ISSUE THREAD

**Issue by Abhay-2412** [espressif/esp-idf#12496]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello iam using DF robot [FireBeetle 2 ESP32-S3](https://wiki.dfrobot.com/SKU_DFR0975_FireBeetle_2_Board_ESP32_S3#target_6) and facing difficulty in flashing the code , i was able to flash code to it through Arduino IDE but unable to do the same in ESP-IDF iam using v4.4.5 anyone please help me troubleshooting it

**Comment by o-marshmallow** [comment]
Hello @Abhay-2412 ,

Please give use more details so that we can help you troubleshooting:

* Which OS are your running on? Windows, Mac or Linux?
* How have you installed ESP-IDF?
* Have you installed the drivers for the UART-to-USB adapter? (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html)
* Which example have you tried to build?
* How did you proceed to build and flash the example?
* What message or log is shown on screen when you try to flash the board? Which error are shown?
*

**Comment by o-marshmallow** [comment]
Hello @Abhay-2412 ,

Please give use more details so that we can help you troubleshooting:

* Which OS are your running on? Windows, Mac or Linux?
* How have you installed ESP-IDF?
* Have you installed the drivers for the UART-to-USB adapter? (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html)
* Which example have you tried to build?
* How did you proceed to build and flash the example?
* What message or log is shown on screen when you try to flash the board? Which error are shown?
*
