### ISSUE TITLE
[TW#16440] In lwip/api/sockets.c, “set_errno(err)” probably not running properly

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-idf#1261]
In components/lwip/api/sockets.c, line 437:

#if LWIP_SOCKET_SET_ERRNO
#ifndef set_errno
#define set_errno(err) do { if (err) { errno = (err); } } while(0)
#endif
#else /* LWIP_SOCKET_SET_ERRNO */
#define set_errno(err)
#endif /* LWIP_SOCKET_SET_ERRNO */

When "err" is 0, “set_errno(err)” probably not running properly.
So the value of "errno" is still the last value.
For example in components/lwip/api/sockets.c, line 1504:

  if (i == -1) {
    LWIP_DEBUGF(SOCKETS_DEBUG, ("-1 / ENFILE (could not allocate socket)\n"));
    netconn_delete(conn);
    set_errno(ENFILE);
    return -1;
  }
  conn->socket = i;
  LWIP_DEBUGF(SOCKETS_DEBUG, ("%d\n", i));
  set_errno(0);
  return i;

**Comment by liuzfesp** [comment]
Hi @xiruilin I think this is not an issue, the application need to get the socket error only when some socket APIs fails, e.g. recv() returns -1 etc. Since the IDF LWIP is thread-safe, one socket can be used in multiple threads, e.g taskA send packets to the socket while taskB receives from the same socket, if every time the err=0 should overwrite the error code, then confusing will happen.
