### ISSUE TITLE
ESP32-C6 deep sleep current >1mA (IDFGH-11526)

### ISSUE THREAD

**Issue by NoNullptr** [espressif/esp-idf#12651]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

master

### Espressif SoC revision.

ESP32-C6FH4 (QFN32) (revision v0.0)

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C6-Mini-1

### Power Supply used.

USB

### What is the expected behavior?

Current consumption should be around 7µA in deep sleep, according to datasheet.

### What is the actual behavior?

ESP32-C6 consumes >1mA when both cores are sleeping (in deep sleep), which is substantially more than even the stated value for light sleep.

### Steps to reproduce.

A simple test app that starts both cores and goes to sleep.

sdconfig.defaults:
```
CONFIG_ULP_COPROC_ENABLED=y
CONFIG_ULP_COPROC_TYPE_LP_CORE=y
```

lp_main.c:
```c
#include <ulp_lp_core_utils.h>

void main()
{
    ulp_lp_core_halt();
}
```

main.c:
```c
#include <esp_sleep.h>
#include <ulp_lp_core.h>

extern const uint8_t lp_core_main_bin_start[] asm("_binary_lp_core_main_bin_start");
extern const uint8_t lp_core_main_bin_end[]   asm("_binary_lp_core_main_bin_end");

void app_main()
{
    esp_err_t ret = ESP_OK;

    ulp_lp_core_cfg_t cfg = {
        .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_HP_CPU,
    };

    ret = ulp_lp_core_load_binary(lp_core_main_bin_start, (lp_core_main_bin_end - lp_core_main_bin_start));
    if (ret != ESP_OK) {
        printf("failed to load LP core\n");
        abort();
    }
    ret = ulp_lp_core_run(&cfg);
    if (ret != ESP_OK) {
        printf("failed to run LP core\n");
        abort();
    }

    esp_deep_sleep_start();
}
```

**Comment by esp-wzh** [comment]
Hi! @NoNullptr 

Sorry for the late relpy, the reason for the high power consumption is that the LP CPU does not enter sleep state,  LP CPU is in sleep state by default when soc startup. In `ulp_lp_core_run->lp_core_ll_hp_wake_lp` of your code, the LP_CPU is awakened through the `ULP_LP_CORE_WAKEUP_SOURCE_HP_CPU` interrupt, and then the corresponding interrupt status bit is set. when ULP requests sleep, because the interrupt source is not been cleared, sleep is rejected. 

This problem can be solved by set `PMU_HP_SW_TRIGGER_INT_CLR` bit in `PMU_LP_INT_CLR_REG` to  clear this interrupt source before LP_CPU goes to sleep. Of course, we will also fix it in IDF master and backport to v5.1 and v5.2 soon.

Thank you for reporting this issue!
