### ISSUE TITLE
Calling rmt_write_items caused a failed error check relating to EVT thresholds.

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#127]
When we call `rmt_write_items()` with a small number of items, the exception check described here:

https://github.com/espressif/esp-idf/blob/master/components/driver/rmt.c#L343

I believe I have configured the channel I am using (channel 0) with 1 memory block.

Unfortunately I can't easily give you a recreate sample as the RMT code is embedded in a much larger project.  I can run tests and put in instrumentation as needed and will always be willing to screen share live if requested.

**Comment by projectgus** [comment]
Hi @nkolban,

Sorry for the slow reply on this issue. Unfortunately the master branch seems to have changed since your post, so the source line linked above is empty. Can you be more specific about the error you're receiving, please?

Also, how many items is a small number? And can you please confirm if the bug still exists in current master?

Angus
