### ISSUE TITLE
I2C Interrupt Code  (IDFGH-11657)

### ISSUE THREAD

**Issue by zeynepdicle** [espressif/esp-idf#12770]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1.2

### Espressif SoC revision.

ESP32-C3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

I want to watch and handle master interrupts on the I2C interface in a bare-metal environment.

**Comment by KonstantinKondrashov** [comment]
Hi @zeynepdicle!
The i2c_driver_install() has already allocated the i2c isr handler. You do not need to allocate it twice. Please have a look the driver code - https://github.com/espressif/esp-idf/blob/master/components/driver/i2c/i2c.c#L402.

```c
esp_err_t i2c_driver_install(
...
    //hook isr handler
    ret = esp_intr_alloc(i2c_periph_signal[i2c_num].irq, intr_alloc_flags,
                           i2c_isr_handler_default, p_i2c_obj[i2c_num],
                           &p_i2c_obj[i2c_num]->intr_handle);
```

I2C example - https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2c/i2c_simple/main/i2c_simple_main.c

**Comment by zeynepdicle** [comment]
> Hi @zeynepdicle! The i2c_driver_install() has already allocated the i2c isr handler. You do not need to allocate it twice. Please have a look the driver code - https://github.com/espressif/esp-idf/blob/master/components/driver/i2c/i2c.c#L402.
> 
> ```c
> esp_err_t i2c_driver_install(
> ...
>     //hook isr handler
>     ret = esp_intr_alloc(i2c_periph_signal[i2c_num].irq, intr_alloc_flags,
>                            i2c_isr_handler_default, p_i2c_obj[i2c_num],
>                            &p_i2c_obj[i2c_num]->intr_handle);
> ```
> 
> I2C example - https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2c/i2c_simple/main/i2c_simple_main.c

Does this imply that ESP-IDF utilizes the I2C function through Interrupt Service Routines (ISRs)? Consequently, it appears unnecessary to employ explicit interrupt functions.

**Comment by KonstantinKondrashov** [comment]
Hi @zeynepdicle! Yes, I2C driver uses ISR. As I understand, you need to use a callback:

I2C master callbacks
When an I2C master bus triggers an interrupt, a specific event will be generated and notify the CPU. If you have some functions that need to be called when those events occurred, you can hook your functions to the ISR (Interrupt Service Routine) by calling [i2c_master_register_event_callbacks()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2c.html#_CPPv435i2c_master_register_event_callbacks23i2c_master_dev_handle_tPK28i2c_master_event_callbacks_tPv). Since the registered callback functions are called in the interrupt context, user should ensure the callback function doesn't attempt to block (e.g. by making sure that only FreeRTOS APIs with ISR suffix are called from within the function). The callback functions are required to return a boolean value, to tell the ISR whether a high priority task is woke up by it.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2c.html#register-event-callbacks

**Comment by zeynepdicle** [comment]
> Hi @zeynepdicle! Yes, I2C driver uses ISR. As I understand, you need to use a callback:
> 
> I2C master callbacks When an I2C master bus triggers an interrupt, a specific event will be generated and notify the CPU. If you have some functions that need to be called when those events occurred, you can hook your functions to the ISR (Interrupt Service Routine) by calling [i2c_master_register_event_callbacks()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2c.html#_CPPv435i2c_master_register_event_callbacks23i2c_master_dev_handle_tPK28i2c_master_event_callbacks_tPv). Since the registered callback functions are called in the interrupt context, user should ensure the callback function doesn't attempt to block (e.g. by making sure that only FreeRTOS APIs with ISR suffix are called from within the function). The callback functions are required to return a boolean value, to tell the ISR whether a high priority task is woke up by it.
> 
> https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2c.html#register-event-callbacks

Yes, I want to do this, but the document you sent me does not match the latest version. Some of the functions mentioned here appear to be undefined in the build I'm using (v15.1.2).
