### ISSUE TITLE
ESP-IDF installation is too convoluted (IDFGH-11746)

### ISSUE THREAD

**Issue by Joebeazelman** [espressif/esp-idf#12848]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3-dev-1043-g8c9e29898f

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Ideally, there should be a single folder on my system containing all things related to espressif. If IDF is a product, it should be a subfolder within it. It would be nice if .espessif folder wasn't hidden so it's easier to find by the user if needed.

### What is the actual behavior?

Installing IDF creates two interelated directories on my system, ~/esp/esp-idf and ~/.espressif. The first is an actual git repo, whereas the second one isn't. It's unclear why there's a separation between the two installed folders. Both folders contain a tools subdirectory with different types of functions. From the looks of it, it appears the repo is intended to setup the environment. 

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by igrr** [comment]
Hi @Joebeazelman,
We made an attempt to explain the purpose of the .espressif directory in this section of the programming guide: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-tools.html

The separation between the two directories — the git repo itself and the "downloadable tools" directory is intentional. Downloadable tools (toolchains, debugging tolls) are typically large archives which are not well suited for being stored in git. At the same time, they change less often than IDF does. It is often possible to use the same version of the tool in multiple versions of IDF, so such a separate tools directory also serves the purpose of not storing multiple copies of the same toolchain even if you have multiple copies of IDF.

Anyway, if you prefer to keep all Espressif-related folders under the same directory, you can. If IDF_TOOLS_PATH environment variable is set, IDF installation scripts will store downloadable tools under that directory, rather than in ~/.espressif. You can set IDF_TOOLS_PATH globally (in your she'll profile script, for example) to the desired location.
