### ISSUE TITLE
esp_netif_set_ip_info doesn't always trigger an IP_CHANGED event. (IDFGH-11836)

### ISSUE THREAD

**Issue by karlp** [espressif/esp-idf#12927]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2-2-g11f9b315f7 (2 commits are unrelated phy changes, separate PR)

### Espressif SoC revision.

ESP32

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

custom

### Power Supply used.

External 3.3V

### What is the expected behavior?

When I use esp_netif_set_ip_info() to change to a different static IP address, I expect the IP_EVENT_ETH_GOT_IP (as appropriate for interface) to be published.  This is required so that (for instance) mDNS can update automatically.

### What is the actual behavior?

Instead, the event is not published.  Note, this only fails when the gateway portion of a static IP is null.  

### Steps to reproduce.

1.
```
	esp_netif_ip_info_t ip;
        ip.ip.addr = ipaddr_addr("10.1.1.1");
        ip.netmask.addr = ipaddr_addr("255.255.0.0");
        ip.gw.addr = ipaddr_addr("0.0.0.0");
        esp_netif_set_ip_info(netif, ip))
```
2. No event will be produced.

### More Information.

The problem is here: https://github.com/espressif/esp-idf/blob/master/components/esp_netif/lwip/esp_netif_lwip.c#L1836:

The new IP address is checked, and if _any_ of ip/mask/gw are null, the actual check on whether the IP has changed is just skipped entirely, regardless of what changes have taken place.  Given that a null gateway is perfectly legitimate, I propose _at least_ removing the `ip4_addr_isany_val(ip_info->gw)` check.  This does fix the problem for me, and makes the system behave much more predictably.

Arguably, the entire triple check should be dropped though.  The `memcmp` check below, that _actually_ checks whether the addresses have changed at all should already completely cover this.

**Comment by david-cermak** [comment]
Hi @karlp 

Thanks for reporting this problem. I agree that we don't have to check the default gateway nor the mask. I would however leave the IP address condition there, due to historic reasons (setting an IP to  `IP4_ANY` meant loosing the IP) and to be in line with other parts of the code, e.g. here (called directly from lwip):

https://github.com/espressif/esp-idf/blob/6b9c2fca79a7b77a42242d48b0cfa82d612e9b85/components/esp_netif/lwip/esp_netif_lwip.c#L1281

I'll replace this line:

https://github.com/espressif/esp-idf/blob/6b9c2fca79a7b77a42242d48b0cfa82d612e9b85/components/esp_netif/lwip/esp_netif_lwip.c#L1835

with checking `ip4_addr_isany_val(ip_info->ip)` only. Please keep this open, we'll close it after it's fixed in IDF.
