### ISSUE TITLE
ESP-IDF Eddystone Example (IDFGH-11963)

### ISSUE THREAD

**Issue by yukselen26** [espressif/esp-idf#13040]
.

**Comment by cstratton** [comment]
The ble-eddystone example is not an example of advertising as an eddystone beacon, but rather an example of scanning for them.   Since both that example and your phone are scanning for beacons rather than advertising beacon packets, neither will detect the other.

I'm not seeing an eddystone beacon example in esp-idf, you could take the existing ibeacon example and modify it to eddystone packet format and behavior instead.

Perhaps if you look around online you'll find a 3rd party example for transmitting as an eddystone type beacon.
