### ISSUE TITLE
esp-idf build on windows with using python (IDFGH-12026)

### ISSUE THREAD

**Issue by kush930** [espressif/esp-idf#13091]
Hi all,

I successfully cloned  esp-idf from link:-  https://github.com/espressif/esp-idf

I am running python command on windows os.

D:\`esp-idf\examples\wifi\iperf>python3 pytest_iperf.py  `                                                      

```
  Traceback (most recent call last): File "D:\esp-idf\examples\wifi\iperf\pytest_iperf.py", line 25, in <module>                                       
  from common_test_methods import get_env_config_variable, get_host_ip_by_interface                                  
   ModuleNotFoundError: No module named 'common_test_methods'       
```                                                                                                                            

`I installed package "commonmethods" wit using pip3 successfully, and verified with using import command its showing package, but when I am running python3 pytest_iperf.py commands, its giving common_test_methods module not found.`

Can anyone suggest me where I am doing wrong,  please help me to build on windows.

T&R
lavkhush

**Comment by dobairoland** [comment]
Hi @kush930. 

Please follow the guide at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html to set up an environment. Cloning the repository might not be enough. On Windows, we recommend to use the installer from https://dl.espressif.com/dl/esp-idf/ to set up a working environment.

I'm not sure that you really want to to run `pytest_iperf.py`. It is a test script for testing the example in our pipeline. I'm not sure if it is supported on Windows. I'll skip explaining how to run it because you probably don't want to do it.

If you want to use the example then you can follow the above guide. After building (`idf.py build`), flashing (`idf.py flash`) you will able to use it by monitoring (`idf.py monitor`). Please see the guide for more information.
