### ISSUE TITLE
RMT driver, memory management clarification / documentation (IDFGH-12068)

### ISSUE THREAD

**Issue by higaski** [espressif/esp-idf#13129]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The new RMT transmission driver introduced with ESP-IDF 5 does require the user to keep data pointed to by the transaction queue alive until this particular transmission gets completed. The documentation mentions multiple times that the internal queue really is **just a job queue**, but I still think that there should be one paragraph about memory management.

The potential to introduce very subtle bugs here is huge, specially when changing the RMT configuration. Imagine users switching from blocking to non-blocking behavior, or simply change the transaction queue size from 1 to 2.

**Comment by technosf** [comment]
I would like to also ask for clarification here, rather than open a bug for an issue I am seeing with RMT memory management, as I am making assumptions due to the lack of doc on behavior once a **RMT_ENCODING_MEM_FULL** state is reached. 

Working with ESP-IDF **5.2**, I made the assumption, given no documentation on this state, that the encoder yields and is subsequently called again, jumping to the same state and continues. And on the surface it does (from logging statements), but the behavior on the wire indicates a buffer or counter under or overrun. I am not sure if this is indicative of a missed memory management step (clearing a buffer), or an buffer or counter under/overrun in the IDF code.

If you take the ESP _NEC IR_ example as a base, and create a complex Encoder with multiple states (say 3) and then send more symbols than the symbol buffer size, I find that you get chaos on the wire on the initial RMT_ENCODING_MEM_FULL, and then that encoder keeps being reentered at the same state and hitting the RMT_ENCODING_MEM_FULL return state ad infinitum never cleanly exiting the encoder.
