### ISSUE TITLE
exFAT on esp32s3 support feature request (IDFGH-12174)

### ISSUE THREAD

**Issue by alex04130** [espressif/esp-idf#13229]
### Is your feature request related to a problem?

I wanted to have a exfat support on my esp32 board with ESP-IDF. And I found a way to let it work.

### Describe the solution you'd like.

# There is already a solution that can be applied to this question, which relies on IDF's FatFs library. 
| in ffconf.h
set FF_LBA64 to 1
set FF_FS_EXFAT to 1
* because LFN must be enabled when enabling exFAT
Long filename support on menu-config should not be set to  "No long filenames".

* because when using spi sd host and exFAT format, the driver will throughout an ESP_ERR_INVALID_RESPONSE error in the trim function
 the FF_USE_TRIM in ffconf.h should be set to 0

The solution I'd like is to put these in the menu-config since I tested it and it worked.

**Comment by igrr** [comment]
We have intentionally not added an easy way to enable exFAT support via menuconfig. This was because in the development stage, people may enable this option and forget about it. However, usage of exFAT implementations in many cases requires a [license](https://www.microsoft.com/en-us/legal/intellectualproperty/tech-licensing/programs?activetab=pivot1%3aprimaryr2) from Microsoft.

On balance, we decided that if you are going through the trouble of obtaining this license, using a patched version of ffconf.h isn't the biggest of the issues. And for everyone else, this prevents potential legal issues.

**Comment by alex04130** [comment]
t

**Comment by alex04130** [comment]
Thank you very much

**Comment by Red-Owl** [comment]
exFAT as part of the Linux kernel

In August 2019 Microsoft announced its support for integrating exFAT into the Linux kernel. exFAT is now part of the Linux kernel 5.7 and devices using this code are covered under the GPLv2 license.

translate: your software is open source or pay license to microsoft

**Comment by Trackhe** [comment]
Is there any update on this?

**Comment by p1ngb4ck** [comment]
@igrr

exFat = GPLv2

espressif = company = legal inclusion w/o license to framework = not possible
user = private = license depending on user decision = inclusion of exFat to open-source projects using GPLv2 = perfectly fine

Actual way things work:
User sets configs => Framework downloads libs on user action to users machine and compiles for users project. No license violation there at all.

I don`t actually think you wanna go on and shoot your own foots business-wise, by providing perfectly fine technical support on modern arch like P4 and keep the framework not able to use modern storages, bc the real-world fact, that exFat is on supported on any modern platform is ignored due to outdated info.
