### ISSUE TITLE
How to Indicate BLE 'Service Changed' (0x2A05)

### ISSUE THREAD

**Issue by mainr** [espressif/esp-idf#1777]
Under BLE standard 'Generic Attribute' (0x1801) there is a Characteristic 'Service Changed' (0x2A05) with 'indicate' property, which is supposed to be used to indicate that a range of handles in the BLE device have changed, so that they can be 're-discovered', updating any cached information.

How would I go about triggering this? 
How do I specify the 'range of affected handles' that are affected by the change?
Does the client need to 'subscribe' to get the indication, or is this automatic (there is no 0x2902 descriptor to write to)?

Issue ( #1673 ) seems to indicate the 'service changed' notification is something other than what I interpret is is supposed to be.

**Comment by Weijian-Espressif** [comment]
@mainr gattc is automatic to 'subscribe'  the notification,  client will get ESP_GATTC_SRVC_CHG_EVT

**Comment by mws-rmain** [comment]
Thanks for the response @Weijian-Espressif .

To clarify:
Say my 'gatt_server' is an ESP32, and the 'client' is an android phone.
Say my 'gatt_server' device has an attribute table:
```
SERVER 1
  +- service
  |  +- characteristic 1
  |  +- characteristic 2
  +- service
     +- characteristic 3
```
Now some conditions arise that cause the STRUCTURE of the attribute table to change, such as exposing a new service (or removing an existing one, etc.). If adding, say the attributes now look like:
```
SERVER 1
  +- service 1
  |  +- characteristic 1
  |  +- characteristic 2
  +- service 2
  |  +- characteristic 3
  +- service 3
     +- characteristic 4
```
I understand the function of the 'service changed' notification is to inform the client that changes have occured, and it should flush its internal cache (GAP/GATT) for this device, and re-discover services.

What I don't understand is what does the gatt server code running on the ESP32 need to do after modifying the GATT structure to trigger the notify/indicate to the client?

Surely the notification is not automatic so that EVERY change to the GATT triggers notification?
If so, the client-side discovery would be triggered every time a change was made?
What I expect is the server would make whatever changes are necessary, then issue some kind of 'commit' or 'update' or 'notify' command to trigger the 'service changed' notification.

**Comment by Weijian-Espressif** [comment]
[service_change_demo.zip](https://github.com/espressif/esp-idf/files/1859163/service_change_demo.zip)
please refer to the service change demo

**Comment by Sladerix** [comment]
> [service_change_demo.zip](https://github.com/espressif/esp-idf/files/1859163/service_change_demo.zip)
> please refer to the service change demo

Hi, is there the Arduino Framework version of this?

**Comment by Sladerix** [comment]
> > [service_change_demo.zip](https://github.com/espressif/esp-idf/files/1859163/service_change_demo.zip)
> > please refer to the service change demo
> 
> Hi, is there the Arduino Framework version of this?

Nothing?

**Comment by sdetweil** [comment]
@Sladerix I don't find anything specific either 'range of...' is ambiguous at best

but I 'guess' that in the end one sends a notify on this characteristic, which triggers the host side action. 
I'm going to add that to my arduino code and see what happens...
