### ISSUE TITLE
heap_caps_check_integrity() with comprehensive heap checking enabled and 4MB spiram causes system pa (IDFGH-219)

### ISSUE THREAD

**Issue by chmorgan** [espressif/esp-idf#1858]
I'm calling heap_caps_check_integrity() periodically from the main task. With 4MB spiram and comprehensive heap checking it looks like the heap_caps_check_integrity() is suspending interrupts or otherwise blocking execution. In my use case I'm using a timer to blink a cpu activity light and the blinking is erratic. Behavior not seen if I remove the call to heap_caps_check_integrity() or run on a system with less ram.

Possible to optimize the heap_caps_check_integrity() call to avoid these long delays? I looked but I'm unfamiliar with the code and nothing obvious stood out.

**Comment by projectgus** [comment]
Hi @chmorgan,

I'm really sorry noone ever got back to you about this.

For a combination of thread safety and performance reasons, heap access happens in a critical section with interrupts disabled. If there are a lot of individual allocations in PSRAM (or "Comprehensive" heap checking is turned on) then it can take a long time to check using `heap_caps_check_integrity()`.

Unfortunately there is no solution to this that doesn't slow down the performance of normal heap operations (i.e. we could use a different type of lock like a FreeRTOS mutex that didn't disable interrupts but then all heap operations would incur the overhead of taking/releasing the mutex.)

The expectation is that `heap_caps_check_integrity()` would normally only be called while debugging a heap issue. Is that the case for you?

Checking integrity in PSRAM can also cause a lot of cache thrashing (because many unrelated PSRAM addresses are read, usually enough to overhwelm the cache). So there is also a performance hit for any other parts of your firmware that use PSRAM.

I don't know if it's useful for your purposes, but changing the caps argument to check `MALLOC_CAP_INTERNAL` memory only will significantly improve performance. However this won't detect heap corruption in any PSRAM region.
