### ISSUE TITLE
[TW#24196] assert (entry < ENTRY_COUNT) in nvs_flash

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#2026]
One of our customers is seeing below reset issue and log says an assert is done from below.  We are using 3.0 release from ESP.  What is the meaning of this assert?
    uint32_t getEntryAddress(size_t entry) const
    {
        **assert(entry < ENTRY_COUNT);**

Also, is there any redirection can be done for asserts used in ESP components.  i.e. Can application control what to be done when an assert happens?

![image001](https://user-images.githubusercontent.com/10186400/40898334-3b606b0a-67de-11e8-9759-eae53f918cf8.jpg)

**Comment by igrr** [comment]
Hi @hvishu, please use [IDF monitor tool](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/idf-monitor.html) (`make monitor`) — it will decode the backtrace automatically. Please post the decoded backtrace here.
Also please use `esptool.py` to download the problematic NVS partition:
```
$IDF_PATH/components/esptool_py/esptool/esptool.py --port COMx read_flash 0x9000 0x6000 nvs_dump.bin
```
(replace COMx with your port number). Please attach resulting nvs_dump.bin file here as well.

Regarding assertions, usually a failed assertion indicates an unexpected condition for which there is no recovery path in the code. You can disable assertions (in menuconfig, under Compiler options), but this is not advisable because the program will likely crash soon after the failed assertion anyway, but debugging output would be much less useful.

**Comment by FayeY** [comment]
Hi @hvishu , did the above suggestion help you resolve the issue?

**Comment by hvishu** [comment]
We increased the NVS partition size as it was at the border.  Right now seeing this issue, but I am not 100% sure lesser NVS partition was the root cause of the issue.
