### ISSUE TITLE
[TW#23414] #include <termios.h> fails

### ISSUE THREAD

**Issue by dmcnaugh** [espressif/esp-idf#2063]
The file `esp-idf/components/newlib/include/termios.h` includes the line
```
#include <sys/termios.h>
```
However this file `sys/termios.h` does not exist anywhere in the esp-idf
subsequently having an `#include <termios.h>` in my code fails.

**Comment by igrr** [comment]
I've marked this as "enhancement", since I assumed that the desired behavior is not only to be able to include `termios.h`, but also to be able to use functions normally defined there (http://pubs.opengroup.org/onlinepubs/7908799/xsh/termios.h.html). This will need some work to connect these functions to the UART (or other VFS driver) APIs.
