### ISSUE TITLE
[TW#23626] BLE Scanning: Reset/configure duplicate filter

### ISSUE THREAD

**Issue by buzzzsam** [espressif/esp-idf#2079]
## Environment

- Core (if using chip or module): |ESP32-WROOM-32U|ESP-WROOM-32D|ESP-WROOM32|ESP32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
e1a6e71
- Development Env:		Make
- Operating System:		MacOS
- Power Supply:         USB

Not exactly a problem, but a question and a request
Question: For BLE scanning is it possible to reset the duplicate filter?  Is it a timer based solution now?
Request: Is it possible to change this to 500/1000 duplicate ?? May be if we use the WROVER32 for extra memory?

Sam

**Comment by Weijian-Espressif** [comment]
hi @buzzzsam  There are three ways to reset the duplicate filter.
1)  stop scan
2)  duplicate filter is full, the size is due to "Maximum number of devices in scan duplicate filter" in menuconfig
3) Time is up (about one minute)

you can change the "Maximum number of devices in scan duplicate filter" to 500/1000, you need modify some code in /components/bt/Kconfig.

config DUPLICATE_SCAN_CACHE_SIZE
    int "Maximum number of devices in scan duplicate filter"
    depends on BLE_SCAN_DUPLICATE
    **range 10 1000**
    default 20
    help
        Maximum number of devices which can be recorded in scan duplicate filter.
        When the maximum amount of device in the filter is reached, the cache will be refreshed.
