### ISSUE TITLE
In branch ’feature/cmake‘.The problem remains unsolved about "ip_addr_t has no member named 'addr  in  ip4_addr.h‘"

### ISSUE THREAD

**Issue by kavinkun** [espressif/esp-idf#2231]
Thank you for your reply。
I use the LWIP lightweight library provided in the project to Create an OTA upgrade program using the FTP protocol for FTP Client。but I met a very serious problem. here it is:
/**********************************************************************************************/
/home/workstation/esp-idf/components/lwip/include/lwip/lwip/ip4_addr.h:141:17: error: 'ip_addr_t {aka struct _ip_addr}' has no member named 'addr'
         (ipaddr)->addr = ((u32_t)((d) & 0xff) << 24) | \
                 ^
/home/workstation/project/smart-n6k5/main/ftp_client.c:208:2: note: in expansion of macro 'IP4_ADDR'
  IP4_ADDR(&data_server,a,b,c,d);
  ^
/home/workstation/project/smart-n6k5/main/ftp_client.c: In function 'ftp_init':
/home/workstation/esp-idf/components/lwip/include/lwip/lwip/ip4_addr.h:141:17: error: 'ip_addr_t {aka struct _ip_addr}' has no member named 'addr'
         (ipaddr)->addr = ((u32_t)((d) & 0xff) << 24) | \
                 ^
/home/workstation/project/smart-n6k5/main/ftp_client.c:861:2: note: in expansion of macro 'IP4_ADDR'
  IP4_ADDR(&ftp_config.server_ip, 192,168,10,50);
  ^
/***********************************************************************************************/
By observation, this problem may be due to the possibility that IDF in the ADF version may be caused by the master version, so I switch to the feature/cmake version to compile, and there is still such a problem.

In IDF about lightweight LwIP libraries, I would like to ask whether to support asynchronous TCP connections. How should I do for this problem wanna solved?

**Comment by projectgus** [comment]
Hi @kavinkun ,

The `IP4_ADDR` macro expects to be passed a struct of type `ip4_addr_t`, not `ip_addr_t`. This is why you're getting this error.

If you need a struct of type `ip_addr_t`, use the macro `IP_ADDR4` instead. Otherwise, change the variable to type `ip4_addr_t`.

(I realise this is confusing, unfortunately this is how the LWIP APIs are designed. The macros in `lwip/ip4_addr.h` operate on `ip4_addr_t` only, and the macros in `lwip/ip_addr.h` operate on `ip_addr_t` only. `ip_addr_t` can represent either an IPv4 or an IPv6 address.)

> In IDF about lightweight LwIP libraries, I would like to ask whether to support asynchronous TCP connections. How should I do for this problem wanna solved?

The best place to ask questions like this is the forum at https://esp32.com

The short answer is: you can use standard BSD socket APIs to make sockets non-blocking (ie `fcntl(fd, F_SETFL, O_NONBLOCK)`), and/or use the standard BSD socket function `select()` to handle multiple TCP sockets in a single task. If you're having trouble getting the project to work how you expect, please post some code on the forums and we can help you there.
