### ISSUE TITLE
[TW#24914] First stage bootloader resets many times

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2243]
## Environment

- Development Kit:      [none]
- Core (if using chip or module): [ESP-WROOM32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    561884b6
- Development Env:		[Make]
- Operating System:		[Linux]
- Power Supply:         [USB]

## Problem Description

First stage bootloader keeps restarting many times until finally loads application.
This is the first time I noticed it and it is very hard to reproduce again (so providing source code does not probably help much).

I have disabled both interrupt and task watchdogs so I can setup them manually.

I setup TIMG0 watchdog like this
```
periph_module_enable(PERIPH_TIMG0_MODULE);
TIMERG0.wdt_wprotect=0x50d83aa1;
TIMERG0.wdt_config0.sys_reset_length=7;
TIMERG0.wdt_config0.cpu_reset_length=7;
TIMERG0.wdt_config0.level_int_en=0;
TIMERG0.wdt_config0.edge_int_en=0;
TIMERG0.wdt_config0.stg0=2;
TIMERG0.wdt_config0.stg1=0;
TIMERG0.wdt_config0.stg2=0;
TIMERG0.wdt_config0.stg3=0;
TIMERG0.wdt_config1.clk_prescale=80;  
TIMERG0.wdt_config2=1000;
TIMERG0.wdt_config0.en=1;
TIMERG0.wdt_feed=1;
TIMERG0.wdt_wprotect=0;
```

and TIMG1 watchdog
```
periph_module_enable(PERIPH_TIMG1_MODULE);
TIMERG1.wdt_wprotect=0x50d83aa1;
TIMERG1.wdt_config0.sys_reset_length=7;
TIMERG1.wdt_config0.cpu_reset_length=7;
TIMERG1.wdt_config0.level_int_en=0;
TIMERG1.wdt_config0.edge_int_en=0;
TIMERG1.wdt_config0.stg0=3;
TIMERG1.wdt_config0.stg1=0;
TIMERG1.wdt_config0.stg2=0;
TIMERG1.wdt_config0.stg3=0;
TIMERG1.wdt_config1.clk_prescale=40000;
TIMERG1.wdt_config2=2000;
TIMERG1.wdt_config0.en=1;
TIMERG1.wdt_feed=1;
TIMERG1.wdt_wprotect=0;
```

From monitor log I conclude that TIMG0 has reset PRO CPU and that caused bootloader to reload app. This is OK but I don't think that `ets Jun  8 2016ets Jun  8 2016ets Jun  8 201ets Jun  8 2016...` messages are expected behavior.

I guess that I have been writing into flash using `esp_partition_write` when watchdog reset occured and it took a long time to bootloader to recover from this.

Is it possible?

## Debug Logs
https://pastebin.com/kHBR4m9v

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.) 

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/2242215/sdkconfig.txt)
[partitions.txt](https://github.com/espressif/esp-idf/files/2242221/partitions.txt)

**Comment by projectgus** [comment]
Hi @michprev ,

Thanks for being patient while someone got back to you about this.

In this case, the ESP32 hardware is behaving as designed and documented (albeit configured in a non-useful way).

Timer group 0 WDT is configured with a Stage 0 timeout of 1ms period (12.5ns * 80 * 1000) to trigger a CPU reset (WDT_STG0 == 2).

Timer group 1 WDT is configured with a Stage 0 timeout of 1 second (12.5ns * 40000 * 2000) to trigger a full system reset (WDT_STG0 == 3).

(Details for these register values can be found in the ESP32 TRM "Timer Group" chapter.)

As described in the ESP32 TRM chapter 19 "Watchdog Timer" section 19.3.1.1 "Operating Procedure", the watchdogs will run through all configured stages and then loop back to the beginning.

As described in the ESP32 TRM Chapter 3 "Reset and Clock", a CPU reset doesn't reset all peripherals only the CPU.

So, 1ms after TG0 WDT is enabled, the CPU is reset by TG0 WDT which then loops back to the beginning. The CPU has just enough time to print "ets Jun  8 2016" (the first bytes printed by the mask ROM after a CPU reset) when TG0 WDT resets the CPU again.

This sequence repeats continuously until TG1 WDT expires after 1s, which triggers a full system reset. This also resets the WDT peripheral itself, so the system is able to restart normally.

Solutions to this situation are:

* Use a system reset for TG0 WDT instead of a CPU reset
* Set a longer timeout for TG0 WDT
* Set at least one additional stage for TG0 WDT with a longer period, so the CPU has some time to start up again and reconfigure itself before the WDT state loops around.
