### ISSUE TITLE
Time of day incorrect until first delay

### ISSUE THREAD

**Issue by lllucius** [espressif/esp-idf#2312]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Core (if using chip or module): ESP32-Wrover
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 8d5ec413
- Development Env:		Make
- Operating System:		Windows (WSL)
- Power Supply:         USB

## Problem Description

Setting the time of day after boot doesn't seem to work until a sufficient amount of time (1000ms ???) has passed.

### Expected Behavior

The time should update after waiting 1000ms, but it doesn't.  In the example below, the first output line should have a "diff" of 1.

### Actual Behavior

The difference is actually 0 assuming vTaskDelay is truly waiting 1000ms.  But, it should be since the remaining lines do show the proper difference.

### Steps to repropduce

Just run the sample code below.

### Code to reproduce this issue

```cpp
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

void app_main()
{
    struct timeval tv;

    tv.tv_sec  = 86400;
    tv.tv_usec = 0;

    settimeofday(&tv, NULL);

    for (int i = 0; i < 5; i++)
    {
        time_t time1;
        time_t time2;

        time1 = time(0);
        vTaskDelay(pdMS_TO_TICKS(1000));
        time2 = time(0);

        printf("time1 = %ld, time2 = %ld, diff = %ld\n",
               time1, time2, time2 - time1);
    }

    vTaskDelay(portMAX_DELAY);
}
```
## Debug Logs

```
time1 = 86400, time2 = 86400, diff = 0
time1 = 86400, time2 = 86401, diff = 1
time1 = 86401, time2 = 86402, diff = 1
time1 = 86402, time2 = 86403, diff = 1
time1 = 86403, time2 = 86404, diff = 1
```

## Other items if possible

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/2302183/sdkconfig.txt)

**Comment by igrr** [comment]
Hi @lllucius,

vTaskDelay(n) blocks the task until n ticks have passed. For example, vTaskDelay(1) may delay anywhere between 0 and 1ms (assuming 1000Hz tick frequency), because it delays *until the next tick*. Since the scheduler is started a bit before `app_main`, by the time execution reaches the first `time` call, the next tick is much less than 1ms away. This, together with the fact that `time` rounds the time down, results in the observed behavior.

Things might get more clear if in addition to `time` you also print microsecond values obtained from `gettimeofday` (Actually, `time` is implemented as a call to `gettimeofday`, which drops the microsecond part and returns seconds only: [source](https://github.com/espressif/newlib-esp32/blob/4ddc99d47677b94c115cafcaa4a6939042ea8c4f/newlib/libc/time/time.c#L46-L51)):

```
time: time1 = 86400, time2 = 86400, diff = 0
gettimeofday: time1 = 86400000098, time2 = 86400999141, diff = 999043
time: time1 = 86400, time2 = 86401, diff = 1
gettimeofday: time1 = 86400999521, time2 = 86401999137, diff = 999616
time: time1 = 86401, time2 = 86402, diff = 1
gettimeofday: time1 = 86401999369, time2 = 86402999137, diff = 999768
time: time1 = 86402, time2 = 86403, diff = 1
gettimeofday: time1 = 86402999369, time2 = 86403999137, diff = 999768
time: time1 = 86403, time2 = 86404, diff = 1
gettimeofday: time1 = 86403999369, time2 = 86404999137, diff = 999768
```
(source code below)

As you can see, on the first delay, time moves from 86400000098us to 86400999141us, which is just a bit short of 86401000000 which would result in `time` returning 86401. This is because of two factors mentioned above: vTaskDelay(1) blocks the task for less than 1ms, and limited resolution of `time` function.

Note that other delays take ~999768 us, which is also a bit less than 1 second. The remaining time is spent in two `printf` calls at the end of the loop. Since the difference is less than 1 second, it is also possible to have identical `time` value before and after delay on one of subsequent loop iterations, just the chance is much smaller.

To summarize, don't rely on `vTaskDelay` for accurate delays, and don't use `time` to measure time if accuracy is required. [esp_timer library](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/esp_timer.html) can provide both quite accurate delays and accurate time interval measurement. If you need even higher accuracy, you can use the [Timer Group driver](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/timer.html) and implement a timer yourself.

```c++
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

void app_main()
{
    struct timeval tv;

    tv.tv_sec  = 86400;
    tv.tv_usec = 0;

    settimeofday(&tv, NULL);

    for (int i = 0; i < 5; i++)
    {
        time_t time1;
        struct timeval tv1;
        time_t time2;
        struct timeval tv2;

        time1 = time(0);
        gettimeofday(&tv1, NULL);
        vTaskDelay(pdMS_TO_TICKS(1000));
        time2 = time(0);
        gettimeofday(&tv2, NULL);

        printf("time: time1 = %ld, time2 = %ld, diff = %ld\n",
               time1, time2, time2 - time1);


        printf("gettimeofday: time1 = %lld, time2 = %lld, diff = %lld\n",
                       tv1.tv_sec * 1000000ULL + tv1.tv_usec,
                       tv2.tv_sec * 1000000ULL + tv2.tv_usec,
                       (tv2.tv_sec - tv1.tv_sec) * 1000000ULL + (tv2.tv_usec - tv1.tv_usec));
    }

    vTaskDelay(portMAX_DELAY);
}
```
