### ISSUE TITLE
[TW#26350] uart1 fifo overflow while flash erase

### ISSUE THREAD

**Issue by rahulbpatel8** [espressif/esp-idf#2424]
Hello,
My application is having uart1 communication where at every 10ms UART1 is receiving data with baud rate of 115200. While accessing flash erase api spi_flash_erase_range() while these data are coming over UART1, I am facing uart1 fifo overflow error from event queue. Without flash erase operations, there is no such issue occurs.
So uart interrupt is not being served while accessing flash.? I am using IDFv2.1 for our application.

By looking into uart_driver_install(), I allowed uart interrupt with ESP_INTR_FLAG_IRAM flag and added whole uart.o in IRAM as discussed in below forum link

[https://www.esp32.com/viewtopic.php?f=2&t=6459&p=27756&hilit=ESP_INTR_FLAG_IRAM#p27756](url)

This solved the issue. As uart interrupt is now allowed while accessing flash I believe.

So now my concern is, my application is accessing .iram0.text is almost 81KB with these changes, so will it cause any issue with other functionalities. It is a major concern that will these changes affect to other functionalities on regression.?

Can you please have any suggestion over it if I still need to manage anything else.?

**Comment by koobest** [comment]
Hi, @rahulbpatel8 
Because the UART ISR handle is not in IRAM  but in cache.  so , it can not be executed while erasing flash(erasing flash will disable cache).  You only need to put the interrupt service function and some function called in interrupt into IRAM ( like this : `static void IRAM_ATTR uart_rx_intr_handler_default`).
but it is best to enable flow control to solve this problem.
