### ISSUE TITLE
[TW#26491] Better support for Powershell with the CMake build system

### ISSUE THREAD

**Issue by tuangu** [espressif/esp-idf#2464]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v4]
- Core (if using chip or module): [ESP-WROOM32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): e7faa1d85
- Development Env:		[CMake]
- Operating System:		[Windows 10]
- Power Supply:         [USB]

## Problem Description
Currently, when executing the idf.py, a new CMD window show up which is actually running python. In some cases, for example, running idf.py without any arguments, the CMD window opens, prints few lines, and then closes.

### Steps to reproduce
1. Open Powershell
2. Run ``idf.py``

[Screenshot when running ``idf.py menuconfig``](https://imgur.com/a/vliBfRA)

**Comment by igrr** [comment]
Hi @tuangu, sorry that this issue was left without any response. This seems to be the behavior of Powershell: when idf.py is invoked, powershell opens a new window where the Python interpreter is started. In other words, it does not matter what we do in idf.py or the build system, new window will be opened anyway. However you can modify PATHEXT variable in your Powershell environment to allow running Python scripts in the same window:

```
$env:PATHEXT += ";.py"
```

(source: [stackexchange answer](https://superuser.com/a/437853)).

After this, idf.py and other Python scripts will run from the same Powershell window.
