### ISSUE TITLE
[TW#12213] RTC runs too fast when in deep sleep mode

### ISSUE THREAD

**Issue by baycom** [espressif/esp-idf#268]
According to the SNTP example the RTC keeps running while in deep sleep. After a wake up it seems that the clock ran too fast while sleeping. After a minute of deep sleep the ESP32 is about 10 seconds ahead of local time.

**Comment by igrr** [comment]
Since 0fe765a, we are doing calibration of the internal RC oscillator instead of assuming that it runs at 150kHz. New configuration option ("Number of cycles for RTC_SLOW_CLK calibration") can be tuned for lower startup time or higher calibration accuracy, depending on application requirements.

@baycom feel free to reopen this if you find that the time drift is still happening.
