### ISSUE TITLE
[TW#27558] esptool error during "make" when processing ELF file

### ISSUE THREAD

**Issue by pilnikov** [espressif/esp-idf#2727]
when I try to build a project with version 3.2.1Beta when processing .elf file, I get a 
struct.error: ubyte format requires 0 <= number <= 255
in esptool.py
![esptool](https://user-images.githubusercontent.com/25922873/48883062-c3323d00-ee3f-11e8-9fa4-cae61c7d0fe8.JPG)
![image](https://user-images.githubusercontent.com/25922873/48883141-2de37880-ee40-11e8-9d99-2deb4ea47a77.png)

**Comment by projectgus** [comment]
Hi @pilnikov ,

Is this an open source project? If so, are you able to attach the sdkconfig and the KaRadio32.elf file from the build directory? If you can't share them it's OK, can figure out another approach.

**Comment by igrr** [comment]
backlink https://github.com/karawin/Ka-Radio32/issues/65

**Comment by pilnikov** [comment]
Yes of course. Its  karadio from https://github.com/karawin/Ka-Radio32
[1.ZIP](https://github.com/espressif/esp-idf/files/2607075/1.ZIP)

**Comment by projectgus** [comment]
Thanks for posting those.

Something seems to have gone wrong in the linker script for both v3.1.1 and v3.2-beta1.

The ELF files both have hundreds of loadable sections when they should have about 5 (you can look at the output with `xtensa-esp32-elf-objdump -h ELFFILE`).

For v3.1.1, there are 254 loadable sections so the .bin file is generated - however the generated .bin file won't boot as the bootloader can only handle up to 16 loadable sections.

For v3.2, there are more than 255 loadable sections so the esptool error comes when this value is packed into a single byte.

I'll fix the error message to be more informative, but the problem is with the ELF file not the elf2binary step.

I can't reproduce the ELF problem with ESP-IDF examples or with the Ka-Radio32 project. Is it possible you've edited some of the linker script files in the IDF repository itself which is causing a bad link?

**Comment by projectgus** [comment]
> Is it possible you've edited some of the linker script files in the IDF repository itself which is causing a bad link?

One other question, can you please post the output of `git describe --tags --dirty` when run in the IDF directory? Thanks.

**Comment by pilnikov** [comment]
![image](https://user-images.githubusercontent.com/25922873/48929435-9eef6280-ef0a-11e8-89ca-c6ca92d28a12.png)

**Comment by pilnikov** [comment]
> I can't reproduce the ELF problem with ESP-IDF examples or by building the Ka-Radio32 project locally. Is it possible you've edited some of the linker script files in the IDF repository itself which is causing a bad link?

Tru make without paremeter
e.g.
make -j4

**Comment by pilnikov** [comment]
![image](https://user-images.githubusercontent.com/25922873/48929538-99dee300-ef0b-11e8-9d80-776b2b094257.png)

**Comment by pilnikov** [comment]
after git pull & git submodule update
![image](https://user-images.githubusercontent.com/25922873/48929631-62bd0180-ef0c-11e8-93d6-484fbd407255.png)

**Comment by pilnikov** [comment]
[2.zip](https://github.com/espressif/esp-idf/files/2609806/2.zip)
Files after make all with updated 3.2 beta1
Size .elf = 6m

**Comment by projectgus** [comment]
The binary seems to be building correctly now, so it appears some change on master branch has fixed this.

One thing I noticed in your screenshots is you are running MSYS2 via "msys.exe", not "mingw32.exe". This is not supported - if you look in the build output you'll see a warning about it. The root cause may be something to do with that, and using an MSYS rather than a MINGW32 Python. But I'm just guessing.

(BTW, I can't explain why your copy of git describes commit 4c881708d as being based on v3.2-beta1-182-g4c881708d. This commit is actually v3.3-dev, and if I clone from github on Windows it's described correctly. Strange! Maybe a `git fetch` will correct this.)

**Comment by pilnikov** [comment]
![image](https://user-images.githubusercontent.com/25922873/48932514-390cd600-ef1e-11e8-92cf-2cc7b6a0a8f4.png)

**Comment by projectgus** [comment]
Everything looks 100% correct now (both binary and version)! Are you experiencing any more issues with ESP-IDF?
