### ISSUE TITLE
[TW#28642] pthread_create does not correctly set stack size

### ISSUE THREAD

**Issue by bpietsch** [espressif/esp-idf#3015]
The implementation of pthread_create calls xTaskCreatePinnedToCore, passing in the stack size obtained from either pthread_attr_setstacksize or the esp_pthread_cfg_t. While the units of esp_pthread_cfg_t are not documented, they can be assumed to match that of pthread_attr_setstacksize, which is in bytes. The stack size passed to xTaskCreatePinnedToCore, however is documented to be in words, and so the stack size allocated is going to be 4x larger than expected, wasting significant memory.

**Comment by igrr** [comment]
Technically we should indeed divide by sizeof(portSTACK_TYPE), but that happens to be 1 (see https://github.com/espressif/esp-idf/blob/master/components/freertos/include/freertos/portmacro.h).

Documentation of xTaskCreatePinnedToCore has recently been updated to mention bytes rather than words:

> The size of the task stack specified as the number of
 * bytes. Note that this differs from vanilla FreeRTOS.
