### ISSUE TITLE
TAG V3.1 - esp_wifi_scan_start() in STA mode (IDFGH-619)

### ISSUE THREAD

**Issue by caipiblack** [espressif/esp-idf#3044]
## Environment
* Development Kit:      self made
* Module or chip used:  ESP32-WROOM-32
* IDF version:  v3.1 (tag)
* Build System:         CMake
* Compiler version: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-73-ge28a011) 5.2.0
* Operating System:     Linux
* Power Supply:         external 5V

## Problem Description

When we call esp_wifi_scan_start() in STA mode (connected to an acces point) we get this error:

`W (167973) wifi: Now is connecting, user scan invalid now!`

The result of esp_wifi_scan_start() is **ESP_ERR_WIFI_TIMEOUT**

The WiFi mode is: **WIFI_MODE_STA**

### Expected Behaviour
The wifi scan must be started

### Actual Behaviour
The wifi scan is not started and it returns the errors on the description

## Questions
Is it possible to use this functions in STA mode (connected to an AP) ?

**Comment by liuzfesp** [comment]
Hi @caipiblack, ESP32 supports two kinds of scan: the connecting scan which is triggered by esp_wifi_connect() and the user scan which is triggered by esp_wifi_scan_start(). The connecting scan has higher priority than the user scan, in other words, the esp_wifi_scan_start() will fail if the station now is connecting to the AP and following log will be displayed:

> W (167973) wifi: Now is connecting, user scan invalid now!

So it's expected behavior. 

The most simple way to handle this cause is to delay sometime and call esp_wifi_scan_start() again. However this method doesn't make sense in following scenario:

1.  esp_wifi_connect() is called and ESP32 station is connecting to an non-exist AP.
2. WiFi disconnected event is raised because the AP is not found, the WiFi event handler simply calls esp_wifi_connect() to reconnect the non-exist AP.
3. step 1/2 is repeated again and again.
4. esp_wifi_scan_start() is called.

If this is your case, you need to call esp_wifi_disconnect() to stop WiFi connection before esp_wifi_scan_start() is called, otherwise, esp_wifi_scan_start() will always fails.

For the return value ESP_ERR_WIFI_TIMEOUT, **I think it's not accurate,** we need to modify it, maybe it's better to return ESP_ERR_WIFI_FAIL etc.

You can refer to: [wifi_doc](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/wifi.html#scan-when-wi-fi-is-connecting) for more info about scan.

BTW, are you use the block scan: esp_wifi_scan_start(config, true)?

**Comment by Alvin1Zhang** [comment]
@caipiblack Hi, would you help share if any updates for the issue? @liuzfesp how is the modification of **return ESP_ERR_WIFI_FAIL etc**? Thanks.

**Comment by Alvin1Zhang** [comment]
@caipiblack Thanks for reporting the issue. Would you please help share if any updates for the issue? Has your issue been fixed? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, the fix is available at https://github.com/espressif/esp-idf/commit/c05a39de0280f896d7fcd7a8852d7e760e850393, feel free to reopen if the issue still happens. Thanks.
