### ISSUE TITLE
Changing timezone with setenv() causes memory leaks (with workaround) (IDFGH-620)

### ISSUE THREAD

**Issue by lszlfrng** [espressif/esp-idf#3046]
## Environment

- Development Kit:      ESP32-DevKitC
- Module or chip used: ESP32-WROOM-32D
- IDF version: v3.1.2
- Build System: Make
- Compiler version: 1.22.0-80-g6c4433a
- Operating System:  Linux
- Power Supply:  external 3.3V

Referring to the issue [#2450 from arduino-esp32](https://github.com/espressif/arduino-esp32/issues/2450) 

## Problem Description

In my project I have to change the timezone frequently. For this I use the time.h setenv("TZ","timezone",1) ).
When the length of the time zone value **increases** the free heap will be **smaller** and smaller.

### Code: 

```c++
void app_main() {
	uint32_t h = 0;
	uint32_t h0 = esp_get_free_heap_size();

	for (;;) {
		h = esp_get_free_heap_size();
		setenv("TZ", "GMT2GMT2", 1);
		printf("Heap GMT2:  lost:%5u total lost:%5d\n", h - esp_get_free_heap_size(), h0 - esp_get_free_heap_size());
		h = esp_get_free_heap_size();
		setenv("TZ", "GMT-2GMT-2", 1);
		printf("Heap GMT-2: lost:%5u total lost:%5d\n", h - esp_get_free_heap_size(), h0 - esp_get_free_heap_size());
	}
}
```

### Logs:

```
Heap GMT2:  lost:    0 total lost:  400
Heap GMT-2: lost:   20 total lost:  420
Heap GMT2:  lost:    0 total lost:  420
Heap GMT-2: lost:   20 total lost:  440
Heap GMT2:  lost:    0 total lost:  440
Heap GMT-2: lost:   20 total lost:  460
Heap GMT2:  lost:    0 total lost:  460
Heap GMT-2: lost:   20 total lost:  480
Heap GMT2:  lost:    0 total lost:  480
Heap GMT-2: lost:   20 total lost:  500
Heap GMT2:  lost:    0 total lost:  500
Heap GMT-2: lost:   20 total lost:  520
Heap GMT2:  lost:    0 total lost:  520
```

### Workaround

Keep the "TZ" environment variable length fixed. Example:

```
	setenv("TZ", "GMT2GMT2  ", 1);
....
	setenv("TZ", "GMT-2GMT-2", 1);
```

#### Disadvantage

Not easy to hold the length of the timezone if you have to use the Daylight Saving Time (DST, summer time).
Based on actual environment value you can padding the new value with whitespace.

```
	setenv("TZ", "CET-1CEST,M3.5.0/2,M10.5.0/3", 1);
	setenv("TZ", "GMT0                        ", 1);
```

### Question

Is there any core solution to handle the UTC and local time bidirectional conversation?

**Comment by igrr** [comment]
Hi @lszlfrng, sorry for replying so late.

This was recently discussed on the newlib mailing list, see https://sourceware.org/ml/newlib/2018/msg00304.html and the follow-up messages.

As I understand, newlib deliberately implements `setenv` this way, and the suggested workaround to avoid a leak (https://sourceware.org/ml/newlib/2018/msg00309.html) is to call `setenv` with sufficiently long value first, then call `getenv` to obtain the pointer allocated for the value. To modify the value, modify that pointer, instead of calling `setenv` again. Another option is to rewrite the code to use `putenv`, see other replies in the same thread.

I'm going to close this IDF issue, please feel free to discuss this further on the newlib mailing list.
