### ISSUE TITLE
ESP32R0 workaround is not Windows specific

### ISSUE THREAD

**Issue by grisevg** [espressif/esp-idf#305]
Hey guys, 

"Reset with ESP32R0 Windows workaround" fixed for me the board not reseting into download mode, even though I'm on macOS running IDF on Ubuntu 14.04 in Virtualbox.
The issue was with "ESP32_Core_board_V2".

It took me a while to try it, as I was mislead by "Windows" in the name. To save others same headache, it would be better to remove "Windows" text from the option.

As far as I understand, the problem is with cp210x drivers, windows or mac.

**Comment by projectgus** [comment]
Thanks @grisevg for reporting this. If you're passing through the USB device (rather than the serial port) to VirtualBox then the problem is probably to do with USB latency introduced between VirtualBox Linux guest and the host OS, rather than the cp210x mac drivers (which aren't being used in that case, and our macOS developers don't report this problem when running natively on macOS).

However your point is well taken that there are situations where this problem is triggered without being on Windows. We'll update the labelling for this option, thanks for pointing it out. (We're also going to change the default esptool behaviour so it should work on the default settings, by merging Marty's PR espressif/esptool#172).
