### ISSUE TITLE
file_serving html always ? on the end

### ISSUE THREAD

**Issue by arnold-b** [espressif/esp-idf#3156]
Hi,

please give me a hint. on every request i have ? on the end.

HTML: <form action='sy.html' method='get'><button class="button">System</button></form>
i know it´s not your Problem. if i put the url directly then ist ok

result: ESP
I (346874) file_server: /sy.html?

E (347264) file_server: Failed to stat file : /spiffs/sy.html?
W (347264) httpd_txrx: httpd_resp_send_err: 404 Not Found - File does not exist
example file_serving from idf3.3
thanks

**Comment by projectgus** [comment]
Hi @arnold-b ,

Sorry, but there isn't enough information here to help you. Are you using the ESP-IDF HTTP server? How are you sending the HTTP request to the server? Are you using an example, or custom code for the HTTP server handlers? What does "put the URL directly" mean?

If this is a question rather than a bug report, the best place to ask it is the https://esp32.com/ forum.
