### ISSUE TITLE
Wierdly encoded characters when receiving data

### ISSUE THREAD

**Issue by feelfreelinux** [espressif/esp-idf#324]
Hi! I'm writing IRC bouncer on esp32. Implemented basic functionality, but when I receive data, I'm randomly getting characters replaced like `ToggleSwitchWidŽŽû?gû?`, ` cherryh.freenode.net @û?Í352` - Hmm, maybe its something with this buffer to string operation? Thanks! 
https://gist.github.com/feelfreelinux/883950670b7b95b3491c05cbda0f463e

**Comment by projectgus** [comment]
Hi,

I can't tell you exactly what the problem might be, but:
* When you call recv(), you pass the full length of the (zeroed) buffer. Then you initialise a C++ string from this buffer. This will work as long as the number of bytes read is less than the size of the buffer, so there is still a byte left to null-terminate the string. Otherwise, it will overflow the buffer and you'll get garbage strings (which may be where the line noise you're seeing is coming from).
* When you call recv(), you should consider the possibility that the TCP stream is fragmented and you won't get a full line of data each time. A line may be split in two packets, so you only read half. Or it may be combined with multiple lines into a single packet. You probably need an extra layer of buffering to read from the socket and fill a buffer until you see a newline, so you can split the data received into lines that way.

This feels more like an application programming question than a bug in esp-idf. As such, please consider posting on the http://esp32.com/ forum or another coding community. Feel free to reopen if you think there's also a framework bug here.
