### ISSUE TITLE
Link to documentation of esp-idf 3.3 beta 3 is not working. (IDFGH-1188)

### ISSUE THREAD

**Issue by Zeni241** [espressif/esp-idf#3498]
Below link to documentation of esp-idf 3.3 beta 3  is not working.

 https://docs.espressif.com/projects/esp-idf/en/v3.3-beta3/

**Comment by projectgus** [comment]
Hi @Zeni241,

Thanks for the heads-up. ReadTheDocs (who we use) updated their version of breathe and it broke our builds. We'll have this fixed before the v3.3 final release, but the beta3 docs will probably not build.

I'll try to provide a working link to v3.3 docs ASAP.

Angus

**Comment by Zeni241** [comment]
Thanks

**Comment by projectgus** [comment]
Reopening until we have 3.3 docs building again.

**Comment by Zeni241** [comment]
BTW when can we expect release of stable 3.3? Just curious :) .

**Comment by projectgus** [comment]
Hi @Zeni241 ,

Sorry for the slow reply. Final release was blocked on one high severity Bluetooth related issue, but it should be next week at the latest.

In the meantime you can view the 3.3 prerelease docs here:
https://docs.espressif.com/projects/esp-idf/en/release-v3.3/

(Ignore "beta1" in the description, this is a bug because the b3.3-beta3 tag was not created as an annotated tag.)

**Comment by Zeni241** [comment]
Thank

**Comment by projectgus** [comment]
Thanks again for your patience updating this issue.

v3.3-rc is the release candidate for v3.3 and the docs can be found here:
https://docs.espressif.com/projects/esp-idf/en/v3.3-rc/

(Note the above link will probably stop working once the v3.3 final release is made.)

**Comment by Zeni241** [comment]
Thanks for update.
