### ISSUE TITLE
Expose C++ NVS API (IDFGH-1242)

### ISSUE THREAD

**Issue by mill1000** [espressif/esp-idf#3540]
- IDF version: v3.1.2
- Build System: Make

This is a feature request. The NVS system can only be accessed via a C-friendly API but is primarily written in C++. It would be nice if the C++ API was exposed so we could access the templated nvs_get and nvs_set functions.

Currently I am writing a templated wrapper around the NVS system and the C API is forcing me to manually expand (via overloads) set and get operation based on my template type. Only for the NVS API to collapse it back down to its internal nvs_set and nvs_get.

**Comment by igrr** [comment]
Hi @mill1000, thank you for the feature request. Will keep it in mind, but this will likely not be implemented short-term, since some of the NVS logic is located in the C wrapper, rather than in C++ classes. This includes API locking with mutexes, finding and creating namespaces, and partitions support. Another feature coming soon, iteration over NVS keys, will also partially be implemented in the C wrapper. So it will require some work to provide an equivalent C++ interface.
