### ISSUE TITLE
我想问一下，怎么读出esp32模块里面的固件呢？ (IDFGH-1404)

### ISSUE THREAD

**Issue by zouzhe1** [espressif/esp-idf#3682]
我想问一下，怎么读出esp32模块里面的固件呢？
模块里这一版代码丢失，但是模块里面的还有用，我想读出来，发给同事测试
不知道怎么能读取出来bin文件

**Comment by Alvin1Zhang** [comment]
@zouzhe1 Thanks for reporting this. **Please do not ignore the GitHub issue posting guidelines.**

1. If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead.

2. If you have a "how to" question and not a suspected/confirmed bug, please post it to the [forum](sp32.com) instead.

Thanks.
