### ISSUE TITLE
Why the menuconfig 'store ble mesh node configuration persistently' dose not work? (IDFGH-1546)

### ISSUE THREAD

**Issue by YuriChen1028** [espressif/esp-idf#3808]
I have enabled the function 'component config -> Ble mesh support -> store ble mesh node configuration persistently' in the menuconfig, but when i turn off the devkit board and turn on again,  the nrf Mesh app remind me provision again.

**Comment by YuriChen1028** [comment]
the SDK version is : mesh-v0.6.1

**Comment by WCCWCC** [comment]
Hi YuriChen，

1.  nrf mesh app 配置设备入网并进行控制。
2.  设备硬件复位， nrf mesh app 可以直接和设备建立连接。你需要点击右上角的 connect 。如下图所示：
 
![图片](https://user-images.githubusercontent.com/47855814/63662356-c56f6080-c7f0-11e9-98e6-ea91fb427246.png)

![图片](https://user-images.githubusercontent.com/47855814/63662350-c1434300-c7f0-11e9-98af-a934a7425a54.png)

**Comment by Alvin1Zhang** [comment]
@YuriChen1028 Thanks for reporting. Would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.

**Comment by arjndr** [comment]
@Alvin1Zhang this issue is similar to #8942 

Enabling the "Store BLE Mesh configuration persistently" option seems to do nothing, whenever the device restarts I need to reprovision it!

<img width="546" alt="image" src="https://github.com/espressif/esp-idf/assets/20661194/a1a3e75d-1d3d-4690-8719-176cea56bda3">
