### ISSUE TITLE
Unable to call `gpio_init` from Deepsleep Wake Stub. (IDFGH-1559)

### ISSUE THREAD

**Issue by nevercast** [espressif/esp-idf#3820]
When I try to call `gpio_init()` from a Deepsleep Wake Stub (So that I may use the `gpio_*` functions in ROM), I get a linker error stating that `gpio_init()` in `rom/gpio.h` is undefined. I believe this is because it is commented out from the linker script (below).

https://github.com/espressif/esp-idf/blob/master/components/esp_rom/esp32/ld/esp32.rom.ld#L1458-L1462

Please provide a way forward. I understand that `gpio_init` must not be called from the application, but I would like it call it from my deepsleep wake stub. I can uncomment `gpio_init` in the linker script for my application, however a better solution may be needed for the community.

Thanks
Josh.

**Comment by projectgus** [comment]
Hi @nevercast ,

Thanks for this bug report. Sorry I forgot about the commented linker script entries when I originally suggested this approach.

For now, as a workaround you can uncomment in the linker script and use this - provided the code is only used from the wake stub it will be OK.

If these functions are called from a running app (after wake stub is finished and the rest of the system has booted), then the ROM is hard-coded to use some RAM addresses which are also reclaimed for IDF app use. Which is why they are commented out - if they're called from the main app, it will cause memory corruption. We originally expected people may call these functions from the bootloader, which is why they are still there in the headers at all (bootloader uses a different linker script).

The difficulty here is that, unlike the bootloader, the wake stub is linked as part of the main application - just in a special section, which allows sharing of some resources between the wake stub and the main app provided this is done carefully.

Maybe there is some solution where we do a partial link of wake stub code (which can use these ROM functions safely) and then link it into the main app in a second pass.

We'll look into this and update the issue if there's a fix available.
