### ISSUE TITLE
Missing posts (IDFGH-1577)

### ISSUE THREAD

**Issue by jhinklejr** [espressif/esp-idf#3837]
I posted two questions yesterday regarding I2S and Camera.

Both posts are gone - not in open - not in closed.

What happened to them?

Are questions not to be asked on this site and they were deleted?

Please explain.

**Comment by igrr** [comment]
The issues have been moved to the esp32-camera project (https://github.com/espressif/esp32-camera/issues/52, https://github.com/espressif/esp32-camera/issues/53), and they are still available at the original URLs, automatically redirecting to the new ones. They were moved because they are out of the scope of this repository. When opening issues in this repository, please observe the issue template. Questions about the TRM can be asked on the esp32.com forum in the Documentation Requests section, and camera related issues can be posted in the esp32-camera repository. Thanks.
