### ISSUE TITLE
Error while installing ESP-IDF for Windows 10

### ISSUE THREAD

**Issue by patelshruti** [espressif/esp-idf#4035]
Hi,
I need to develop an application using  esp32  for BLE (scan,notify,read/write) functionality using ESP-IDF.

I have referred following link for software setup, using the same downloaded file, I am not able to install ESP-IDF. It shows "installation has failed with exit code 129"
https://dl.espressif.com/dl/esp-idf-tools-setup-2.0.exe

I am attaching error log file generated during installation.
Error log:
[Setup Log 2019-09-09 #005.txt](https://github.com/espressif/esp-idf/files/3589339/Setup.Log.2019-09-09.005.txt)
Please help.

Thanks & Regards

**Comment by patelshruti** [comment]
[Setup Log 2019-09-09 #005.txt](https://github.com/espressif/esp-idf/files/3589329/Setup.Log.2019-09-09.005.txt)

**Comment by Alvin1Zhang** [comment]
@patelshruti Thanks for reporting, we will look into it. Thanks.

**Comment by igrr** [comment]
Hi @patelshruti, the issue happens because the name of the destination directory contains spaces (`C:\Users\INEshrp\OneDrive - OneVirtualOffice\Desktop\esp-idf-5`). This was fixed in the more recent versions of the installer, https://dl.espressif.com/dl/esp-idf-tools-setup-2.3.exe.
However keep in mind that ESP-IDF build system currently doesn't support spaces in $IDF_PATH or the project path. Therefore you need to choose a directory without spaces in its path, when installing IDF. The recent versions of the installer will check for this during the selection of destination directory.
