### ISSUE TITLE
Esp-idf++ (IDFGH-1831)

### ISSUE THREAD

**Issue by howroyd** [espressif/esp-idf#4040]
I've started working on a home project on a few esp32-wroom-32 chips. Using platformio in VS Code and ESP-IDF v3.3. Using freeRTOS and c++.
Not found much on the esp in the above situation. Particularly later builds of the IDF in pip, and c++.
Thought I'd do my but by asking if there's any interest from others? If so I'll happily share my code on GitHub for others!

**Comment by projectgus** [comment]
Hi @howroyd!

Thanks for letting us know about your progress. We have some internal plans for better C++ APIs for some of the ESP-IDF functions, as I agree these can be lacking, and also for official VS Code support (although using ESP-IDF directly, we don't use platform.io although we think it's a great project.) We should be able to announce something publicly on these soon.

It sounds like what you're working on may be of much interest to some members of the community though, and developers may find it very helpful. Suggest that rather than discussing here on the IDF issue tracker, which is largely for ESP-IDF bugs and feature requests, the best place to discuss your project and gather community interest would be the ESP32 forums: https://esp32.com/

Would you consider making a post over there? I think it could be quite popular.
