### ISSUE TITLE
About using each type of SPI transaction for each slave (IDFGH-1850)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#4057]
[This](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/spi_master.html#notes-to-send-mixed-transactions-to-the-same-device) refers to doing the 2 types of transactions to the same device. However, I'm doing one one polling transaction for my NFC slave, and interrupt transaction for my Ethernet slave, and [this](https://github.com/espressif/esp-idf/blob/9f145ff165099f32b92b7ee022a1debc5f0a583d/components/driver/spi_master.c#L959) assertion is triggering quite frequently during stress tests, despite the transactions going through a mutex for each of the 2 devices (each mutex controlling access to each SPI slave).
After reading [this](https://github.com/espressif/esp-idf/issues/3200), since I'm already using the mutexes, the question is: what are the possible reasons to trigger this assert?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks. @KaeLL

**Comment by ginkgm** [comment]
An SPI device has a pair of queues, one to send trans_desc to ISR and the other returning trans_desc from ISR. The queues guarantee the executation order, which means, trans first queued will get sent first, and return from the queue first.

When you send my spi_transmit, it assumes both queues are empty, and send one. It wait for the trans be executed and return from the queue. If the returned desc is not the one it sent, assertion failure happens.

Two possible causes:
1. You are using `spi_device_queue` + `spi_device_get_trans_result` and `spi_device_transmit` to the same device at the same time. You should use `spi_device_get_trans_result` to get all queued descs before other queueing/transmit. Otherwise they will get unexpected desc.

2. You havn't apply for enough [queue size ](https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/peripherals/spi_master.html#_CPPv4N29spi_device_interface_config_t10queue_sizeE) when using `spi_device_queue` + `spi_device_get_trans_result`. In this case, you may queueing too much desc before handle them from the returning queue. You will lose the returning descs when the returning queue is overflow.

**Comment by KaeLL** [comment]
Ok. Looks like it it could be due to the 2nd reason. But wouldn't a bigger queue just delay the issue? If transactions are being queued in faster than they are processed and queued out, the assert is bound to trigger at some point.

**Comment by ginkgm** [comment]
@KaeLL The queue means, how many in-flight trans you can have in maximum. You still have to handle the return trans before queueing new. For example, you can do like this:
```
queue A
queue B
queue C
(... do something else in the same task, maybe prepare for new transactions)
get_res A
get_res B
get_res C

queue D
queue E
queue F
...
```

Then you can do something else (rather than blocked) before desc C is done. In this case, the queue size should be no less than 3.

**Comment by ginkgm** [comment]
@KaeLL since polling transactions are done synchronizedly, they don't need the queue, the queue size doesn't take effect to it.

**Comment by KaeLL** [comment]
> @KaeLL since polling transactions are done synchronizedly, they don't need the queue, the queue size doesn't take effect to it. (also not counted as one).

So there should be a way to specify to IDF that only polling transaction will be used, therefore there's no need for the 2 queues, because as it stands, it creates them anyway, and if you let 0 be the value of the queue size, the [queue creation assert](https://github.com/espressif/esp-idf/blob/96b96ae244f360c84b71c8c3670e24a1186e9844/components/freertos/queue.c#L378) triggers.

> But if you use polling transaction, please use get_result/transmit to make sure the previous interrupt transactions are done.

I use only the wrapper functions to make transactions (spi_device_transmit/spi_device_polling_transmit). Does that work?
