### ISSUE TITLE
why is the ethernet component in the new version 4.x missing? (IDFGH-2013)

### ISSUE THREAD

**Issue by Mosbeard** [espressif/esp-idf#4208]
## Problem Description

Hello,
why is the ethernet component in the new version 4.x missing? 
The CMakeLists file of the arduino-esp32 project is dependent on this ethernet component, see line 206 and without CMake can't resolve it:
[CMakeLists.txt](https://github.com/espressif/esp-idf/files/3737784/CMakeLists.txt)

I tried to copy the ethernet component from version 3.2., then cmake can resolve the component, but then i get compiler errors.
Do someone know a good way to resolve this issue?
I could go back to version 3.2, but then the import of 3rd party cmake projects doesn´t work really good.
I think when i know how the component was replaced i could adjust the CMakeLists file.

**Comment by suda-morris** [comment]
Hi @Mosbeard 
Sorry for any inconvenience. 
We started a new Ethernet driver since 4.0, and removed the previous driver. All Ethernet related examples are updated to the new APIs in ESP-IDF too. 
The new component has been renamed to [esp-eth](https://github.com/espressif/esp-idf/tree/master/components/esp_eth).
The reason we update the Ethernet driver is to make it more flexible and extensible. For now, `esp-eth` component can not only support ESP32 internal EMAC, but also support SPI Ethernet driver (e.g. DM9051), with almost the same APIs.

**Comment by Mosbeard** [comment]
Hello @suda-morris 
thanks for the advice. I close the issue.
