### ISSUE TITLE
esp (IDFGH-2223)

### ISSUE THREAD

**Issue by reshma26p** [espressif/esp-idf#4372]
hello...
what data should be erase by make erase_flash command.
i gave command make erase_flash and then make flash the led blink code then led not getting blink but on terminal gives response as led on led off

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by reshma26p** [comment]
what is next step if i erased flash using command make erase_flash

**Comment by suda-morris** [comment]
make sure your board does have an LED and connect to the right GPIO you configured in your code :)

**Comment by reshma26p** [comment]
@Alvin1Zhang yes i am using wroom 32 board and i checked led and gpio

**Comment by Dazza0** [comment]
@reshma26p 
No, it should not affect the LED. `make erase_flash` simply erases the contents of the flash chip on the board. Since you are calling `make flash` to reflash the contents of the chip afterwards, the program should still run.

We need more information in order to help you:
* What GPIO are you using to drive the LED?
* What type of Wroom 32 Board are you using (e.g., DevKitC)? Is it manufactured by Espressif or by a third party?

**Comment by Dazza0** [comment]
@reshma26p Do you have any updates on this issue?

**Comment by Alvin1Zhang** [comment]
@reshma26p Thanks for reporting. Would you please help share if any updates for this issue? Thanks.

**Comment by projectgus** [comment]
Closing due to lack of updates.
