### ISSUE TITLE
cmake menuconfig missing entries (IDFGH-2251)

### ISSUE THREAD

**Issue by paoloach** [espressif/esp-idf#4396]
## Environment

- Development Kit:      it doesn't matter
- Kit version:  it doesn't matter
- Module or chip used:   it doesn't matter
- IDF version: v4.1-dev-1086-g93a8603c5
- Build System:    CMake
- Compiler version: crosstool-NG esp32-2019r1-rc2) 8.2.0
- Operating System:     Linux
- Power Supply:        it doesn't matter

## Problem Description

Running menuconfig from the cmake build folder, the Serial Flasher config miss the first 3 entries:

- default serial port
- default baud rate
- use compressed upload

### Expected Behavior
These 3 entries shuold be present

### Actual Behavior
These 3 entries are not present
### Steps to repropduce

got into the folder examples/get-started/hello_world
mkdir build
cd build
cmake ../
make menuconfig
select the voice "Serial Flasher config"

**Comment by projectgus** [comment]
Hi @paoloach ,

When we moved from GNU Make to CMake, the serial flasher settings were removed from the project configuration. It was a frequent source of (legitimate) complaints that changing serial port settings should not cause the entire project to rebuild.

The Getting Started guide explains how to set the serial port if working with idf.py:
https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#step-9-flash-onto-the-device

If not using idf.py then you can set the serial port details via environment variables ESPPORT & ESPBAUD:
https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#flashing-with-ninja-or-make

There is a minor bug in the CMake build system though, which is that the "Compressed Upload" config option is still being used to generate the flashing commands, even though it's disabled in CMake. Will fix ASAP (this option was removed because there is not really any reason to disable compressed uploads in normal operation).

**Comment by paoloach** [comment]
Hi @projectgus,

thank for the explanations.

So, I think I can close this issue.

Regards,
Paolo
