### ISSUE TITLE
Questions about the esptool.py (IDFGH-2261)

### ISSUE THREAD

**Issue by rolandma** [espressif/esp-idf#4404]
I am working on zephyr project and when flash, using the esptool.py, I always get this error that the segments are bigger than 16, which indicates a linker script error somewhere. Can anybody give me some hints about this error? Or which linker script should I use? I'm using a ESP32-wroom-32D dev kit, and the only sample on zephyr project that will run is hello-world.

**Comment by projectgus** [comment]
Hi @rolandma ,

As I explained to you yesterday when you posted the same question on esp32.com, esptool.py isn't part of ESP-IDF and Zephyr isn't part of ESP-IDF. Zephyr project uses its own linker script, build system, etc. which is totally different to the ESP-IDF ones:
https://esp32.com/viewtopic.php?f=13&t=13285

So this is not an issue in ESP-IDF.

I would repeat the advice I gave you already on the forum, which is to try and report this issue to Zephyr maintainers and see if they can help.

If you're still stuck then please reply on the forum (not here) and attach the .ld linker script file and the hello_world ELF file which was built from Zephyr. I'll take a look at these, and try to help you on the forum.

It would also be helpful to get the full command line and complete output from esptool.py, rather than a vague description.
