### ISSUE TITLE
Issue with Finishing ESP-IDF Installation on Windows 7 64-bit (IDFGH-2276)

### ISSUE THREAD

**Issue by Stoi723** [espressif/esp-idf#4417]
Installation on Windows 7 64-bit never end when running :

Running command: powershell -ExecutionPolicy ByPass -File "C:\Users\s\.espressif\dist\tools_WD_excl.ps1" -AddExclPath "C:\Users\s\.espressif\*.exe"

![issue](https://user-images.githubusercontent.com/58312299/69832855-2ae04c80-1239-11ea-8d7f-0f5cd559247c.jpg)

**Comment by squonk11** [comment]
I had the same problem. I simply solved it by not ticking the box for setting the Windows Defender exceptions. This can be done in the last dialog box before statring the installation.

**Comment by igrr** [comment]
Please try the latest version of the installer (v2.2), it should fix the issue.

**Comment by Alvin1Zhang** [comment]
@Stoi723 Thanks for reporting. Would you please help check whether your issue has been fixed by trying the latest version of the installer (v2.2)? Thanks.

**Comment by pacucha42** [comment]
This issue is solved by the latest fix for https://github.com/espressif/esp-idf/issues/4225 (to be released soon). It's quite likely you don't have Windows Defender cmdlets installed (can be checked by running **Get-Command -Module Defender**  from PS cmdline, see the linked issue), the latest fix does the detection for you and disables whole WD function.
Sorry for inconvenience

**Comment by Alvin1Zhang** [comment]
@Stoi723 Thanks for reporting. Would you please help if any updates for the issue? Has your issue been resolved? Thanks.

**Comment by georgik** [comment]
@squonk11 We updated ESP-IDF Tools Windows Installer. The checkbox was moved to the last screen of the installation process because it also requires elevation of privileges. Having the checkbox on the last screen helps to avoid the problem with the timeout of UAC. 

We also added an Antivirus check and the checkbox is only available when Windows Defender is detected.

Please, test the latest installer: https://dl.espressif.com/dl/esp-idf/

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
