### ISSUE TITLE
ESp32 bluetooth device can not be connected or discoveried (IDFGH-2285)

### ISSUE THREAD

**Issue by c-hamster** [espressif/esp-idf#4426]
Hi  all!

I compile the demo project "esp-idf/examples/bluetooth/bluedroid/ble/ble_hid_device_demo" and download it .

there are two problems.

the first problem!

my cellphone (huawei honor 10) can discovery the "HID" device and pairs well .but when  I change to it to honor6(MIUI), the "HID" device can't even be discovered.  I also try this on Iphone7 .the result is the same . bluetooth host can not find the ESP32's broadcast。

the second problem:
when I try to connect esp32 device from PC.  PC can find "HID" device . then the driver automatic installed . finally the driver occur error !  

errror code as below:

符合 Bluetooth 低能耗 GATT 的 HID 设备

该设备无法启动。 (代码 10)

发送无效的参数给服务或功能。

HOW TO SOLVE THIS TWO QUESTION!!!! THANKS A LOT!

ps:   in order to avoid error ,I Shield the  xTaskCreate(&hid_demo_task, "hid_task", 2048, NULL, 5, NULL);  esp32 will not send VOLUME_UP and VOLUME_DOWN when paired.

**Comment by xiewenxiang** [comment]
The first Problem  -  Some phones cannot scan HID broadcast package


1. Firstly, make sure that the ESP32 are sending broadcast packages. The easiest way for customers is to download bluetooth debugging App, the android phone download NRF connect and the IOS phone download LightBlue.

2. If ESP32 is actually sending the broadcast package , it may be because the mobile phone system  do not display BLE device.


The second Problem  -  Driver installation error


1. This problem probably because of the macro definition 'SUPPORT_REPORT_VENDOR'

**Comment by Alvin1Zhang** [comment]
@c-hamster Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
