### ISSUE TITLE
esp-idf可以用来开发ESP8266芯片吗? (IDFGH-2329)

### ISSUE THREAD

**Issue by hscxg** [espressif/esp-idf#4463]
请问一下: 

esp-idf是否只是用来开发ESP32芯片, 能否用来开发ESP8266芯片?

如果要开发ESP8266芯片, 是否需下载另外的开发包, 如: ESP8266_RTOS_SDK-3.2

ESP8266芯片的SDK包新老版本配置都不一样,  搞得迷糊得很. 请指点, 谢谢!

**Comment by igrr** [comment]
Hi @hscxg,
Currently ESP-IDF doesn't have support for ESP8266. This may change in the future, but I can't give you a firm timeline when this might happen. For now, to develop for the ESP8266 you need to use the [ESP8266_RTOS_SDK](https://github.com/espressif/esp8266_rtos_sdk).

The ESP8266 RTOS SDK has been significantly refactored since version 2.0, more information on this here: https://github.com/espressif/esp8266_rtos_sdk#roadmap. If you find something in the documentation of the ESP8266 RTOS SDK which is confusing, please open an issue at https://github.com/espressif/esp8266_rtos_sdk/issues.
