### ISSUE TITLE
Missing extern "C" in "components/esp_wifi/include/esp_wifi_default.h" (IDFGH-2370)

### ISSUE THREAD

**Issue by svenbieg** [espressif/esp-idf#4497]
I am calling esp_netif_create_default_wifi_ap and esp_netif_create_default_wifi_sta from a cpp-file. Usually there is an #ifdef __cplusplus extern "C" statement at the beginning of the header.

**Comment by svenbieg** [comment]
Same as IDFGH-2241

**Comment by anderstogern** [comment]
It seems this issue is still around!

With latest master the `extern C` deifnition is still missing. Adding it manually fixes the problem and compilation completes successfully.

#4389 focuses on the order of the initializers and refers to this as a separate issue, so I think that this issue should be reopened.

**Comment by Alvin1Zhang** [comment]
@svenbieg @anderstogern Thanks for reporting, please help check whether the issue still happens at your side, thanks.

**Comment by svenbieg** [comment]
It's working now, thank You!

**Comment by Alvin1Zhang** [comment]
@svenbieg Thanks for the updates.
