### ISSUE TITLE
dns provision in udp_client (IDFGH-2813)

### ISSUE THREAD

**Issue by sumit809** [espressif/esp-idf#4875]
So, there is only one option of providing IPv4 address in Example Configuration in menuconfig. As the IP may change, can there be an option to enter DNS directly?

**Comment by david-cermak** [comment]
Hi @sumit809 

Do you mean to use a host name instead of IP in examples? Yes it is possible, of course, but the socket examples are meant so demonstrate very simple socket manipulations and adding a dns resolver might add unnecessary complexity.  Moreover one can check other examples that connect to hostname rather than ip address. Linking the `esp-tls` component which is used by many other protocol examples as a reference: https://github.com/espressif/esp-idf/blob/master/components/esp-tls/esp_tls.c#L128

**Comment by sumit809** [comment]
Okay @david-cermak !
I will look into it!
Thanks...! :)
