### ISSUE TITLE
HFP disconnects incoming call when disconnected (IDFGH-2992)

### ISSUE THREAD

**Issue by shimomu2** [espressif/esp-idf#5024]
## Environment
- Development Kit: EVK-NINA-W102-00
- Module or chip used:  NINA-W102
- IDF version:  4.0
- Build System: Make
- Compiler version: xtensa-esp32-elf-gcc 8.2.0
- Operating System: Linux
- Using an IDE:No
- Power Supply:USB

## Problem Description

If you connect to the smartphone with HFP and disconnect the incoming call from esp32, the connection will be disconnected.

### Steps to reproduce

Follow BTstack instructions for ESP32: https://github.com/bluekitchen/btstack/blob/master/port/esp32/README.md

Switch to btstack/port/esp32/example/hfp_hf_demo

start demo.
After connecting to the device, disconnect the call to the device

## Debug Logs
[snooplog.zip](https://github.com/espressif/esp-idf/files/4401740/snooplog.zip)

**Comment by AbnerFederer** [comment]
My test is good, so may you can provide more info like which phone.

**Comment by AbnerFederer** [comment]
Hi, @shimomu2 

I have reviewed the air log you provided.
But I haven't seen any LMP log, can you support the complete log?
Or I would think the two devices are not really connected.

Thanks
Abner

**Comment by shimomu2** [comment]
Here, we are checking with Galaxy S10,
Even with the same Galaxy S10, there were some cases where the phenomenon occurred and some did not occur.

When confirmed on different smartphones, the phenomenon did not occur.


Please check the attached airlog when the phenomenon occurs.
[airlog.zip](https://github.com/espressif/esp-idf/files/4479613/airlog.zip)

**Comment by AbnerFederer** [comment]
Hi, @shimomu2 

Have you ever compare the Bluedroid host in IDF?
I cannot reproduce your issue with Bluedroid.

Thanks
Abner

**Comment by AbnerFederer** [comment]
Hi, @shimomu2 

From the air log, I see that the initiating process of the ACL link is okay but the initiating process of the SCO link has some issues. **I don't see that SCO link has already been established.** And because of "AT+CHUP" is a string sent to the controller, so please check the host string handler. The detach may be caused by the timeout of the SCO parameter negotiation.

Thanks
Abner

**Comment by AbnerFederer** [comment]
Hi, @shimomu2 

The air log shows that the SCO connection has not been established and ESP32 initiates **LMP Response Timeout**, in the end, to disconnect with the peer device.

The disconnection comes from the LMP timeout (30 sec) rather than the error of AT+CHUP.

I will check the controller and please try Bluedroid in IDF first.

Thanks
Abner

**Comment by Wth-Esp** [comment]
Hi, @shimomu2

Any update for this issue?

Thanks
Weitianhua

**Comment by Wth-Esp** [comment]
Hi, @shimomu2 

There is a lib file for you, please try it and better scratch another air log.
[libbtdm_app.zip](https://github.com/espressif/esp-idf/files/4596783/libbtdm_app.zip)

Thanks
Weitianhua

**Comment by Wth-Esp** [comment]
Hi @shimomu2 

Any updates about this issue?

Thanks
Weitianhua

**Comment by Alvin1Zhang** [comment]
Will close due to short of feedback.
