### ISSUE TITLE
BLE_MESH proxy_client.c stack buffer overflow (IDFGH-3004)

### ISSUE THREAD

**Issue by pokerfacett** [espressif/esp-idf#5035]
INSTRUCTIONS
============
bt_mesh_proxy_client_adv_ind_recv function has buffer overflow：
![image](https://user-images.githubusercontent.com/13774458/77996178-ba207c80-735f-11ea-82df-1d55d10c24ee.png)

When I post packet as follow when bt_mesh scan:
![image](https://user-images.githubusercontent.com/13774458/77996249-da503b80-735f-11ea-8b8e-e8eadc34d4f6.png)

It could cause 8 bytes buffer overflow

and exploit first should set uuid = 0x1828 and first packet is as follow：
![image](https://user-images.githubusercontent.com/13774458/78000266-9ca2e100-7366-11ea-81bd-bf1ebfd0b448.png)

which could jump the case：BLE_MESH_DATA_UUID16_ALL，and set uuid 0x1828  as follow:

![image](https://user-images.githubusercontent.com/13774458/78000472-e8ee2100-7366-11ea-91a9-2545e4bcb65c.png)

![image](https://user-images.githubusercontent.com/13774458/78000782-6580ff80-7367-11ea-8b32-a15189b349a1.png)

Then attacker could use the buffer overflow to remote code execution

Fix Suggestion
============
```
if(buf->len <= sizeof(ctx.net_id.net_id)){
    memcpy(ctx.net_id.net_id, buf->data, buf->len);
}
```

**Comment by Alvin1Zhang** [comment]
@pokerfacett Thanks for reporting and really appreciate you bring fix suggestion, we will look into . Thanks.

**Comment by pokerfacett** [comment]
> @pokerfacett Thanks for reporting and really appreciate you bring fix suggestion, we will look into . Thanks.

Any progress？

**Comment by Campou** [comment]
Hi @pokerfacett 

Thanks, i will add a length check here.

**Comment by pokerfacett** [comment]
commit https://github.com/espressif/esp-idf/commit/fab9b944a47067024ac61e48a08945e02b924369

**Comment by projectgus** [comment]
Hi @pokerfacett,

Thanks for reporting this issue so clearly. We've analyzed the impact and although this is a buffer overflow onto the stack, it's not a security bug in any of the configurations or versions we've checked.

The reason for this is that the maximum size of the buf->len argument to memcpy that an attacker can inject is 16 bytes. Of this, 8 bytes are copied correctly to the destination buffer, one byte overflows to another field in the destination buffer, and 7 bytes overflow onto the stack.

The stack frame for the bt_mesh_proxy_client_adv_ind_recv() function is 48 bytes long (`entry a1, 48`).  `a1` is the stack pointer register. The destination structure is the only local variable stored on the stack, so the `memcpy()` call evaluates as `memcpy(a1, src buffer, 16)`. This means that although the structure on the stack overflows by up to 7 bytes, these overflow bytes are all unused bytes of this function's stack so they don't corrupt any other memory. These bytes are never read back, they might be written over if this function makes another function call.

In addition, xtensa stack frames are always 16-byte aligned so the smallest possible stack frame for this function is 16 bytes.

The attacker would need `buf->len` to be the length of the stack frame or more in order to trigger a security bug.

Regarding the other issue you've reported, thanks for this report also. We're investigating this currently and will have an update for you soon.

In future, when reporting potential security bugs please consider taking advantage of the [ESP32 Bug Bounty Program](https://esp32.com/viewtopic.php?f=10&p=7266&sid=b1e9e459e291f6aed17185dd21aed1f4).
