### ISSUE TITLE
GNU Make ESPPORT mangled (erroneous passing double quotes) (IDFGH-3103)

### ISSUE THREAD

**Issue by BrianPugh** [espressif/esp-idf#5124]
Parsing/passing `${ESPPORT}` to `esptool` in `components/esptool_py/Makefile.projbuild` broke `make monitor` and `make flash` commands in commit 2e14149bff63fe211d6d30ff0cd84c90b5fface9. `CONFIG_ESPTOOLPY_PORT` as parsed from `sdkconfig` contains leading/trailing double quotes. Placing this variable inside singlequotes means `esptool` gets the string `"MY_PORT"` instead of just `MY_PORT`. For example, it parses the erroneous `"/dev/ttyUSB0"` instead of `/dev/ttyUSB0`. What was the intention of adding the single quotes to `Makefile.projbuild`?

**Comment by projectgus** [comment]
Hi @BrianPugh,

Thanks for reporting this and giving such clear details about the problem.

> What was the intention of adding the single quotes to **Makefile.projbuild?**

Single quoting was added because it's necessary to use the port syntax `\\.\COMx` for Windows when using gdb (serial stub) and a port number higher than 16, and passing around backslashes in Make variables is a minefield without single quoting.

A fix for the problem with `CONFIG_ESPTOOLPY_PORT` is in review now and will be merged soon. In the meantime, a workaround is to the ESPPORT environment variable:

```
export ESPPORT=/dev/ttyUSB0
```

or

```
make flash ESPPORT=/dev/ttyUSB0
```

(This method also has the advantage of being able to change ports without triggering a full rebuild.)
