### ISSUE TITLE
not using the model element index in the given example (IDFGH-3308)

### ISSUE THREAD

**Issue by ankit-thealchemist** [espressif/esp-idf#5293]
https://github.com/espressif/esp-idf/blob/5e436be77f68b1ba7d2ebbefb8aeda34f6c71276/examples/bluetooth/esp_ble_mesh/ble_mesh_node/onoff_server/main/ble_mesh_demo_main.c#L125

In this example, In this function we try to find the element index, by calculating it by the address of the primary element and getting the number of count of elements regarding this model, and then comparing to the address of the destination. My question is what is the reason not to use the model element index? why did we do not directly put the 'model->element_idx' as an index rather than making it complex by calculating it manually?

**Comment by Campou** [comment]
Hi @ankit-thealchemist 

Thanks for pointing this out. Using `model->element_idx` is a better approach indeed.

Since currently as the description of `element_idx`, it is mainly for mesh stack internal usage, so we are not using it in the examples.
And maybe using the `primary_address` combined with the element number to calculate each element's unicast address, and compared with the dst of the message will be more understandable for beginners?

Thanks.
