### ISSUE TITLE
Need 128G/256G TF Support (IDFGH-3426)

### ISSUE THREAD

**Issue by coollofty** [espressif/esp-idf#5389]
Is there a way to make ESP32 support 128G TF card, such as exfat or ext4 partition format?

**Comment by igrr** [comment]
While not a supported option, you can try enabling exFAT by changing this to `1`:
https://github.com/espressif/esp-idf/blob/7d75213674b4572f90c68162ad6fe9b16dae65ad/components/fatfs/src/ffconf.h#L255
Keep in mind that exFAT is not a royalty-free format: https://www.microsoft.com/en-us/legal/intellectualproperty/mtl/exfat-licensing.aspx.

The only compact implementation of ext4 I am aware of is lwext4, but due to GPL v2.0 license it might not be suitable.
