### ISSUE TITLE
IDF 4.2 HTTPS Client SSL issue (IDFGH-3468)

### ISSUE THREAD

**Issue by kotkis1** [espressif/esp-idf#5428]
**Environment:**

- IDF version: ESP-IDF v4.2-dev-1660-g7d7521367 (marked as latest)
- Hardware: ESP32-SOLO-1,  ESP32-S2-Wrover(Saola) 
- Compiler version: (crosstool-NG esp-2020r1) 8.2.0
- OS: Linux
- IDE: Eclipse 2020-03 (4.15.0)
- SDK Config: defaults from the examples

**The isuue**
Running the examples "https_request" and "https_x509_bundle" on Saola and Solo ends up with the following error:
`E (25843) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7680`
with meaning: No CA Chain is set, but required to operate.

**Additional tests on stable IDF 4.0.1**
The examples are running fine on ESP32-SOLO-1

**Comment by Alvin1Zhang** [comment]
@kotkis1 Thanks for reporting, we will look into.

**Comment by ESP-Marius** [comment]
Hi @kotkis1,

This issue has already been fixed on our internal repo (commit: a2d7e8cbba35a9d44f2ae833cfd12e8743511e88) and should be available here as soon as Github is synced with our internal repo.

Unfortunately there's been some issue with this lately so it's been a while since the last sync, hopefully it will happen soon!

If you want to fix it yourself before this, you can apply the following change in `components/mbedtls/CMakeLists.txt:`

Change: `target_link_libraries(${COMPONENT_LIB} INTERFACE ${mbedtls_targets})`
To: `target_link_libraries(${COMPONENT_LIB} PUBLIC ${mbedtls_targets})`

**Comment by kotkis1** [comment]
The fix worked, thank you.
