### ISSUE TITLE
target_add_binary_data() does not depend of the file (IDFGH-3746)

### ISSUE THREAD

**Issue by galah92** [espressif/esp-idf#5666]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it): v4.0.1
- Build System: CMake & idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System: Windows & Linux
- (Windows only) environment type: ESP Command Prompt & Plain Command Prompt
- Using an IDE?: VSCode
- Power Supply: USB

## Problem Description

Updating the file embedded with `target_add_binary_data()` on disk doesn't trigger a rebuild of the relevant component.
Consider a `file.txt` which is embedded via:
```
idf_component_register(
SRCS
    main.c
EMBED_TXTFILES
    file.txt
)
```

After manually updating `file.txt` on disk and running `idf.py build` / `cmake --build build`, the relevant binary file which is generated from `file.txt` and then attached is not updated.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, ha

**Comment by galah92** [comment]
Hi @Alvin1Zhang, the original issue was updated.

**Comment by Alvin1Zhang** [comment]
@galah92 Thanks for the updates, we will look into.

**Comment by projectgus** [comment]
Hi @galah92 ,

Thanks for providing the extra details.

I'm not able to reproduce this in a simple example under Linux with ESP-IDF v4.0.1 or on master branch. Building with `idf.py build` or `cmake --build build` both seem to pick up the changed file and trigger the necessary generation, compile & linking steps.

> the relevant binary file which is generated from file.txt and then attached is not updated.

There are four steps where this might be failing: first `file.txt` is processed into an assembly file `file.txt.S`, then assembled to `file.txt.S.obj`, then saved into the component static library, and finally linked into the executable.

I am guessing it's most likely the first step is not happening because CMake handles the rest in a fairly standard way. But to rule it out, could you please check if either/both of `file.txt.S` and `file.txt.S.obj` are being updated in the build directory?

One thing I did notice is that `file.txt.S` is generated in the top-level build directory, so there is a potential for collisions if a file with the same name is embedded into multiple components.

The only other possibilities I can think of are:

* Some unexpected difference between CMake versions. I'm using 3.16.3.
* Some other condition in the component or the project has to be true to trigger the bug.

Finally, if it doesn't contain any sensitive information then are you able to attach your generated build.ninja or Makefile?

Thanks.

**Comment by Alvin1Zhang** [comment]
@galah92 Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by galah92** [comment]
> @galah92 Thanks for reporting, would you please help share if any updates for this issue? Thanks.

Hi, yes - thanks for raising that up. The solution was to add `enable_language(C CXX ASM)` before calling `project(..)`. I didn't get into the details, but a think a call of such is required somewhere under `idf.cmake` (or in a nested CMake file).
