### ISSUE TITLE
taskYIELD should also clear task wdt enough. (IDFGH-3751)

### ISSUE THREAD

**Issue by junyoun-kim** [espressif/esp-idf#5671]
As I understand, task wdt is designed to prevent a task occupying cpu in monopoly for long times.
Then sholudn't taskYIELD function also clear task wdt timer enough?

As I tested, taskYIELD doesn't clear the wdt timer if there is no other task running.
So in my thread, I'm calling taskYIELD several times, but watchdog always happens.

I don't want to use bsp-dependent function like "esp_task_wdt_reset" in my code.
So could you consider engaging taskYIELD function with clearing task wdt?

**Comment by Dazza0** [comment]
Although this issue has been closed, I'll leave a comment in case someone else has the same questions/runs into the same issue.

> As I understand, task wdt is designed to prevent a task occupying cpu in monopoly for long times.

Not exactly. The task WDT does not check if a particular task occupies too much CPU time. Rather, the task WDT checks whether the IDLE tasks (one for each CPU) has been able to run within a given timeout period. Because the IDLE tasks are the lowest possible priority task, them not being able to run is indicative of one (or a group of) higher priority task occupying the CPU in monopoly for a long period of time.

> Then sholudn't taskYIELD function also clear task wdt timer enough?

Nope, because calling `taskYIELD()` does not guarantee that the IDLE task will run. You could be running a `taskA()` that yields to a lower priority `taskB()`,  where `taskB()` still has a higher priority than the IDLE task.

> As I tested, taskYIELD doesn't clear the wdt timer if there is no other task running. So in my thread, I'm calling taskYIELD several times, but watchdog always happens.

You need to ensure that all your tasks (threads) will block on something, either some semaphore/queue/event or a delay. This will mean at some point, all the tasks are blocked, thus allowing the scheduler to select the IDLE task to run.

> I don't want to use bsp-dependent function like "esp_task_wdt_reset" in my code.

`esp_task_wdt_reset()` is not meant to reset the entire task WDT. The task WDT has a "subscription" feature where you can cause the task WDT to watch a user task. In other words, if a `taskA()` subscribed to the task WDT, then the task WDT will trigger if `taskA()` has not run within the specified timeout. Inside `taskA()`s main loop code, you would then add `esp_task_wdt_reset()`.
