### ISSUE TITLE
mqtt connect_return_code is always zero (IDFGH-3787)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#5705]
## Environment

- Module or chip used: ESP32-WROOM-32D
- IDF version: v4.3-dev-771-gc77c4ccf6c43
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System: Linux
- Power Supply: USB

## Problem Description

When I got MQTT_EVENT_ERROR event, I check the value of connect_return_code and found it's always 0.
I would expect to get some meaningful error code with this field.

### Expected Behavior
connect_return_code should be some some meaningful error code when error happened.

### Actual Behavior
connect_return_code is always 0.

### Steps to reproduce
Various ways to see this issue:
e.g try connect wrong port or test with wrong user/password.

**Comment by ESP-Marius** [comment]
@AxelLin Hi

The `connect_return_code` is defined in the MQTT specification (see [Connection return code](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Table_3.1_-)) and is returned by the broker. 

So errors like connecting with the wrong port is not covered by this return code.

Connecting with the wrong password _will_ give you a `Connection refused, not authorized` though, I just tested it with a local mosquitto broker and it works fine. If you don't get an error then the issue is probably on the broker side.
