### ISSUE TITLE
DNS Not working when DHCP disabled for setting static ip (IDFGH-3942)

### ISSUE THREAD

**Issue by jogendar** [espressif/esp-idf#5831]

**Comment by Alvin1Zhang** [comment]
@jogendar Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@jogendar Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by jogendar** [comment]
@Alvin1Zhang  Thanks for looking in to it.

## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version WroverKit v3
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it):
    v4.0.1
- Build System:         |idf.py
- Operating System:     Windows
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: No
- Power Supply: USB

## Problem Description
Connected to WiFi In station mode and
I have https client (get query to get weather from open weather api) + tcp server application running on two different threads.
to connect to TCP server, i made it static ip. but when static ip enbled not able to connect to weather API (with DNS error)

### Expected Behavior
static IP + DNS should work together since there is no relation b/w DHCP and DNS
### Actual Behavior

### Steps to reproduce

1. Enable wifi in Station mode
2. Disable dhcp and set static ip
3. call http url with domain name


I don't have the setup right now. I'll post the logs once I got setup in my hand

**Comment by hagre** [comment]
Some days ago i mabye had the same problem. After some hours "debuging" the software, i discoverd that the problem was the new android mobile phone hotspot i have just started to use. With the change to Android pie 9.0 all ip adresses of the hotspot/ap/gateway changed automaticly to a random number each activationtime. 
On the ESP side i used a static ip setting with a correct/possible DNS and esp ip, but i missed the changing gateway ip. So all connections in the network itself worked normal, but connections to the internet incl. the DNS stopped working!
Now i am connecting using dhcp to get the actual setting. disconnect and reconnect with the same numbers as static settings (ecxept the esp ip).

**Comment by YouDONG-ESP** [comment]
Hi @jogendar , did @hagre helps your problem?

**Comment by freakyxue** [comment]
hi @jogendar 
Follow the steps below to test:

-  connect to ap

- disable dhcp

-  set static ip addr

- set fallback dns

- get website dns IP

**Comment by freakyxue** [comment]
hi @jogendar 
Do you have any questions? If not, I will close this issue. If you have any problems, please open this question at any time. Thank you

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen. Thanks.
