### ISSUE TITLE
idf.py set-started esp32 err: no module named click (IDFGH-4171)

### ISSUE THREAD

**Issue by huang443765159** [espressif/esp-idf#6032]
Hello.
I am using mac for idf tool installation.I installed the tutorial https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/get-started/index.html#get-started-set-up-tools and they were fine until I did step 7.
I got the error when i did idf.py set-started esp32 like this:
<img width="878" alt="WeChat17d865120f185d2c40cd4dcb6f0ba30b" src="https://user-images.githubusercontent.com/59813252/97268418-d7bab380-1866-11eb-8670-49d1a098ff95.png">

I have installed this library, but there is still something wrong, could you please help me？
<img width="428" alt="WeChate7817cabb6b053a05e62788b5d1f3d12" src="https://user-images.githubusercontent.com/59813252/97268289-9aeebc80-1866-11eb-8769-403553ed5141.png">
Thanks.

**Comment by huang443765159** [comment]
I have solved the problem！It took me hours... The problem is that I need to use python2.7 instead of 3.8.

**Comment by dobairoland** [comment]
Hi @huang443765159. I'm glad that you've resolved your issue. In case anybody else encounters this issue, I just want to note that it should have to work with Python 3.8 as well. As a matter of fact, I'm using it with that Python version right now. 

Usually, this kind of issue is caused by invoking not the same Python for which the package was installed. The output of `which python` changes to a Python environment with "espressif" in the path. After that, using `python -m pip` can be used to ensure that packages are manipulated for the right Python interpreter. It is worth noting that even `python $(which idf.py)` can be used to ensure or check if the same behavior is encountered in case `idf.py` is invoked with a different Python.

I hope this helps for any future similar issue.
