### ISSUE TITLE
using SDcard and JTAG (IDFGH-4447)

### ISSUE THREAD

**Issue by mcSimoffa** [espressif/esp-idf#6278]
I want use JTAG debug and SD card not in SPI mode
I have idea to remap SPIFLASH to VSPI
How should I configure my project in this case ?

**Comment by igrr** [comment]
@mcSimoffa I assume your question is about the ESP32 chip. Please note that this issue tracker is for feature requests and bug reports for ESP-IDF project. Hardware and PCB design is out of scope of this issue tracker, please use esp32.com for similar questions or contact Espressif support via a form on the website.

I'll post an answer here anyway, since this seems to be a recurring question. What you are describing is possible but a bit tricky. You need to do the following:

* Use ESP32 chip in your design, not a module. ESP32-WROOM and ESP32-WROVER modules have an SPI flash chip connected to GPIOs 6-11. This flash chip would interfere with the SD card.
* Choose the pins to connect a SPI flash chip. At minimum you need 4 GPIOs, for example GPIO19, GPIO21, GPIO22, GPIO23. Here is an example of connections you can use:
  <img width="574" alt="Screenshot 2020-12-16 at 12 26 01" src="https://user-images.githubusercontent.com/4349050/102342679-e0438680-3f99-11eb-99d8-e76fc4086c6b.png">
* Verify your connections before proceeding with the PCB design! It is not uncommon to accidentally swap DI/DO lines when connecting a flash chip. You can connect the flash chip to a development board first, and verify that the pin connections work as expected, using the [ext_flash example](https://github.com/espressif/esp-idf/tree/master/examples/storage/ext_flash_fatfs).
* The next step is to make the ESP32 boot from the flash chip connected to non-default GPIOs. This can be done using espefuse.py. For the pin connections shown above, the commands would be as follows:
  ```
  espefuse.py --port PORT burn_efuse SPI_PAD_CONFIG_CLK 22
  espefuse.py --port PORT burn_efuse SPI_PAD_CONFIG_Q 19
  espefuse.py --port PORT burn_efuse SPI_PAD_CONFIG_D 21
  espefuse.py --port PORT burn_efuse SPI_PAD_CONFIG_CS0 23
  ```
  Note that burning the eFuses is a one-time operation. Once burned, eFuses can not be reset.
* At this point it should be possible to flash the board using `idf.py flash` as usual. No special configuration is required in the project. You can use slot 0 for SD/MMC peripheral, since it is now free from the external SPI flash. For example, when initializing sdmmc, you can modify the config structure as follows: 
  ```
  sdmmc_host_t config = SDMMC_HOST_DEFAULT();
  config.slot = 0;
  ```
