### ISSUE TITLE
Instructions on how to get ESP-IDF should be on top of release info (IDFGH-4494)

### ISSUE THREAD

**Issue by rogerdahl** [espressif/esp-idf#6323]
The instructions on how to get ESP-IDF for a given release from GitHub is currently the bottom of the release info, underneath the (very long) changelog. It would be better to have it on top, as the first thing you see when opening a release.

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.

**Comment by projectgus** [comment]
Hi @rogerdahl,

Yes, agree this seems reasonable. The steps have been at the end for a long time now, since back when the changelogs were shorter.

We won't edit the existing releases, as editing a release sends a new round of emails to everyone who is subscribed. But we can change this starting from the next release.

**Comment by Alvin1Zhang** [comment]
Thanks for your suggestion, we have used this approach in our recent releases. Will close the issue.
