### ISSUE TITLE
parallel builds (IDFGH-4578)

### ISSUE THREAD

**Issue by edbek** [espressif/esp-idf#6395]
1. Please, give advice on how to make a parallel builds ?
2. In addition, for some reason, compilation in Eclipse for the target ESP32-S2 does not work (works only ESP32) !

**Comment by projectgus** [comment]
H @edbek,

Can you please give some more information about which ESP-IDF version you are using, how you are building your project, etc?

Some tips in the meantime:

* If you're using CMake (or the [ESP-IDF Eclipse Plugin](https://github.com/espressif/idf-eclipse-plugin/) which uses CMake on the backend) then you should be getting parallel builds already, automatically.
* You need to use ESP-IDF v4.2 or newer, and the CMake build system, in order to build for ESP32-S2.

**Comment by edbek** [comment]
Thank you, everything works with ESP-IDF v4.2 !

**Comment by projectgus** [comment]
Glad to hear!
