### ISSUE TITLE
v3.3.1   ./install.sh  erros (IDFGH-4913)

### ISSUE THREAD

**Issue by zhy102** [espressif/esp-idf#6705]
Installing Python environment and packages
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "C:/msys32/esp-idf-v3.3/tools/idf_tools.py", line 1358, in <module>
    main(sys.argv[1:])
  File "C:/msys32/esp-idf-v3.3/tools/idf_tools.py", line 1354, in main
    action_func(args)
  File "C:/msys32/esp-idf-v3.3/tools/idf_tools.py", line 1144, in action_install_python_env
    idf_python_env_path, _, virtualenv_python = get_python_env_path()
  File "C:/msys32/esp-idf-v3.3/tools/idf_tools.py", line 840, in get_python_env_path

**Comment by dobairoland** [comment]
Hi @zhy102. I'm sorry but what you are attempting to do is not supported. You should not run `install.sh` from MSYS32. Here are the available options:
- Run `install.bat` from Windows command line. Later versions of ESP-IDF support powershell as well. You can use ESP-IDF from the Windows command line after running `export.bat`. This feature is experimental in v3.3 but became the default one since v4.0.
- Use https://github.com/espressif/esp-idf/blob/release/v3.3/tools/windows/windows_install_prerequisites.sh to set up your MSYS32 environment. This is the `install.sh` equivalent for MSYS32.
- Download a ZIP-ped MSYS32 environment from https://docs.espressif.com/projects/esp-idf/en/release-v3.3/get-started/windows-setup.html#toolchain-setup.
