### ISSUE TITLE
MQ2 sensor component for ESP-IDF (IDFGH-4955)

### ISSUE THREAD

**Issue by Yoimer** [espressif/esp-idf#6747]
Hello everybody. Is there any MQ2 library available for ESP-IDF?.

Currently there are these amazing libraries that work great on Arduino-ESP32 https://github.com/miguel5612/MQSensorsLib.

Is there any possible way to import those Arduino libraries and use them as native components on ESP-IDF, MQ2 specifically?. 

Thanks in advance

**Comment by leeebo** [comment]
@Yoimer Thanks for your advice. But I think ESP-IDF tends to support more basic and core components, while ESP-IoT-Solution is more suitable to support such external sensor drivers. MQ series will be considered to add to https://github.com/espressif/esp-iot-solution/tree/master/components/sensors

**Comment by Yoimer** [comment]
@leeebo Hello. Thanks for responding. To make things a bit easier. Is there any way you could import these [MQSensorsLib](https://github.com/miguel5612/MQSensorsLib) from Arduino ESP32 to ESP-IDF as a component?

That Arduino library happens to be very reliable.

Looking forward to hearing from you soon.

Thanks in advance.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for the very slow turnaround, let us track in https://github.com/espressif/esp-iot-solution/issues, feel free to reopen.

**Comment by carlosdelfino** [comment]
I refactored the MQSensorLib library to adapt it to ESP-IDF. I don't yet have the MQ sensors in hand and how to test them, but there was no change in the algorithm, only in the calls to the analogRead() and Serial.print*() functions, so I believe it works well. Since the RP has not yet been accepted, it is in my repository: https://github.com/RapportTecnologia/esp-iot-solution/tree/MQSensorLib/components/sensors/gas/MQSensorLIB
