### ISSUE TITLE
Contriburiton Guidelines Popup on Github Links Not Useful (IDFGH-5021)

### ISSUE THREAD

**Issue by cnlohr** [espressif/esp-idf#6807]
## Environment

- Development Kit:     N/A
- Kit version (for WroverKit/PicoKit/DevKitC): N/A
- Module or chip used:  N/A
- IDF version (run ``git describe --tags`` to find it): v4.4-dev-480-g68ce83dff
- Build System:        N/A
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     Linux
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?:  N/A
- Power Supply:         N/A

## Problem Description

When attempting to make a pull-request, the following popup appears linking the contribution guidelines on github.  
![image](https://user-images.githubusercontent.com/2748168/113253699-9ace6f00-9293-11eb-87be-eee759ed1abf.png)

It links this page here: https://github.com/espressif/esp-idf/blob/526f682397a8cfb74698c601fd2c5b30e1433837/CONTRIBUTING.rst

But many of the links on that page are broken. All of the links using the :prefix: appear to point back at the page but nowhere on the page.

For instance, clicking :idf:`examples' links to here: https://github.com/espressif/esp-idf/blob/526f682397a8cfb74698c601fd2c5b30e1433837/CONTRIBUTING.rst#id7  (note #id7) 

### Expected Behavior

The github documentation page for contributions can 

### Steps to reproduce

1. Start a new PR for ESP-IDF from a personal repo.
2. Click "Contributing guidelines"
3. Click a link within the "Contributing guidelines" document.

(See problem description for pictures/etc)

### Code to reproduce this issue

N/A

## Debug Logs

N/A

## Other items if possible

N/A

**Comment by projectgus** [comment]
Hi @cnlohr,

Thanks for the heads-up. This ReST file is built into the main ESP-IDF docs here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/index.html - which is what all of the extra markup is for. GitHub renders some of it correctly, but clearly not all of it.

I'm not sure what we can do to fix this, I don't think we can override the GitHub generated link, and we do like the fact that the file is (mostly) readable in plaintext in the repo as well as being in the docs.

Something we might be able to do is add some kind of header on the .rst file that links to the "real" docs pages, but isn't rendered into the "real" docs page itself. Although this is also a bit fiddly because we maintain multiple docs versions and we have no way of knowing which branch someone is reading.

Will consult some colleagues and think about this some more.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for the very slow turnaround, there is a fix under internal reviewing, and the issue will close automatically once the fix is available on GitHub, thanks.
