### ISSUE TITLE
SPI Slave not Realtime and corrupting Data (IDFGH-5166)

### ISSUE THREAD

**Issue by nikhilavrio** [espressif/esp-idf#6943]
## Environment

- Module or chip used:  ESP32-WROVER-IE
- IDF version: v4.2-351-gce2c615bb
- Build System:        idf.py
- Compiler version: 8.4.0
- Operating System:     macOS
- Power Supply:        external 3.3V

## Problem Description

I am interfacing with ADC to capture waveforms. ADC sends data as SPI Master at 8Mhz / 4Mhz (configurable) to ESP32 (SPI Slave). Waveform is a 50Hz sine wave from a signal generator.

The data received in ESP32 is then plotted. I am getting spikes every  3-4 cycle. ADC sends 28bytes at 8kHz frequency. It looks like the SPI Slave Driver is corrupting the data / not capturing bits in realtime.

Plotting the SPI Protocol data of ADC (using a protocol analyzer) results in a perfect sine wave.

So there is definitely something wrong with SPI Slave driver. Can you help ?

SPI Mode (as per datasheet of ADC) should be 3

But ESP32's SPI Mode 1 gives the perfect data. (0, 2, 3 are full of noises).

PFA Spike Image

### Expected Behavior

Perfect Sine wave is expected.

### Actual Behavior

Sine Wave with Spikes every 3-4 cycles. Protocol Data represents perfect Sine Wave without any spike. SPI Slave Driver is wrong.

As per ESP32 SPI Slave - 
<img width="1253" alt="Screen Shot 2021-04-26 at 10 57 35 PM" src="https://user-images.githubusercontent.com/60929494/116125190-cf8ee400-a6e2-11eb-908d-00ee763b2326.png">

As per Protocol Analyzer - 
<img width="1280" alt="Screen Shot 2021-04-26 at 10 58 53 PM" src="https://user-images.githubusercontent.com/60929494/116125368-095fea80-a6e3-11eb-8b8f-ebe40930be2a.png">

**Comment by nikhilavrio** [comment]
Here is Logic Analyzer screenshots.
<img width="1021" alt="Screen Shot 2021-04-26 at 11 29 38 PM" src="https://user-images.githubusercontent.com/60929494/116129168-6d84ad80-a6e7-11eb-9136-4b32efa3ee49.png">
<img width="1038" alt="Screen Shot 2021-04-26 at 11 30 21 PM" src="https://user-images.githubusercontent.com/60929494/116129193-737a8e80-a6e7-11eb-9afd-d61cae44b237.png">
<img width="1048" alt="Screen Shot 2021-04-26 at 11 30 09 PM" src="https://user-images.githubusercontent.com/60929494/116129199-75445200-a6e7-11eb-9503-5338a8a41bd1.png">
<img width="1159" alt="Screen Shot 2021-04-26 at 11 29 53 PM" src="https://user-images.githubusercontent.com/60929494/116129203-76757f00-a6e7-11eb-94c8-f0cc182d78f3.png">

**Comment by Alvin1Zhang** [comment]
Thanks for the very detailed report.

**Comment by Icarus113** [comment]
Hi @nikhilavrio ,

For SPI protocol, master determines when to start/finish a transaction, no matter if slave has prepared ready TX/RX/both buffer(s) or not. So usually there is a synchronization way to let master know slave is ready. 

Therefore, if you directly use SPI slave driver to receive data from ADC without synchronization, you may not get complete data in some conditions. Let's take an easy example:
1. Slave side prepares a 28-Byte buffer.
2. Master lowers down the CS, the transaction starts.
3. Slave side called `spi_slave_transmit`. When the slave-prepared-buffer is actually loaded to the SPI hardware, we assume that at this time, master has already sent 10 Bytes data to the SPI bus.
4. Slave side gets the rest 18 Bytes data from the SPI bus.
5. Master finish sending all the data, and it sets CS to high. 
6. `spi_slave_transmit` will return due to the low CS. 

Finally, for the 28-Byte buffer, the first 18 Bytes data are actually got from the master, whereas the rest 10 Bytes of the buffer are **unchanged**. At this point, if you plot all the buffer, you'll get a wrong plot. 

However, you can check the `trans_len`  of `spi_slave_transaction_t` indicating the actual received bytes per transaction. With respect to the above situation, the `trans_len` would be 18*8 (in bits).

For synchronization, the goal is to make sure that slave has actually loaded its buffer to the SPI hardware (time point A) before master lowers down the CS line. We have a callback to indicate the time point A  - `post_setup_cb` in `spi_slave_interface_config_t` will be called at this time.

**Comment by Alvin1Zhang** [comment]
@nikhilavrio Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@nikhilavrio Thanks for reporting, would you please help share if any updates for this issue? Thanks.
