### ISSUE TITLE
[S2] float calculations accuracy (IDFGH-5171)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#6947]
- idf commit: b0150615dff529662772a60dcb57d5b559f480e2
- freq: 240.0001 to 1000, with resolution up to 4 digits
- div: 1 - 10
```
float val = (freq * div) / 26.0;
```
- required accuracy up to 6 digits
example:
- expected result: `433,9251×4÷26 = 66,757707692`
- esp32-s2 result: `I (00:00:01.991) : Freq: 433.9251, val: 66.757706, div: 4`

I think the problem is bigger, because:
```
433.9251 * 1000 = 433925.1250
433926  / 1000.0 = 433.925995
```

Thanks

**Comment by igrr** [comment]
Hi @chegewara, I have compiled the following code on Linux:

```c++
#include <stdio.h>

int main(void) {
    float freq = 433.9251f;
    float div = 4;
    float val = (freq * div) / 26;
    printf("val=%f\n", val);
    return 0;
}
```
Running it produces:
```
$ gcc test.c -o test && ./test
val=66.757706
```
Which seems to match the value printed on ESP32-S2. So it doesn't seem to be an ESP32-S2 specific problem.

This looks correct for 32-bit float representation, since:
66.7577**076**92 (expected result) is between two nearest floating point values:
66.7577**056**884765625 — mantissa 36145**8** (1.0430891513824463), exponent 133 (2^6) and
66.7577**133**1787109375 — mantissa 36145**9** (1.0430892705917358), exponent 133 (2^6)

There is simply no other value between 66.7577057 and 66.7577133 that can be represented as a 32-bit floating point number.

**Comment by chegewara** [comment]
Thanks
