### ISSUE TITLE
COMPONENT_EMBED_FILES does not seem to honor file change (IDFGH-57)

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#696]
I am using `COMPONENT_EMBED_FILES` in my build environment to include a data file in flash.  This seems to work fine.  However, I also seem to notice that if I change the underlying file that is to be build and issue a new "make" to build the new binaries, the new file sizes (and possibly even the content) are not being honored for the new file.  I have to execute a full "make clean" and then a full rebuild.  This issue asks for examination of this and either we document a warning about a clean re-build being required or else we change the build to honor a change in the data files.

**Comment by projectgus** [comment]
Hi @nkolban ,

I don't know how this issue got overlooked for so long. This is my fault and I'm very sorry about it.

I'm no longer able to reproduce this with the v3.2.2 release. If I make a simple program like this:

```
#include <stdio.h>
#include <string.h>

extern char _binary_test_bin_start;
extern char _binary_test_bin_end;

void app_main()
{
    char buf[128];
    strlcpy(buf, &_binary_test_bin_start, &_binary_test_bin_end - &_binary_test_bin_start);
    printf("Test binary contents: %s\n", buf);
}
```

and embed the test binary via main/component.mk:

```
COMPONENT_EMBED_FILES := test.bin

```

Then the file is re-embedded each time `make` runs, if it has changed.

I'm guessing probably the issue was fixed in one of the interim IDF releases.

Sorry again for the unacceptably slow turnaround.
