### ISSUE TITLE
Terminal crashes when I run source vendors/espressif/esp-idf/install.sh (IDFGH-5252)

### ISSUE THREAD

**Issue by OzzyGrammer** [espressif/esp-idf#7018]
on my ubuntu 18.04 whenever I run the install.sh script my terminal crashes

source vendors/espressif/esp-idf/install.sh
. vendors/espressif/esp-idf/install.sh
vendors/espressif/esp-idf/install.sh

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@OzzyGrammer Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details, feel free to reopen with more details. Thanks.

**Comment by aaronjudd** [comment]
this is actually a real issue - If you run  `$IDF_PATH/install.sh esp32` it will not crash.  if you run with source ` source $IDF_PATH/install.sh esp32` it will crash the terminal.

**Comment by fhrbata** [comment]
> this is actually a real issue - If you run `$IDF_PATH/install.sh esp32` it will not crash. if you run with source ` source $IDF_PATH/install.sh esp32` it will crash the terminal.

Hello, the `install.sh` script should be executed normally, not sourced. The issue you're encountering arises because the script includes `set -e` (which causes the script to exit immediately if any command returns a non-zero status). The
 command `basedir=$(dirname "$0")` fails because `$0` does not contain the script name when it is sourced. As a result, the `install.sh` script exits, and since it is sourced, it also closes your current terminal session. This is equivalent to running `exit` in the terminal.
