### ISSUE TITLE
May I please get details of Internal RTC and how it works in ESP-32 C3 DevKitM-1 v1.0. How can I update time of this internal RTC such that it's time should not get reset after any situation like power failure etc..  (IDFGH-5564)

### ISSUE THREAD

**Issue by Shravani100** [espressif/esp-idf#7287]
I want exact working of Internal RTC in ESP32-C3 DevKitM-1 v1.0. I want to update the time of RTC such that it should not reset after any situation like power failure. If settimeofday() is the function to maintain the RTC time then how to execute it. Or else there is any other process to carry out this time updation.

**Comment by igrr** [comment]
Hi @Shravani100,

> such that it should not reset after any situation like power failure

Unfortunately this is not possible on the ESP32-C3. Internal RTC clock will keep working when the chip is being reset due to deep sleep, software or watchdog resets. However powering the chip off will also power off the RTC. Same for resetting the chip via its EN pin.

You might need to use an external battery-backed RTC module if you need the time to be maintained across power-on reset.

Regarding settimeofday, you are correct that this function can be used to set the time in ESP-IDF. See https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html for more information on time related functions.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
