### ISSUE TITLE
BlueFi library esp_ble_gap_set_device_name can't accept more than 26 characters (IDFGH-5588)

### ISSUE THREAD

**Issue by raoulshih** [espressif/esp-idf#7310]
## Environment

- Module or chip used:  [ESP32-S by AI Thinker]
- IDF version (run ``git describe --tags`` to find it):
v3.3.1
- Build System:         [Make]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
   xtensa-esp32-elf-gcc (crosstool-NG esp32-2018r1) 8.2.0
- Operating System:     [Linux]
- Using an IDE?: [vscode]
- Power Supply:         [USB]

## Problem Description

I used BlueFi to create my own BLE to WiFi Setting, when I try to set the name of the ESP32 Device using esp_ble_gap_set_device_name, I got incorrect results.  

### Expected Behavior

I intend to set a 29-characters name for the device, expected to see 29 characters using the EspBluFi utility. 

### Actual Behavior

On the EspBluFi utility, I only see 26 characcters.

### Code to reproduce this issue

I use this to set the name of ESP32,
```cpp
BLUFI_DEVICE_NAME = "123456789012345678901234567890";
esp_ble_gap_set_device_name(BLUFI_DEVICE_NAME);
```
But I see only 26 characters on the EspBluFi utility "12345678901234567890123456"
![IMG_8602](https://user-images.githubusercontent.com/22785781/126725988-7c0ed78b-31eb-43da-950f-8b0027831bb9.PNG)

**Comment by xulongzhuang** [comment]
Hi，@raoulshih , 
I think the reason may be this: first, the length of adv_data is 31 bytes, and it contains multiple AD structures. When the AD_struture of device_name is too long, it will make the AD_struture arranged after it not displayed, and it will also The display is not complete due to length limitation, I think this is normal. The attachment is a device_name with 28 bytes, you can see that his original adv_data is only 26 bytes 
![微信图片_20210816112345](https://user-images.githubusercontent.com/80943680/129508140-0a979cff-caf1-4fb6-b310-3d5cb9db19fd.jpg)

**Comment by Alvin1Zhang** [comment]
@raoulshih Thanks for reporting, sorry for slow turnaround, would you please help share if any updates for the issue? Thanks.

**Comment by raoulshih** [comment]
@Alvin1Zhang I just stuck with 26 characters, and it worked fine.

**Comment by Alvin1Zhang** [comment]
@raoulshih Thanks for sharing the updates.
