### ISSUE TITLE
The .html code of our developed webpage sends (date, month, year, hour, minute, seconds) of system to which it is connected from front end through json format. I am using esp32C3. I am facing issue in acquring/printing that json object array on screen. In my code I took a variable and allocate memory for the same and defined a pointer array. Now I want to print each of that element but it is showing zero value.

### ISSUE THREAD

**Issue by Shravani100** [espressif/esp-idf#7316]

**Comment by julian-weinert** [comment]
Please read the instructions for issues. You need to provide details, code, info of your setup, a clear explanation.
To me it sounds like a general programming question though and not an issue with ESP in particular

**Comment by Alvin1Zhang** [comment]
@julian-weinert Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and will close due to short of details, feel free to reopen and provide more information as per the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
