### ISSUE TITLE
Appending questions to MDNS responses breaks Avahi-Daemon (IDFGH-5736)

### ISSUE THREAD

**Issue by d8ahazard** [espressif/esp-idf#7453]
This is to loop in this library on the discussion being had here:

https://github.com/Aircoookie/WLED/issues/2009#issuecomment-902983255

and here:

https://github.com/lathiat/avahi/issues/348

Basically, the esp-mdns implementation is echoing th question message in responses, which causes avahi-daemon to discard the response as invalid. 

I can see this happening here at line 1085:

https://github.com/espressif/esp-idf/blob/master/components/mdns/mdns.c

Apparently, the proper approach as per the RFC for MDNS is to ignore these responses, so it would stand to reason that the behavior on this side is fine, but I just wanted to link it to the other issues for completeness.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/7124

**Comment by david-cermak** [comment]
@negativekelvin Thanks for the reference

@d8ahazard This bug was fixed as
* f601cb0 on `v4.4`
* 3a588d7 on `v4.3`
* 93921e0 on `v4.2`

Please update the IDF version to include the above commits. It's also possible to work around this bug setting 
* [CONFIG_MDNS_STRICT_MODE](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-mdns-strict-mode) to `y`

**Comment by david-cermak** [comment]
@d8ahazard Could you please close the issue?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
