### ISSUE TITLE
Support for sdkconfig overlays (IDFGH-5765)

### ISSUE THREAD

**Issue by bpietsch** [espressif/esp-idf#7473]
I'd like to be able to have multiple variants of my sdkconfig file for different stages of my workflow (e.g. debug and release variants, but more general than that). Given that large portions of the various configs will have the same values, it would be nice to have a "base" sdkconfig file and one or more "overlay" sdkconfig files that can override just the relevant settings. This way, when updating to new ESP-IDF versions I don't need to worry about making sure that new settings are applied the same to all of my variants... they would just get applied once in the base sdkconfig. This could be achieved via an "include" mechanism and an augmented config editor that behaves differently when opened using the base vs overlay config (e.g. if the editor notices the "include" directive, it writes only the settings that differ from the included base config when saving, thus preserving the base configuration for the majority of the settings)

**Comment by dobairoland** [comment]
Hi @bpietsch. Thank you for the suggestions and feedback.

Currently we have `sdkconfig.defaults` which gets applied when `sdkconfig` is not present. This can be used for the "base" sdkconfig file you mention.

The overlays you are describing are not supported but if you really need it then you maintain and apply a set of files by yourself. Here is how I would do it:

```bash
cat sdkconfig.defaults > sdkconfig   # overwrites the old sdkconfig with a maintained minimal set of "base" options
cat sdkconfig.set1 >> sdkconfig       # append to the file - it sets additional configurations
```

The overlays you are describing is not supported because it goes against the essential of the purpose of the configs. The configs stored in `sdkconfig` is the configuration of the project which sets hardware (and software) configuration but it should not change during the lifetime of the project development. You want to debug the same hardware setup you are releasing.

You can have different build directories and run the build with different `sdkconfig`s as well, if that helps you.

You can find more information on this page:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html

**Comment by igrr** [comment]
One thing to add, working with multiple sdkconfig.defaults files can be facilitated by setting SDKCONFIG_DEFAULTS variable. This example might be useful: https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config#combining-multiple-files-in-sdkconfig_defaults.
