### ISSUE TITLE
[TW#13642] Wifi+BLE error while scanning wifi

### ISSUE THREAD

**Issue by Emaxinvader** [espressif/esp-idf#752]
If I scan for wifi network when BLE GATT server and Wifi are connected, I get sometimes this error "E (33262) wifi: pm.c 953" and all connections are closed.
What does it mean?

I'm using the defult configuration of BLE examples with esp-idf v2.1rc1.

**Comment by FRDavid** [comment]
+1

In my case I reached the error in the following way:
- Turn on BLE to advertise
- Turn on WiFi
- Scan networks, connect to a network, disconnect from network, scan networks

After a couple of scans the message above mentioned appears and seems wifi task is in a bucle or similar since next message is shown:

Task watchdog got triggered. The following tasks did not feed the watchdog in time:
 - IDLE (CPU 0)
Tasks currently running:
CPU 0: wifi
CPU 1: IDLE

BR,
David

**Comment by Roody75** [comment]
From time to time (about 1 in 5 tries) the same issue occures during WPS scan as well (@HEAD revision), mostly if I start WPS in ESP before I start it in the AP:

```
E (184476) wifi: pm.c 953
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
Tasks currently running:
CPU 0: wifi
```

**Comment by jack0c** [comment]
@Roody75 @Emaxinvader @FRDavid It should be a bug, can you provide commit ID.

**Comment by TimXia** [comment]
@Roody75 @Emaxinvader @FRDavid The bug has been fixed in IDFv2.1. Please have a try.
