### ISSUE TITLE
Modbus RTU example in ESP32  (IDFGH-5961)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7649]
We got response from ESP32 that :- **The UART has byte interrupt but no byte interrupt and not recomment using udma in ESP32.**

1. Does that mean ESP32 don't recommend the uDMA at all or Does it mean that it is not recommended for MODBUS??
2. Does this apply to all their chips or any specific chip are pointed??
3. In ESP32 is it possible to implement by using interrupt instead of polling??
4. In ESP there is no byte interrupt  so how to calculate interbyte delay ??

Thank You!!

**Comment by alisitsyn** [comment]
@dimpalsharm ,

The Modbus spec has two specific times to control timeouts T1.5 (between bytes) and T3.5 (between frames).

> Does that mean ESP32 don't recommend the uDMA at all or Does it mean that it is not recommended for MODBUS??

There is the possibility to implement the Modbus using uDMA however its approach will not satisfy the standard.

> Does this apply to all their chips or any specific chip are pointed??

Yes.

> In ESP32 is it possible to implement by using interrupt instead of polling??

Yes. The interrupt driven Modbus can be implemented. However original requirement was to use universal UART driver in ESP-IDF. The interrupt driven UART can be implemented using driver HAL layer similar to [example](https://github.com/alisitsyn/modbus_support/tree/mb_support/add_uart_isr_hal_example). This approach is being tested in the new version of ESP_Modbus.

> In ESP there is no byte interrupt so how to calculate interbyte delay ??

One of the possible approach is to have the hardware timer setup for T1.5 and read the incomming data from UART FIFO there. If no UART data recieved and timer T1.5 expired then if no bytes in the FIFO during T3.5 time the end of frame condition generated otherwise fix the error receiving frame condition.

**Comment by alisitsyn** [comment]
@dimpalsharm ,

Could you give us some feedback for this issue?

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
