### ISSUE TITLE
idf_monitor.py: allow monitor without resetting target (IDFGH-5963)

### ISSUE THREAD

**Issue by bugadani** [espressif/esp-idf#7651]
**Is your feature request related to a problem? Please describe.**

We have some bugs that occur after a long uptime. It would help if monitor would not reset our system when connected.

**Describe the solution you'd like**

A new command line switch (e.g. `idf.py monitor --running`) that would monitor the serial output of a running target without requiring establishing a connection.

**Describe alternatives you've considered**

* The `idf_monitor.py` shipped with esp-idf 4.2 worked well. We started monitor without connecting the debug wires, then connected our device. Unfortunately, with esp-idf v4.3, the tool requires a connection, therefore it can't be used this way.
* we can use putty or other software, but it lacks the address processing features of idf_monitor.py

**Comment by dobairoland** [comment]
Hi @bugadani. Your request about connecting `idf_monitor.py` to an ESP chip without reset is clear to me.

However, please explain how this relates to esptool used for flashing. After flashing the chip, you need to restart it so the uploaded firmware could start executing. It is possible to keep the chip in bootloader mode and not reset it but that is unusable for you because the firmware won't be executed at all. The update of esptool from v3.0 to v3.1 is not changing the behaviour of `idf_monitor.py`.

**Comment by bugadani** [comment]
@dobairoland I didn't mention flashing at all, since in my use case, there is no flashing involved. The target device is up and running, and has been running for some time when I would like to connect the monitor.

I might be confusing the exact tools involved, though I hope that's not an issue here.

**Comment by dobairoland** [comment]
Thanks for the clarification!
