### ISSUE TITLE
Override ESP panic print handler (IDFGH-5996)

### ISSUE THREAD

**Issue by shreyasbharath** [espressif/esp-idf#7681]
**Is your feature request related to a problem? Please describe.**

We want to be able to capture all the errors/panics that occur on our ESP32 based product. Is there a way to override the panic handler so that we can redirect output to our own console/logs and also keep a count of the number of panics etc.?

**Describe the solution you'd like**

The panic handler provides a `user hook` where it passes the formatted output, which can then be printed to a console or logged somewhere or sent over a network.

**Describe alternatives you've considered**

We've been trying to use the linker wrap option `-Wl,--wrap=panic_print_char` but this seems like a major hack.

**Additional context**

**Comment by o-marshmallow** [comment]
@ammaree Unfortunately, it is not that easy for these functions as they are marked as `static` and/or `inline`. The `inline` functions are unlikely to still be present at linking time, the compiler will inline them and just get rid of the function name/symbol.
For the `static` functions, no matter if the function is inlined or not, the linker won't wrap static functions.

So the only way to go with such functions is to modify the source code (`components/driver/i2c.c` and `components/hal/esp32*/include/hal/uart_ll.h` in our case). If you are not willing to modify it/them, you can let your project's`CMakeLists.txt` patch the file(s) (`components/driver/i2c.c`)  with `sed` command before compiling.

**Comment by mmoskal** [comment]
@o-marshmallow @igrr  do you think it would be possible to move `panic_print_char()` to a separate file, so that it can be wrapped? Right now the references it inside of `panic.c` are not wrappable...

**Comment by o-marshmallow** [comment]
Hi @mmoskal ,
I understand why one would need to do this, but the fact is this function is not meant to be wrapped. Defining it in another file would also make it non-inlinable.

One solution I can think of is force the inclusion of a header file when compiling that lib in order to make `panic_print_char()` weak. Then, in your main component you will be able to define a strong `panic_print_char()` function. All the references to `panic_print_char()` would then result to your function instead of the weak one.

To do so, I will take the `get_started/hello_world` example. In its `CMakeLists.txt` file, add the following line at the end:
```
set_target_properties("__idf_esp_system" PROPERTIES COMPILE_FLAGS "-include ../weakprint.h")
```

Near `CMakeLists.txt` file, define `weakprint.h`,  as:
```
#pragma weak panic_print_char
```

In `main/hello_world_main.c`, you can now define:
```
void panic_print_char (const char c) {
    /* Custom code, count the number of panics or simply print a message */
    esp_rom_printf("Panic has been triggered by the program!\n");
}
```

This is not equivalent to wrapping because you do have access to the weak function, but at least now it will replace all the occurences of `panic_print_char`, even in `esp_system` component (where `panic.c` is part of)

**Comment by matth-x** [comment]
@o-marshmallow Thank you for the guide, I will definitely try it.

One follow up question: Is there a guarantee that the panic handler will be called when the program crashes? It would be relevant for using the panic handler as a safety mechanism, for example to return the GPIOs into a safe state as soon as a program fault occurs.

In the documentation it looks like the panic handler is not supposed to be a safety mechanism though. What's your opinion about it? Thanks!

**Comment by matth-x** [comment]
Okay, thank you. By any chance, can I guarantee to reset the GPIOs with another approach?

**Comment by AAJAY5** [comment]
It is possible to write file using `fwrite` on panic?

**Comment by igrr** [comment]
@AAJAY5 i don't think it's possible. Using fwrite requires multiple system components to be working: C library, VFS, filesystem implementation, RTOS, SPI flash driver. Most of these things will not work in the panic handler, as it is similar to the interrupt handler.
You can store the log buffer in RTC memory instead. This memory will persist after reboot and then you can append it to the file, once the system is running normally.
