### ISSUE TITLE
custom section empty? (IDFGH-5997)

### ISSUE THREAD

**Issue by Dandjinh** [espressif/esp-idf#7682]
declare a custom section
```c
// cmd_handler.h

#define CMD_ITEM_ATTR __attribute__((section(".test.handler")))
#define CMD_ITEM_DEFINE(_cmd, _size, _handler) \
    static CMD_ITEM_ATTR cmd_item_t gs_handler_##_cmd =   \
        {                                      \
            .cmd = _cmd,                       \
            .size = _size,                     \
            .handler = _handler                \
        }
```

define variable with custom section
```c
// cmd_handler_test1.c

static uint32_t gs_test1_count;

static void cmd_test1_handler(void *_data)
{
    ESP_LOGW(TAG, "count = %u", gs_test1_count++);
    if (gs_test1_count >= 1000)
    {
        ESP_LOGW(TAG, "reset to 0");
        gs_test1_count = 0;
    }
}

CMD_ITEM_DEFINE(CMD_TEST1, 8, cmd_test1_handler);
```

setup the lf file
```
[sections:test_handler_section]
entries:
    .test.handler+

[scheme:test_handler]
entries:
    test_handler_section -> dram0_data

[mapping:test_handler_mapping]
archive: libtest_task.a
entries:
    * (test_handler);
        test_handler_section -> dram0_data KEEP() ALIGN(4, pre, post) SURROUND(g_test_handler_section)

```

after built, .map file shows the section is empty
```
// lf_test.map

 *libtest_task.a:(.test.handler .test.handler.*)
                0x000000003ffb2340                . = ALIGN (0x4)
                0x000000003ffb2340                _g_test_handler_section_end = ABSOLUTE (.)
                0x000000003ffb2340                _data_end = ABSOLUTE (.)
                0x000000003ffb2340                . = ALIGN (0x4)
```

and the .ld file seens corrent
```
// sections.ld

    . = ALIGN(4);
    _g_test_handler_section_start = ABSOLUTE(.);
    KEEP(*libtest_task.a:(.test.handler .test.handler.*))
    . = ALIGN(4);
    _g_test_handler_section_end = ABSOLUTE(.);
```

Now, I have no idea how to go on 😞

**Comment by igrr** [comment]
Hi @Dandjinh, it seems that nothing has changed since your previous solution — as explained in my last comment, the linker still has no reason to include your object file cmd_handler_test1.o into the final executable, as this object file doesn't resolve any undefined symbols. There is not something that can be solved by modifying the linker scripts. Please see my last comment again for the ways you can solve this issue.

(`ESP_SYSTEM_INIT_FN` doesn't guarantee that the specific object file will be linked into the application; it gets linked because of some other unresolved symbol, which causes the init function to also be included, and added to the custom section)

**Comment by Zmmfly** [comment]
> Hi @Dandjinh, it seems that nothing has changed since your previous solution — as explained in my last comment, the linker still has no reason to include your object file cmd_handler_test1.o into the final executable, as this object file doesn't resolve any undefined symbols. There is not something that can be solved by modifying the linker scripts. Please see my last comment again for the ways you can solve this issue.
> 
> (`ESP_SYSTEM_INIT_FN` doesn't guarantee that the specific object file will be linked into the application; it gets linked because of some other unresolved symbol, which causes the init function to also be included, and added to the custom section)

According to the current compilation logic, all files are first compiled into static libraries, and then linked at the end; if “KEEP” is added to the linking script at the final linking stage, can the relevant segments be retained?

**Comment by igrr** [comment]
No, KEEP only affects retaining sections which are already chosen to be included into the output file.

In this case the linker won't even consider including the object file into the output file since it doesn't resolve any unresolved symbols.

You can override this logic by adding `-Wl,--whole-archive (your library name) -Wl,--no-whole-archive` to the linker flags of your component.

**Comment by o-marshmallow** [comment]
Hi @Dandjinh,
Any feedback on this?

**Comment by maplerian** [comment]
#### auto_init.lf

```
[sections:auto_init]
entries:
    .auto_init+

[scheme:auto_default]
entries:
    auto_init -> dram0_data

[mapping:auto_init]
archive: *
entries:
    * (auto_default);
    auto_init -> dram0_data KEEP() ALIGN(4, pre, post) SURROUND(auto_init)
```
You can try this link configuration
