### ISSUE TITLE
RTC_NOINIT_ATTR not working (IDFGH-6032)

### ISSUE THREAD

**Issue by baldhead69** [espressif/esp-idf#7718]
Hi,

I'm trying to preserve a data structure with 2 variables bool and 1 variable ​​uint8_t between resets using RTC_NOINIT_ATTR, but the data are not preserved.
I am testing reseting by a reset button on a ESP32-DevKitC-VB.
I dont know if reseting by en pin preserve or not preserve rtc data memory.

idf version: v4.4-dev-2359-g58022f859

h file:
```c
typedef struct 
{
    bool a;
    bool b;
    uint8_t thing;   
}someState_t;    

extern someState_t state;
```

c file:
```c
RTC_NOINIT_ATTR someState_t state;

static void init_someState_struct()
{
    esp_reset_reason_t reset_reason = esp_reset_reason();
    
    if( reset_reason == ESP_RST_POWERON )
    {
        state.a = false;   
        state.b = false;    
        state.thing = 100;    
    }
}
```

**Comment by baldhead69** [comment]
Pressing the reset button is characterized as power on reset ?

I don't remove the power from the circuit.

**Comment by RichFalk** [comment]
The restart reason you showed was ESP_RST_POWERON which is a power-on reset.  A software reset is SW_CPU_RESET which would retain NOINIT section data in RTC RAM.

The EN pin (that I presume the reset button is connected to in order to pull it to GND) is for a hardware reset equivalent to a power-on reset.  See [ESP32-DevKitC V4 Getting Started Guide - Functional Description](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html#functional-description).

If you want to save information over power cycles or hardware reset, you can use the non-volatile storage (NVS) system that stores data in Flash (there is no EEPROM in the ESP32).

**Comment by baldhead69** [comment]
Hi, 

I only want to test the functionality of RTC_NOINIT_ATTR.

I assumed that hardware reset did not reset rtc ram, only the power cycle would reset the rtc ram memory, for this reason my if no reset reason.  I want to preserve the data structure in a possible system crash/reset.

Thank's.

**Comment by baldhead69** [comment]
Thank`s @RichFalk 

it's working now with "esp_restart();".

My goal is to restore the system to the state it was in before the crash, so that the system user has a good impression of it if the system crashes(sporadic crash).

**Comment by rob040** [comment]
@RichFalk: Although this is an old issue, it appears still to be true.

Above, you state 'Power on reset does not preserve RTC RAM'. That appears to be true, but I like to understand why? What makes a power-on reset (HW reset pulling the EN pin low) different from an SW restart ? 
In the __NOINIT_ATTR and RTC_NOINIT_ATTR locations I read some pseudo random data after HW reset. Is it some bootloader that uses that memory? Is it because it is MMU mapped?
What memory (-segment) can be expected to be undisturbed when HW reset occurs and device remains powered?

Background: I am making a double reset detector, in order to enter a configuration mode, or in general, enter an alternative startup mode. In my opinion, it is unwise to use NVS that involves flash writes in a moment of time when you can expect HW resets.

**Comment by RichFalk** [comment]
@rob040 RAM cannot be preserved when there is no power.  A hardware reset is equivalent to powering off and then powering on the chip so during power off with no power then RAM is not retained.  I don't know exactly what a hardware reset does internally but its intention is to do the same things a physical powering off and then on of the chip would do including resetting of chip registers and GPIO to defaults in a way that is the same as powering on.  All RAM is handled in the same way as well in that it will not be preserved across a hardware reset.  So basically just treat a hardware reset as doing the same thing as a physical power off then on cycling and clearly that isn't going to retain any RAM memory.

If you are trying to detect double resets you are most likely trying to detect some sort of software reset in which case the use of RTC RAM should work for that purpose.  Instead **if you are seeing actual power resets where the esp_reset_reason is POWERON (1) and the soc_reset_reason is CHIP_POWER_ON (1) then there is no way you can use RAM to log this such as counting how many times it occurs**.

Your concern about NVS for multiple reset detection isn't an issue with one caveat I will explain.  The way the ESP-IDF NVS code is written **NVS is safe to use even if there is an interruption from a restart or power cut**.  The reason is that they write to Flash in an order where incomplete states do not cause a problem.  The last write essentially writes a bit (entry state) that enables the new entry and if this is a modification then the old entry is not deleted until the new one is written and the system handles having both and will clean that up later.  See [NVS "Internals"](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/nvs_flash.html#internals).  We do logging to NVS during startup so I've seen multiple resets and log those with no issue (with the caveat below).

**There is an issue with Flash corruption that can occur during a power cycling**, most likely during power off and not on.  It's a 1-bit corruption in Flash at a random location.  It turns a bit from 1 into 0 which is the only direction one can write to Flash as going from 0 to 1 requires an erasure (and Flash is initialized as all bits with 1).  We saw this problem come up with higher frequency when our manufacturing was sometimes powering on and off our unit in an unsafe way where it could cause unclean powering with sparking and brownouts.  The chip shouldn't have this problem but it does and when we reported it to Espressif it didn't get addressed because it wasn't easily reproducible.  We enforced the test fixture procedures to make sure the operators physically connected to power lines when they were off and having power enabled and disabled via the power supply (they were supposed to do it that way but some operators tried to speed up their work by connecting/disconnecting powered wires).

I also added Flash corruption detection and correction so that even when this happens it would be handled 95% of the time (I can't handle corruption of the bootloader nor of NVS or other areas with actual data).  Detection and correction is possible during startup in the two large copies of code in Flash due to CRC checking and checking empty sectors being all erased (we make sure to erase the entire partition when loading new firmware) and can be corrected by copying the "good" firmware copy to the "bad" one so we always have both copies be the same, essentially treating one as a backup for the other.  We also detect and correct in our Flash partition for logging and for saved Wi-Fi messages where most of the space is empty so is kept in erased (bits as 1) state so we can detect any random one getting to 0 and can fix that at least at the sector level (16 pages).  We did this to handle the occasional failure in the field since our device is battery operated so sometimes users replacing batteries could cause the corruption issue.  If one doesn't do this sort of protection, then a corrupted bit can end up bricking the device in the field (i.e. no longer remotely updatable).
