### ISSUE TITLE
Correct usage of "CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL" (IDFGH-6106)

### ISSUE THREAD

**Issue by BitProgress** [espressif/esp-idf#7784]
I am trying to free up as much IRAM as possible, and are using all the different configuration settings in the SDK.
In our product we receive a 70KB json configuration file, which is parsed by a library.
I believe the parsing will result in a lot of memory allocations, which mostly will be very small.

It looks like, that the parsed configuration is mostly stored in the IRAM. Therefore I tried to change "CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL" to a very small number (8), and that caused the IRAM to increase very much.

What is the drawback of setting the "CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL" very low - except of decrease of performance.

Is it correct, that if most of the allocations at runtime is small (less than CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL), the IRAM will reach 0 at some point in time - even though the data would fit in SPI RAM. I suppose the allocation will happen in SPI RAM, when IRAM reaches 0...

I am just worried about hitting 0 IRAM, and a new allocation is required, which MUST happen in IRAM.

Would it make sense with a better description of a real world problem in documentation?

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by BitProgress** [comment]
@Alvin1Zhang Yes, we managed to create a custom memory manager for rapidjson. That solved half of the problem. But another strange thing was observed regarding forcing use of external SPIRAM: https://github.com/espressif/esp-idf/issues/7862

**Comment by phatpaul** [comment]
I was looking for an example and benchmark of using RapidJSON in ESP-IDF and I only found this issue.  Can you please share your experience?  Does it perform better than cJSON?  I'm looking at other json parsers because cJSON is taking several seconds to parse a ~60kB json file.  (I'm not entirely sure it is cJSON that is the slow part.  I'm reading the file from the internal flash FAT filesystem and buffering it to PSRAM before parsing it by cJSON).
