### ISSUE TITLE
How do I set 1 nano second timer in esp32 ? (IDFGH-6278)

### ISSUE THREAD

**Issue by enthunilu** [espressif/esp-idf#7947]
## Environment

Development Kit: ESP32-Mini-1
Kit version
Module or chip used: ESP32
IDF version :v4.2.1
Build System: Make|CMake|idf.py
Compiler version : xtensa-esp32-elf-gcc (crosstool NCG esp-2020r3)8.4.0
Operating System: Windows
(Windows only) environment type: Command Prompt
Using an IDE?: Yes (Eclipse)

Power Supply: USB
## Problem Description

//Detailed problem description goes here.
I am trying to implement 1 nano second timer for my esp32 board.
This I am looking for, to check time taken by my function/handler.
 
So, could you please help me with this. 

Thanks!!

**Comment by o-marshmallow** [comment]
Hi @enthunilu ,

The simplest way to get the time a function took to execute is to use `int64_t esp_timer_get_time(void)`. This returns the elapsed time, in microseconds, since boot. so you can do something like:
```
void app_main () {
    int64_t first = esp_timer_get_time();
    function_to_bench();
    int64_t second = esp_timer_get_time();
    /* Calculate elapsed time within function_to_bench */
    int64_t elapsed = second - first;
    printf("Elapsed: %lld\n", elapsed);
   [...]
}
```

However, I not sure what you mean by "1 nano second timer". `esp_timer_get_time()` returns microseconds, so even if this function takes less than 1us to execute, you won't have a precise nanosecond value.
Moreover, ESP32 CPU is running at 240MHz, which is 1 clock cycle every 4ns. It means that even the simplest instruction, `nop`, would take at least 4ns.

**Comment by negativekelvin** [comment]
esp_cpu_get_ccount and esp_clk_cpu_freq

**Comment by enthunilu** [comment]
Thank you so much @o-marshmallow and @negativekelvin for your quick response. 
For me both options will work. Thank you again!!

**Comment by o-marshmallow** [comment]
You're welcome :+1:
Closing this issue.
