### ISSUE TITLE
Failed to initialize SPIFFS (ESP_ERR_INVALID_STATE) (IDFGH-6329)

### ISSUE THREAD

**Issue by enthusisastSR** [espressif/esp-idf#7991]
Hello,

I am unable to figure out what goes wrong when I try to upload spiffs. Please find the details below:

Partition table:
# Name, Type, SubType, Offset, Size, Flags
nvs, data, nvs, 0x9000, 0x4000,
otadata, data, ota, 0xd000, 0x2000,
phy_init, data, phy, 0xf000, 0x1000,
factory, app, factory, 0x10000, 512K,
ota_0, app, ota_0, 0xd0000, 512K,
ota_1, app, ota_1, 0x190000, 512K,
data, data, spiffs, 0x250000, 512K,
hwinfo, data, nvs, 0x2d0000, 0x3000

My code to initialze and upload:
Code: [Select all] [Expand/Collapse]

 ```
   [ESP_LOGI(TAG, "Initializing SPIFFS");
      esp_vfs_spiffs_conf_t conf = {
          .base_path = "/data",
          .partition_label = "data",
          .max_files = 5,
          .format_if_mount_failed = true,
      };
     
      esp_err_t ret = esp_vfs_spiffs_register(&conf);
      if (ret != ESP_OK)
      {
        if (ret == ESP_FAIL)
        {
          ESP_LOGE(TAG, "Failed to mount or format filesystem");
        }
        else if (ret == ESP_ERR_NOT_FOUND)
        {
          ESP_LOGE(TAG, "Failed to find SPIFFS partition");
        }
        else
        {
          ESP_LOGE(TAG, "Failed to initialize SPIFFS (%s)", esp_err_to_name(ret));
        }
        return;
      }
      size_t total = 0, used = 0;
      ret = esp_spiffs_info(conf.partition_label, &total, &used);
      if (ret != ESP_OK)
      {
        ESP_LOGE(TAG, "Failed to get SPIFFS partition information (%s)", esp_err_to_name(ret));
      }
      else
      {
        ESP_LOGI(TAG, "Partition size: total: %d, used: %d", total, used);
      }
     
      if (l_Addr == 0x1E800)
      {
        FILE *f1 = NULL;
        f1 = fopen("/data/mem.bin", "w");
        ESP_LOGI(TAG, "file opened to append");
        if (f1 != NULL)
        {
          fwrite(ringBuf_begin(pCmd->data) + 9, l_Len, 256, f1);
          ESP_LOGI(TAG, "firmware appended to flash");
        }
```

**Comment by o-marshmallow** [comment]
Hi @enthusisastSR ,
I am not sure to understand, you say you cannot upload your spiffs partition to your board but the debug log shows the line:
```
I (101) boot:  6 data             Unknown data     01 fe 00250000 00080000
```
which is the partition you are trying to open from your code.

I also noticed that you are flashing `factory.bin` to the address `0x2d0000`, but the partition table shows that this address corresponds to hwinfo partition:
```
I (109) boot:  7 hwinfo           WiFi data        01 02 002d0000 00003000
```

Is `factory.bin` the data partition you are trying to open in your code? What about `/data` partition? Where does it come from? If it's your spiffs data partition, then in the log, we can see that `/data` partition is of type `phy` (0x1) instead of `nvs` (0x2).
So can you please show us your `factory.csv` file and your partition CSV file (the one that contains your project partitions)?

**Comment by enthusisastSR** [comment]
Thank you @o-marshmallow. I have it working now. The problem was it was already initialized in my repository. So since I was trying to initialize it again I was running into this error. /data is custom partition type.

**Comment by o-marshmallow** [comment]
@enthusisastSR Great, thanks for coming back with the solution!
