### ISSUE TITLE
Can't run websocket server example (IDFGH-6401)

### ISSUE THREAD

**Issue by Barabas5532** [espressif/esp-idf#8060]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it): v4.3.1
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:     Arch Linux
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

When trying to run `python ws_server_example_test.py` in `examples/protocols/http_server/ws_echo_server`, I get errors from python.

First I get `ModuleNotFoundError: No module named 'ttfw_idf'`. This is resolved by executing the commands from https://github.com/espressif/esp-idf/issues/7815#issuecomment-958686964.

```
export PYTHONPATH="$IDF_PATH/tools:$IDF_PATH/tools/ci/python_packages"
python -m pip install -r $IDF_PATH/tools/ci/python_packages/ttfw_idf/requirements.txt
```

After this I still get `ModuleNotFoundError: No module named 'websocket'`.

I've done a clean install of esp-idf by removing `~/.espressif` and the issue is still present.

I seems to work if I manually install `websocket-client` by running `python -m pip install websocket-client`, however this defats the point of the virtual environment, so I assume it is a bug.

**Comment by dobairoland** [comment]
Hi @Barabas5532. These tests are not provided primarily to run by customers. Therefore, the interaction with them is not so user-friendly. This package doesn't belong to `ttfw_idf/requirements.txt` because it is not a dependency of `ttfw_idf` (it is not used there at all). The dependency was introduced by the websocket example.

So I think it is fine that the `websocket_client` package needs to be installed manually on top of the other requirements. But I agree that the error message could be more helpful. Thank you for reporting this.
