### ISSUE TITLE
iperf 例程烧录到esp32s3-eye开发板无法输入iperf命令 (IDFGH-6796)

### ISSUE THREAD

**Issue by We-Sky** [espressif/esp-idf#8423]
![image](https://user-images.githubusercontent.com/35215119/154434039-df37a5f8-0876-44cc-b932-90b842a86156.png)
如图：在这里无法输入是怎么回事呢？

**Comment by MaxwellAlan** [comment]
Hi @We-Sky please update some more detais according to the issue template:
## Environment

- Development Kit:      [ESP32-Wrover-Kit|ESP32-DevKitC|ESP32-PICO-Kit|ESP32-LyraT|ESP32-LyraTD-MSC|none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it):
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows|Linux|macOS]
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No|Yes (please give details)]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

//Detailed problem description goes here.

### Expected Behavior

### Actual Behavior

### Steps to reproduce

PS: May be you can using the latest master to retest iperf example.

**Comment by We-Sky** [comment]
**Environment**
开发板：ESP32S3-EYE
IDF version (run git describe --tags to find it): v4.4
Build System:idf.py
Operating System: Windows
Using an IDE?: [No|Yes (please give details)]:VSCODE
Power Supply: [USB|external 5V|external 3.3V|Battery]:USB
**Problem Description**
iperf例程可以正常编译烧录，但是无法在命令行输入iperf的命令

**Comment by MaxwellAlan** [comment]
hi @We-Sky ,
Please using the latest release/v4.4 or master branch to retest. We have fix some USB related issues.
Thanks.
