### ISSUE TITLE
Sha256 for NVS bin file (IDFGH-6955)

### ISSUE THREAD

**Issue by pavithvishnu** [espressif/esp-idf#8575]
Is there way to add/append sha256 values to the NVS binary file.?
 Before flashing it to the esp.

**Comment by igrr** [comment]
Hi @pavithvishnu, [NVS format](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html#structure-of-a-page) doesn't have provisions for SHA256 checksum. NVS binary size should be equal to the size of the partition allocated in the partition table.
NVS format contains internal CRC checks for every entry, so simple data corruption (e.g. due to a partially written NVS binary) will be detected at run time.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, you could also raise a post on our forum https://esp32.com, thanks.
