### ISSUE TITLE
Adc Reading Issue (IDFGH-6968)

### ISSUE THREAD

**Issue by pavithvishnu** [espressif/esp-idf#8588]
I have a problem with ADC Reading in ESP32C3,

my function,
{
int adc1_reading;
adc1_config_width(ADC_WIDTH_BIT_12);
adc1_config_channel_atten(ADC1_CHANNEL_4, ADC_ATTEN_DB_11);
adc1_reading = adc1_get_raw(ADC1_CHANNEL_4);
printf("adc1_reading : %d", adc1_reading);
}

As per the TRM, I configured to 12 bit width and ADC_ATTEN_DB_11 for 2500mV as max.
In that case i should get 4096 form "adc1_get_raw" when my input voltage is 2.5V but am getting as shown below,

input voltage ---------> adc1_reading
2.5V  ---------> 3590(approx)
2.29  --------->  3358(approx)

TRM : [https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/adc.html#adc-attenuation](url)

Can any one explain this ?

**Comment by Icarus113** [comment]
Hi @pavithvishnu , due to the internal reference voltage differences between chips, some chips can measure higher than 2500mV when in `ADC_ATTEN_DB_11`. Besides, you can use [this API](https://github.com/espressif/esp-idf/blob/master/components/esp_adc_cal/include/esp_adc_cal.h#L108) to get a calibrated value. Then you'll know the actual max voltage that your chip can measure.

**Comment by Alvin1Zhang** [comment]
@pavithvishnu Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
