### ISSUE TITLE
i2c.h not found in component (IDFGH-7205)

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#8799]
Hello,

I update my IDF and now in my cutom component header the #include "driver/i2c.h" is no longer found.
With the IDF version from december all worked fine .....

In file included from /home/reiner/DATA/data/programm/esp/mycomponents/components/include/bmx80_helper.h:18,
                 from ../src/main.c:43:
/home/reiner/DATA/data/programm/esp/mycomponents/components/include/i2c_helper.h:18:10: fatal error: driver/i2c.h: No such file or directory
 #include "driver/i2c.h"
          ^~~~~~~~~~~~~~

**Comment by Reiner1210** [comment]
I found it: I need this in my component:

REQUIRES "driver"

But why has it changed ??

**Comment by o-marshmallow** [comment]
Hi @Reiner1210,

As you have found, it is now necessary to explicit the dependency on `driver` component. A refactoring is currently on-going in order to reduce dependencies between lower-level components (such as `hal` or `soc`) and higher-level components (such as `esp_system` or `driver`). One of the consequences of this is to remove `driver` as part of the common components, thus, any component using `driver` shall now explicit it with `REQUIRES` or `PRIV_REQUIRES`

**Comment by o-marshmallow** [comment]
Closing this issue
