### ISSUE TITLE
Micropython memory allocation failed, allocating 176401 bytes when there is sufficient memory (IDFGH-7224)

### ISSUE THREAD

**Issue by MATTYGILO** [espressif/esp-idf#8818]
## Environment

- Development Kit:      ESP32S3 
- Module or chip used:  ?
- IDF version (run ``git describe --tags`` to find it): v4.4
- Build System:         ?
- Operating System:     macOS
- Using an IDE?: Pycharm
- Power Supply:         USB

## Problem Description
I'm running the esp32 using Micropython and trying to read a 176400 bytes from a wav file on an sd card that exists. I also print how much memory is free. 2350416 bytes free. Why can't I allocate the bytes???
`print(gc.mem_free())` => `2350416`

### Expected Behavior
Read the bytes
### Actual Behavior
`memory allocation failed, allocating 176401 bytes`

So
```
read_data = fid.read(176400)
## ERRORR ABOVE ##

# Convert to samples
data = np.asarray([struct.unpack("<h", read_data[i * 2:(i + 1) * 2])[0] for i in range(len(read_data) // 2)])

```

**Comment by igrr** [comment]
Hi @MATTYGILO,
Heap memory may be fragmented. Although the sum of all fragments may exceed the size you require, there may not be a sufficiently long continuous chunk to fit this array.
In ESP-IDF, `[heap_caps_get_largest_free_block()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/mem_alloc.html#_CPPv432heap_caps_get_largest_free_block8uint32_t)` function is available to find the size of the largest continuous block in heap. Please see [the docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html#heap-information) for more information. 

Micropython has its own heap, separate from ESP-IDF one. I think there is a function `micropython.mem_info()` which prints information about Micropython heap. You may find more information on Micropython heap on Micropython forums and documentation. https://forum.micropython.org/viewtopic.php?t=1260 seems like a good place to start.

I'll close the issue since it doesn't seem to be related to ESP-IDF project.
