### ISSUE TITLE
Register Uart Interrupt Handling without losing the default one (IDFGH-7336)

### ISSUE THREAD

**Issue by carlessole** [espressif/esp-idf#8922]
Module or chip used: ESP32-WROVER (With ESP_PROG)
IDF version: v4.3
Build System: CMake/idf.py (usingEclipse Plugin)
Compiler version: esp-2020r3-8.4.0
Operating System: Windows
(Windows only) environment type: -.
Using an IDE?: Yes. Eclipse + ESP-IDF plugin
Power Supply: USB

Hello,
For my current needs I need to perform some custom actions on some Uart Interrupts. I have seen that custom interrupts can be installed (https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-reference/peripherals/uart.html?highlight=uart#using-interrupts) calling [uart_isr_register](https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-reference/peripherals/uart.html?highlight=uart#_CPPv417uart_isr_register11uart_port_tPFvPvEPviP17uart_isr_handle_t) but then, default 'uart_rx_intr_handler_default' is lost right?

If currently that is not possible, I think that it should be nice to register your custom interrupt being able to call the default one also (after or before the custom).

Thanks

**Comment by o-marshmallow** [comment]
Hi @carlessole ,

As you said, the default handler is "lost" if you install your own handler. The only way to retrieve it would be to re-install the driver with `uart_driver_install`, but still, you won't get the default handler address.
A "dirty" way of doing it would be to install a wrapper around `uart_register_isr` in order to get the default ISR address when the driver is installed. It would look like this:
```
extern esp_err_t __real_uart_isr_register(uart_port_t uart_num, void (*fn)(void *), void *arg, int intr_alloc_flags,  uart_isr_handle_t *handle);
static bool save_isr = false;
void (*uart_isr)(void*) = NULL

esp_err_t _wrap_uart_isr_register(uart_port_t uart_num, void (*fn)(void *), void *arg, int intr_alloc_flags,  uart_isr_handle_t *handle) {
    if (save_isr) {
        uart_isr = fn;
    }
    return __real_uart_isr_register(uart_num, fn, arg, intr_alloc_flags, handle);
}

void my_custom_isr(void*) {
    [...]
    if (uart_isr)
        uart_isr();
    [...]
}

void app_main(void) {
    [...]
    save_isr = true;
    uart_driver_install(...);
    save_isr = false;
    [...]
    uart_isr_register(..., my_custom_isr, ...);
}
```

What happens here is that when uart_driver_install is called, inside, instead of calling `uart_isr_register` directly, it will call `_wrap_uart_isr_register` , where we save the parameter `fn`, which is the default ISR address.

We can then re-use this saved address in the `my_custom_isr` handler.

**Note:** In order to wrap the `uart_isr_register` function, it is necessary to add the following line to the project's `CMakeLists.txt` file:
```
idf_build_set_property(COMPILE_OPTIONS "-Wl,--wrap=uart_isr_register" APPEND)
```
