### ISSUE TITLE
Unknown CMake command "fatfs_create_spiflash_image" (IDFGH-7363)

### ISSUE THREAD

**Issue by MadDogMayCry0** [espressif/esp-idf#8944]
esp-idf 1.4.0 @ vscode extension

when i put it to CMakeList.txt
```fatfs_create_spiflash_image(storage ../files FLASH_IN_PROJECT)```

```
CMake Error at main/CMakeLists.txt:2 
(fatfs_create_spiflash_image) 
Unknown CMake command "fatfs_create_spiflash_image".
```
i tryed this one
```
spiffs_create_partition_image(storage ../spiffs_image FLASH_IN_PROJECT)
```
and this works well.
that's it

**Comment by igrr** [comment]
@MadDogMayCry0 the feature to generate FatFS partitions is new, it has been introduced on the `master` branch only and isn't present in any of the released versions yet.
You have probably met the issue because you have tried to compile an example provided on the `master` branch with and older version of esp-idf.

**Comment by MadDogMayCry0** [comment]
> @MadDogMayCry0 the feature to generate FatFS partitions is new, it has been introduced on the `master` branch only and isn't present in any of the released versions yet. You have probably met the issue because you have tried to compile an example provided on the `master` branch with and older version of esp-idf.

That's what I thought :)
