### ISSUE TITLE
How to install json-c library in the espressif IDE (IDFGH-7457)

### ISSUE THREAD

**Issue by vinothkrstatiq** [espressif/esp-idf#9031]
In the link below library is given 
https://github.com/json-c/json-c

After installing the library i have to include like
#include <json.h>

**Comment by igrr** [comment]
Hi @vinothkrstatiq, the issue tracker of the ESP-IDF project is intended for bug reports and feature requests, not for coding advice. Please consult [the examples](https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/import_lib) and [the documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#using-third-party-cmake-projects-with-components) on adding third party libraries to ESP-IDF projects.

Since ESP-IDF already includes cJSON library as a component and another library, [jsmn](https://github.com/espressif/idf-extra-components/tree/master/jsmn), is available via the IDF Component Manager, it is unlikely that we will be supporting a third one. Of course, nothing prevents you or someone else from making a wrapper component around json-c, but this is out of scope of this issue tracker.

If in the process you run into some problem which you believe is a bug in ESP-IDF build system or the IDE, please feel free to open a specific issue.
