### ISSUE TITLE
Wifi reception blocked after BLE provisioning stopped (IDFGH-7654)

### ISSUE THREAD

**Issue by IrianGT** [espressif/esp-idf#9204]
Hi, 

We are working on a project with an ESP-WROOM-32D wich use unified provisioning to connect to a wifi access point through BLE.

The provisioning works very well. The only problem we have is that after the provisioning is stopped, our server send a rpc request through mqtt to the esp but this request takes more than 10 seconds to be received (We can see TCP retransmission with wireshark). After more than 10 seconds the ESP32 receives the request. 

This delay does not appear at 100%. And if we connect the ESP32 to a Windows Hotspot, it happens that the ESP32 never receives the request and ends up disconnecting without triggering the 'WIFI DISCONNECT' event. 

If we do an esp_wifi_connect just after the provisioning is stopped, there is no problem. 
It seems that the wifi reception is blocked after the provisioning is stopped but we don't know why. It was found that if the ESP32 was sending data via wifi (instead of waiting to receive it), the problem did not appear either. 

For information we use custom data handlers for provisioning to connect the ESP32 to our server. If we remove these custom handlers, the bug does not appear but it is not a solution. 

We use the ESP-IDF version on the following commit https://github.com/espressif/esp-idf/commit/48997e82c00f745afa7da0b254511cb40d04de9b (which is placed between 4.3.1 and 4.3.2). 
We realized that this bug disappeared by using a higher version than this commit: https://github.com/espressif/esp-idf/commit/b137ae42592ef67a4f145c3d067dafca0d6bf612

This commit has big changes on the lib of the esp_wifi component but we don't understand well what relation it can have with our problem?

Thanks for your help !

## Environment

- Development Kit: ESP32-DevKitC
- Kit version : v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version : 48997e82c00f745afa7da0b254511cb40d04de9b 
- Build System:  idf.py
- Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2) 8.4.0
- Operating System:  Linux (In docker host : Windows)
- Using an IDE?: dev container (vs code)
- Power Supply:  external 3.3V

**Comment by Espressif-liuuuu** [comment]
Hi @IrianGT , thanks for your report!
If I understand correctly, it appears to be you could not receive data on ESP32 through WiFi after it connected to AP, unless you have transmited something. While there is no such problem on https://github.com/espressif/esp-idf/commit/b137ae42592ef67a4f145c3d067dafca0d6bf612.
The reason for this issue is that we made some mistake on internal WiFi status, which sometimes led to no null data sent to AP even if AP noticed us there is buffered data. We fixed this issue at https://github.com/espressif/esp-idf/commit/b137ae42592ef67a4f145c3d067dafca0d6bf612 and you dont need to worry about that reception blocked happen again:)

**Comment by IrianGT** [comment]
Hi @Espressif-liuuuu, thanks for your support! 
This corroborates well with the tests we have done. 

Our next software release is next week so this is too late for us to validate a change on the esp-idf version :) .  We'll make the switch to the esp-idf V4.3.3 on a further release! 

Thank  you for your help !
Have a nice day ! This issue can be closed !
