### ISSUE TITLE
This script should be sourced, not executed: (IDFGH-7831)

### ISSUE THREAD

**Issue by zghnx** [espressif/esp-idf#9360]
![微信截图_20220715200451](https://user-images.githubusercontent.com/80946720/179219583-dadf7c67-efc0-4c9f-a4ec-e37ae2f9f2ac.png)

**Comment by igrr** [comment]
@zghnx That suggestion means that you should run the script like this:
```bash
. ./export.sh
```
instead of
```
./export.sh
```
This is required because the script is supposed to update the environment variables in your shell. That is only possible when "sourcing" the script rather than executing. More on this [here](https://superuser.com/q/176783).
