### ISSUE TITLE
spi_flash_get_chip_size () is gone with v5.0-dev-4037 (IDFGH-7855)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#9382]
## Environment
```
$ idf.py --version
ESP-IDF v5.0-dev-4037-g9b8c558e63
```

## Problem Description
I updated from ESP-IDF v5.0-dev-3202 to ESP-IDF v5.0-dev-4037

spi_flash_get_chip_size () is gone

### Code to reproduce this issue

```cpp
#include "stdio.h"

#include "esp_spi_flash.h"
//#include "spi_flash_mmap.h" // V5

void app_main()
{
    spi_flash_get_chip_size();
}
```

## Debug Logs

```
In file included from ../main/main.c:8:
/home/nop/esp-idf/components/spi_flash/include/esp_spi_flash.h:6:2: warning: #warning esp_spi_flash.h is deprecated, please use spi_flash_mmap.h instead [-Wcpp]
    6 | #warning esp_spi_flash.h is deprecated, please use spi_flash_mmap.h instead
      |  ^~~~~~~
../main/main.c: In function 'app_main':
../main/main.c:13:9: error: implicit declaration of function 'spi_flash_get_chip_size' [-Werror=implicit-function-declaration]
   13 |         spi_flash_get_chip_size();
      |         ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
[1/1] cd /home/nop/rtos/test/build/bootloader/esp-idf/...00 /home/nop/rtos/test/build/bootloader/bootloader.binBootloader binary size 0x6690 bytes. 0x970 bytes (8%) free.
ninja: build stopped: subcommand failed.
```

**Comment by AxelLin** [comment]
It's removed by a690a87829a73019c8e7011ec7b16ff37dbdf02d.
Use esp_flash_get_size instead:
```
-    size_t size_flash_chip = spi_flash_get_chip_size();
+    uint32_t size_flash_chip;
+    esp_flash_get_size(NULL, &size_flash_chip);
```

**Comment by nopnop2002** [comment]
@AxelLin 

Thank you.
It work.

```
#include "stdio.h"

//#include "esp_spi_flash.h"
#include "esp_flash.h" // V5

void app_main()
{
    //spi_flash_get_chip_size();
    uint32_t size_flash_chip;
    esp_flash_get_size(NULL, &size_flash_chip);
    printf("size_flash_chip=%d\n", size_flash_chip);
}
```

**Comment by damago1** [comment]
Please note that esp_flash_get_size() is NOT returning the real chip size so it is NOT an replacement for spi_flash_get_chip_size(). 

Please note, that esp_flash_get_size() is only returning the partition table size as configured in your project and not the real size of your chip. So if you did create partition table for 4MB chip, and than flashed it to 16MB chip - you will get the size of 4MB instead of real 16MB size. 

The only known to me method of determining chip size is by getting chip ID using esp_flash_read_id(esp_flash_default_chip, &flash_id); and then taking the known chip id's and decoding sizes from them.  But be aware, that there is no universal method of converting the last byte of ID (size code) to real sizes. So you need to build a database of flash chips known to you. 

Some other users reported that they can try to erase last sector of known chip sizes (16MB, 8MB, 4MB etc) and note for which sizes the operation failed. This is a destructive method of getting real chip size. 

For now I do not see any reliable method of getting real chip size programmaticly.
