### ISSUE TITLE
Would esp-idf generate a custom waveform for esp32s3 using lcd peripheral (IDFGH-8095)

### ISSUE THREAD

**Issue by PickaxeHit** [espressif/esp-idf#9596]
**Describe the solution you'd like**

Hi there,
I want to generate a custom waveform to drive a special display. It isn't a existing protocol (i8080, moto6800, spi or i2c). but they are similar(8-bit parallel, hsync and vsync(not in the same name)), and it has some new signals to drive the display, and different data stream(2-bit per pixel and 4-pixel per period of clock). Could  esp-idf to generate the custom waveform?

**Describe alternatives you've considered**

I tried to use I2S peripheral to generate this, but it doesn't work.

**Additional context**

Here are the waveform(s) I want to generate.
![image](https://user-images.githubusercontent.com/95094338/185729826-f24038f7-b631-4f86-883d-e4fe8c7a7eeb.png)
( Horizontal input timing )
![image](https://user-images.githubusercontent.com/95094338/185729850-5a7c3f65-79a3-436e-9214-405d6e6ec0a4.png)
( Vertical input timing )
![image](https://user-images.githubusercontent.com/95094338/185729863-2d7fe52c-6647-413f-bc8d-810061d3a6c6.png)
( VCOM input to control the grayscale )

**Comment by suda-morris** [comment]
I'm afraid the esp_lcd driver can't generate the waveforms as described because it involves some signals that are not required by standard RGB timing. The hardware peripheral can't generate these signals automatically. But IMO it's doable by writing a dedicated driver with HAL/LL driver APIs. The missing signals can be simulated by `gpio_set_level`. However, we can't take use of a "circle DMA ring buffer". Instead, we need to trigger the LCD flush manually in a loop.
