### ISSUE TITLE
Whether I should add external pull-up resistor or not for I2C pin? (IDFGH-8310)

### ISSUE THREAD

**Issue by BrandonStudio** [espressif/esp-idf#9791]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

You have contradictory versions about this:

On https://github.com/espressif/esp-idf/blob/36f49f361c001b49c538364056bc5d2d04c6f321/tools/test_apps/peripherals/i2c_wifi/README.md, you say:
> Note: It is recommended to add external pull-up resistors for SDA/SCL pins to make the communication more stable, though the driver will enable internal pull-up resistors.

whereas on https://github.com/espressif/esp-idf/blob/36f49f361c001b49c538364056bc5d2d04c6f321/examples/peripherals/i2c/i2c_tools/README.md, you say:
> **Note: ** There’s no need to add an external pull-up resistors for SDA/SCL pin, because the driver will enable the internal pull-up resistors itself.

![image](https://user-images.githubusercontent.com/55647556/190347554-378c3626-6771-463b-936b-9357b0c118e1.png)

Which one should I believe?

**Comment by mythbuster5** [comment]
@BrandonStudio You can see the update date is different.

Well, let me make a conclusion, the docs say `no need to pull-up external` on theory is correct, because we do have internal pull-up to support this. The reason why new docs say `user should pull up` is because we found the I2C slave users used are very very different. Sometimes the capacity will influence the frequency that user should adjust resistor. Sometimes users feel internal pull-ups are not strong enough.

So, new docs and technical reference manual both say `user should choose proper external pull-up resistors`. Of course, the old one is out of date and need to be updated, thanks so much.
