### ISSUE TITLE
[TW#15302] Arduino BLE Client Notification Subscribe/Read Error

### ISSUE THREAD

**Issue by WALLTECH** [espressif/esp-idf#981]
Hello,
In our work and testing over on the ESP Arduino repo, I've run into a debug line that's causing any reading of characteristics or their notifications to be ignored and I don't want them to. How can this be fixed? I'm trying to read from a known working peripheral when used with curieBLE or nRF connect.

E (51039) BT: bta_gattc_cmpl_cback unknown conn_id = 3, ignore data

**Comment by Weijian-Espressif** [comment]
hi @WALLTECH , please give me more log information to locate the problem.

**Comment by nkolban** [comment]
Over the last week, the ESP-IDF BLE API changed and that required rework of our Arduino BLE libraries.  We have done that but are now suffering an inability to compile C++ applications because of an apparent problem in the latest toolchain (see #1032).  Unfortunately until we can compile C++ classes as described in that issue, we are going to be somewhat stuck in giving you more log diagnostics (I think).

**Comment by FayeY** [comment]
Any update about this issue?
