### ISSUE TITLE
how can I operate the MQTT related functions separately in the task? (IDFGH-8402)

### ISSUE THREAD

**Issue by Beanv587** [espressif/esp-idf#9869]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Development environment:
Windows+VSCode+Espressif extension
ESP-IDF version: 4.4.2
Chip: ESP32-S3

I put the MQTT client handle in the global variable: static esp_mqtt_client_handle_t xclient;

Then complete the initialization configuration and register MQTT events in mqtt_app_start and start:
xclient = esp_mqtt_client_init(&mqtt_cfg);
esp_mqtt_client_register_event(xclient, ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);
esp_mqtt_client_start(xclient);

Create a task in app_main:
xTaskCreate(vWaitTask, "Task1", ​​1024, NULL, tskIDLE_PRIORITY, &TaskHandle);

Set the flag after judging that the connection is successful in mqtt_event_handler:
case MQTT_EVENT_CONNECTED:
ESP_LOGI(TAG, "MQTT_EVENT_CONNECTED");
xWait = true;

Operate MQTT separately in tasks
void vWaitTask(void *pvParameters)
{
int msg_id;
while(true){
if (xWait == true){
xWait = false;
//As long as the functions of the esp_mqtt_client_publish, esp_mqtt_client_subscribe or esp_mqtt_client_xx series are called here, all the functions will crash...
}
// Check mark every 100ms
vTaskDelay(100 / portTICK_RATE_MS);
}
}

So my question is how can I operate the MQTT related functions separately in the task? I put all the calls into mqtt_event_handler and it all succeeds. Once I put a separate task, it crashes..

**Comment by nopnop2002** [comment]
@Beanv587 


Refer to this.


https://github.com/nopnop2002/esp-idf-mqtt-camera/blob/master/main/mqtt_sub.c

**Comment by douzi3322** [comment]
@nopnop2002 I give it a try, thank you very much.

**Comment by Beanv587** [comment]
@nopnop2002 I give it a try, thank you very much.

**Comment by euripedesrocha** [comment]
Hi @Beanv587, as suggested, it's possible that you are suffering from some concurrency issue in your code. 
It should be possible to operate the client from a different task without issues. 

Could you please share some logs showing the crash, so we can understand better what is happening?

**Comment by Kakomis** [comment]
Hi, I have a similar issue, as @nopnop2002 suggested I used **xTaskNotify** and **xTaskNotifyWait**. In my case I'm using single use mqtt credentials so I have to handle reconnection by my own, I have this:

```c
static void mqtt_event_handler(void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)
{
  esp_mqtt_event_handle_t event = event_data;

  switch ((esp_mqtt_event_id_t)event_id)
  {
  case MQTT_EVENT_CONNECTED:
    ESP_LOGI(TAGO, "MQTT_EVENT_CONNECTED");
    xTaskNotify(taskHandle, MQTT_CONNECTED, eSetValueWithOverwrite);
    break;
  case MQTT_EVENT_DISCONNECTED:
    ESP_LOGI(TAGO, "MQTT_EVENT_DISCONNECTED, msg_id=%d", event->msg_id);
    xTaskNotify(taskHandle, WIFI_CONNECTED, eSetValueWithOverwrite);
    break;
  case MQTT_EVENT_SUBSCRIBED:
    ESP_LOGI(TAGO, "MQTT_EVENT_SUBSCRIBED, msg_id=%d", event->msg_id);
    xTaskNotify(taskHandle, MQTT_SUBSCRIBED, eSetValueWithOverwrite);
    break;
  case MQTT_EVENT_UNSUBSCRIBED:
    ESP_LOGI(TAGO, "MQTT_EVENT_UNSUBSCRIBED, msg_id=%d", event->msg_id);
    break;
  case MQTT_EVENT_PUBLISHED:
    ESP_LOGI(TAGO, "MQTT_EVENT_PUBLISHED, msg_id=%d", event->msg_id);
    break;
  case MQTT_EVENT_DATA:
    ESP_LOGI(TAGO, "MQTT_EVENT_DATA");
    process_incoming_msg(event->topic, event->topic_len, event->data, event->data_len);
    break;
  case MQTT_EVENT_ERROR:
    ESP_LOGI(TAGO, "MQTT_EVENT_ERROR");
    break;
  default:
    ESP_LOGI(TAGO, "Other event id: %d", event->event_id);
    break;
  }
}
```
```c
void onConnected(void *params)
{
  uint32_t command = 0;
  esp_mqtt_client_handle_t client = NULL;

  while (true)
  {
    xTaskNotifyWait(0, 0, &command, portMAX_DELAY);
    switch (command)
    {
    case WIFI_CONNECTED:
      ESP_LOGI(TAGO, "WIFI_CONNECTED");
      get_mqtt_credentials(); // <-- here GOT_CREDENTIALS is called.
      break;
    case GOT_CREDENTIALS:
    {
      esp_mqtt_client_config_t mqttConfig = {
          .uri = "mqtts://my.mqtt.server:8883",
          .cert_pem = (char *)cert,
          .client_id = get_randomId(),
          .username = mqtt_data.user,
          .password = mqtt_data.pass,
          .keepalive = (int)60,
      };

      ESP_LOGI(TAGO, "[APP] 1 Free memory: %d bytes", esp_get_free_heap_size());

      if (client != NULL)
      {
        toggle_led(false);
        esp_mqtt_client_destroy(client);
      }

      ESP_LOGI(TAGO, "[APP] 2 Free memory: %d bytes", esp_get_free_heap_size());

      client = esp_mqtt_client_init(&mqttConfig);
      esp_mqtt_client_register_event(client, ESP_EVENT_ANY_ID, mqtt_event_handler, client);
      esp_mqtt_client_start(client);
    }
    break;
    case MQTT_CONNECTED:
    {
      toggle_led(true);
      char topic[64] = "";
      strcat(topic, mqtt_data.topic);
      strcat(topic, "+/actdata");
      esp_mqtt_client_subscribe(client, topic, 1);
    }
    break;
    case MQTT_SUBSCRIBED:
    {
      publish_data_t publish_data;
      if (xQueueReceive(queue, &publish_data, portMAX_DELAY))
      {
        esp_mqtt_client_publish(client, publish_data.topic, publish_data.payload, strlen(publish_data.payload), 1, false);
      }
    }
    break;
    default:
      break;
    }
  }
}
```
The thing is when **MQTT_EVENT_DISCONNECTED** occurs **xTaskNotifyWait(0, 0, &command, portMAX_DELAY);** is never called, while another one works properly.

I get this message:

E (31986) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=119
I (31986) MQTT: MQTT_EVENT_ERROR
E (31986) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
I (31996) MQTT: MQTT_EVENT_DISCONNECTED, msg_id=44288
I (42006) MQTT: Other event id: 7
W (43136) MQTT_CLIENT: Connection refused, not authorized
I (43136) MQTT: MQTT_EVENT_ERROR
E (43136) MQTT_CLIENT: MQTT connect failed
I (43146) MQTT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (58146) MQTT: Other event id: 7
W (59216) MQTT_CLIENT: Connection refused, not authorized
I (59216) MQTT: MQTT_EVENT_ERROR
E (59216) MQTT_CLIENT: MQTT connect failed
I (59226) MQTT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (74226) MQTT: Other event id: 7
W (75286) MQTT_CLIENT: Connection refused, not authorized
I (75296) MQTT: MQTT_EVENT_ERROR
E (75296) MQTT_CLIENT: MQTT connect failed
I (75296) MQTT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (90296) MQTT: Other event id: 7
W (91366) MQTT_CLIENT: Connection refused, not authorized
I (91366) MQTT: MQTT_EVENT_ERROR
E (91366) MQTT_CLIENT: MQTT connect failed
I (91376) MQTT: MQTT_EVENT_DISCONNECTED, msg_id=0

I hope someone can help me.

Thanks in advance

**Comment by nopnop2002** [comment]
ESP_LOG in mqtt_event_handler and ESP_LOG in onConnected can be better understood by separating the TAGs.

**Comment by nopnop2002** [comment]
@Kakomis 

I have never used esp_mqtt_client_destroy.

The behavior of this function should be thoroughly examined.

**Comment by Kakomis** [comment]
I'm using single-use credentials for connecting to broker, so I have to request for new credentials before mqtt client try to connect again. For that reason, in a disconnect event I want to request for new credentials once I got them I destroy old mqtt connection and I start a new one, but It doesn't occur since onConnect not respond and the process it's stuck in the mqtt event callback.

I (8406) CONN: WIFI_CONNECTED
W (9316) wifi:<ba-add>idx:0 (ifx:0, 50:46:4a:3e:9f:64), tid:0, ssn:2, winSize:64
I (10346) CONN: [APP] 1 Free memory: 270452 bytes
I (10346) CONN: [APP] 2 Free memory: 270452 bytes
I (10346) MQTT_EVENT: Other event id: 7
I (11356) MQTT_EVENT: MQTT_EVENT_CONNECTED
I (12486) MQTT_EVENT: MQTT_EVENT_SUBSCRIBED, msg_id=13480
E (39856) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=119
I (39856) MQTT_EVENT: MQTT_EVENT_ERROR
E (39856) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
I (39866) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=13480
I (54866) MQTT_EVENT: Other event id: 7
W (55906) MQTT_CLIENT: Connection refused, not authorized
I (55906) MQTT_EVENT: MQTT_EVENT_ERROR
E (55906) MQTT_CLIENT: MQTT connect failed
I (55906) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (65916) MQTT_EVENT: Other event id: 7
W (67296) MQTT_CLIENT: Connection refused, not authorized
I (67296) MQTT_EVENT: MQTT_EVENT_ERROR
E (67296) MQTT_CLIENT: MQTT connect failed
I (67306) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (82306) MQTT_EVENT: Other event id: 7
W (83546) MQTT_CLIENT: Connection refused, not authorized
I (83556) MQTT_EVENT: MQTT_EVENT_ERROR
E (83556) MQTT_CLIENT: MQTT connect failed
I (83556) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (93566) MQTT_EVENT: Other event id: 7
W (94606) MQTT_CLIENT: Connection refused, not authorized
I (94606) MQTT_EVENT: MQTT_EVENT_ERROR
E (94606) MQTT_CLIENT: MQTT connect failed
I (94616) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (109616) MQTT_EVENT: Other event id: 7
W (110806) MQTT_CLIENT: Connection refused, not authorized
I (110806) MQTT_EVENT: MQTT_EVENT_ERROR
E (110806) MQTT_CLIENT: MQTT connect failed
I (110806) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (120816) MQTT_EVENT: Other event id: 7
W (121856) MQTT_CLIENT: Connection refused, not authorized
I (121856) MQTT_EVENT: MQTT_EVENT_ERROR
E (121856) MQTT_CLIENT: MQTT connect failed
I (121856) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0
I (131866) MQTT_EVENT: Other event id: 7
W (133006) MQTT_CLIENT: Connection refused, not authorized
I (133006) MQTT_EVENT: MQTT_EVENT_ERROR
E (133006) MQTT_CLIENT: MQTT connect failed
I (133016) MQTT_EVENT: MQTT_EVENT_DISCONNECTED, msg_id=0

**Comment by nopnop2002** [comment]
where is this error coming from?
```
E (39856) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=119
```

**Comment by Kakomis** [comment]
Ok, I'm working with EMQX broker from there I can kick out clients, I do that in order to simulate a disconnection, that message appear when I do that.

**Comment by nopnop2002** [comment]
Your process may be blocked here.

xQueueReceive(queue, &publish_data, portMAX_DELAY)
