### ISSUE TITLE
is  there some ways to get a device mac within lan (IDFGH-8544)

### ISSUE THREAD

**Issue by featherfly** [espressif/esp-idf#9996]
### Is your feature request related to a problem?

is there some ways to get a device mac within lan, such as `arp -a 192.168.x.x`

**Comment by MaxwellAlan** [comment]
Hi @featherfly 

In response to your request, please clarify the specific usage requirements. 

From our perspective, implementing the 'arp -a' functionality within an IoT chip may not be highly significant. This is because the lwIP protocol stack internally updates and maintains the ARP table regularly. For upper-layer applications, obtaining the MAC address of the counterpart may not be crucial. In most cases, communication at the upper layers is conducted using IP addresses.

**Comment by MaxwellAlan** [comment]
PS: you can get the arp table from here: https://github.com/espressif/esp-lwip/blob/f5c43549e5d12ec2105a43c27986416124143e6e/src/core/ipv4/etharp.c#L105

**Comment by Sherry616** [comment]
Hi @featherfly, could you please share your latest status of this issue? Thanks.

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
